---
title: 'cNMF_HMSC_02_get_results' 
author: "Avishai Wizel"
date: '`r Sys.time()`'
output: 
  html_document: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: TRUE
    number_sections: true
    toc_depth: 2
params: 
  data_out_dir: "./temp_data/" 
---

```{r}
if (interactive()) {
  source("./pipe.R")
  input = get_input(get_current_path())
  output = get_output(get_current_path())
}
```

```{r}
library(reticulate)
library(stringr)
use_virtualenv("/sci/labs/yotamd/lab_share/avishai.wizel/python_envs/Virtual_env/cnmf_dev/",required = T)
py_config() # if you see that r-reticulate has been loaded, terminate r and try again
```

# Functions

```{r warning=FALSE}
```

# Data

```{r}
output_dir_path = params$data_out_dir
cnmf_object_path = input$cnmf_object
```



## NMF {.tabset}


```{python}
from cnmf import cNMF
import pickle
f = open(r.cnmf_object_path , 'rb')
cnmf_obj = pickle.load(f)
f.close()
```



```{r fig.height=7, fig.width=10}
img = png::readPNG(dirname(cnmf_object_path) %s+% "/HMSC_BatchCorrected_NMF.k_selection.png")
plot.new() 
rasterImage(img,  0, 0, 1, 1)
```



```{python}
selected_k = 3
density_threshold = 0.1
cnmf_obj.consensus(k=selected_k, density_threshold=density_threshold,show_clustering=True)
usage_norm, gep_scores, gep_tpm, topgenes = cnmf_obj.load_results(K=selected_k, density_threshold=density_threshold)
```

```{r}
gep_scores = py$gep_scores
gep_tpm = py$gep_tpm
all_metagenes= py$usage_norm
```

```{r}
# save data
write.table(x = gep_scores,file = paste0(params$data_out_dir,"gep_scores.csv"))
write.table(x = all_metagenes,file = paste0(params$data_out_dir,"all_metagenes.csv"))

```

<script src="https://hypothes.is/embed.js" async></script>

