---
title: '`r rstudioapi::getSourceEditorContext()$path %>% basename() %>% gsub(pattern = "\\.Rmd",replacement = "")`' 
author: "Avishai Wizel"
date: '`r Sys.time()`'
output: 
  html_notebook: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: FALSE
    number_sections: true
    toc_depth: 1
---



# Functions

```{r warning=FALSE}
```
# Data

```{r}
script_name = rstudioapi::getSourceEditorContext()$path %>% basename() %>% gsub(pattern = "\\.Rmd",replacement = "")
output_dir_path = paste0("./Data_out/",script_name,"_",Sys.Date())
dir.create(output_dir_path)

```

```{r}
hmsc_cancer_cells = readRDS("./Data_out/03_HMSC_cells_preprocess_2024-05-12/acc1_cancer_cells_2500features_integrated_V5.RDS")
```

```{r}
# # run once
# # Create virtual env of cNMF development branch for using batch correction
# library(reticulate) #  use reticulate 1.24 (1.35 produce "Suitable Python installation for creating a venv not found")
# virtualenv_create("/sci/labs/yotamd/lab_share/avishai.wizel/python_envs/Virtual_env/cnmf_dev", packages = "https://github.com/dylkot/cNMF/archive/development.zip")
# use_virtualenv("/sci/labs/yotamd/lab_share/avishai.wizel/python_envs/Virtual_env/cnmf_dev/",required = T)
# py_install("harmonypy") 
# py_install("scikit-misc")

# for some reason .todense() method is rasing error in preprocess.py. remove all .todense() in /sci/labs/yotamd/lab_share/avishai.wizel/python_envs/Virtual_env/cnmf_dev/lib/python3.8/site-packages/cnmf/preprocess.py
# to avoid this error.
```

```{r}
library(reticulate)
use_virtualenv("/sci/labs/yotamd/lab_share/avishai.wizel/python_envs/Virtual_env/cnmf_dev/",required = T)
py_config() # if you see that r-cnmf_dev has not been loaded, restrat/terminate r and try again

```

```{python}
import os
import pandas as pd
import numpy as np
from scipy.io import mmread
import scipy.sparse as sp
import matplotlib.pyplot as plt
import scanpy as sc
from cnmf import cNMF, Preprocess
import seaborn as sns
np.random.seed(14)
```

```{r}
sc <- import('scanpy', convert = FALSE)
gene_expression = t(as.matrix(GetAssayData(hmsc_cancer_cells,slot='data',assay = "RNA")))
gene_expression = gene_expression[,colSums(gene_expression) != 0] #remove genes with 0 expression in all cells

gene_expression = 2**gene_expression #convert log2(TPM+1) to TPM+1
gene_expression = gene_expression-1 #convert TPM+1 to TPM
hmsc_cancer_cells_filtered  = hmsc_cancer_cells[colnames(gene_expression),]
adata <- sc$AnnData(
  X   = gene_expression, 
  obs = hmsc_cancer_cells_filtered[[]],
  var = GetAssay(hmsc_cancer_cells_filtered,assay = "RNA")[[]]
)


rm(gene_expression)
```

```{python}
p = Preprocess(random_seed=14)
adata = r.adata
(adata_c, adata_tp10k, hvgs) = p.preprocess_for_cnmf(adata, harmony_vars='orig.ident', n_top_rna_genes = 2000,max_scaled_thresh = 50, quantile_thresh = .9999,theta = 2, makeplots=True,save_output_base=r.output_dir_path + "/preprocess_output")
```



```{python}
cnmf_obj_corrected = cNMF(output_dir='./Data/cNMF/batch_corrected_cnmf/', name='BatchCorrected_NMF')
cnmf_obj_corrected.prepare(
  counts_fn='./Data/cNMF/batch_corrected_cnmf/preprocess_output.Corrected.HVG.Varnorm.h5ad',
  tpm_fn='./Data/cNMF/batch_corrected_cnmf/preprocess_output.TP10K.h5ad', genes_file='./Data/cNMF/batch_corrected_cnmf/preprocess_output.Corrected.HVGs.txt',components=np.arange(3,11), n_iter=20, seed=14, num_highvar_genes=2000)
```

```{python}
cnmf_obj_corrected.factorize(worker_i=0, total_workers=1)
cnmf_obj_corrected.combine()
```
```{python}
cnmf_obj.k_selection_plot()
```

```{python}
import pickle
with open('./Data/cNMF/batch_corrected_cnmf/cnmf_obj.pkl', 'wb') as file: 
    # A new file will be created 
    pickle.dump(cnmf_obj_corrected, file) 


```

