---
title: "Myo_lum_score_myo_anti_cor"
author: "Avishai Wizel"
date: 1.1.23
output: 
  html_notebook: 
    code_folding: hide
---

## Parameters:

```{r warning=FALSE}
suffix = ""
data_to_read = "acc1_cancer_cells_15KnCount_V3.RDS"
```

-   suffix = `r suffix`
-   data_to_read = `r data_to_read`

## functions

```{r warning=FALSE}
source_from_github(repositoy = "DEG_functions",version = "0.2.1")
top_correlated <- function(genes, threshold,anti_cor = F) {
  markers_expression = FetchData(object = acc1_cancer_cells,vars = genes,slot = "data") #get genes expression
  markers_average = rowMeans(markers_expression) %>% as.data.frame() %>% rename("average" = 1) #average them
  cor_mat = cor(expression %>% t(), markers_average)%>% as.data.frame() #cor with all genes
  cor_mat = cor_mat[complete.cases(cor_mat),,drop=F]  %>% as.data.frame %>%  rename("corr" = 1) #remove rows with NA in at least one col
  if (threshold<1){ #if threshold is based on pearson correlation 
      if(anti_cor == T){top_genes =   cor_mat %>% as.data.frame %>% select(1) %>% dplyr::filter(.< threshold) %>% rownames()}else{
          top_genes =   cor_mat %>% as.data.frame %>% select(1) %>% dplyr::filter(.> threshold) %>% rownames()
      }
  }else{ #if threshold is based on top correlated genes 
      if(anti_cor == T){threshold  = threshold*(-1)}
      top_genes =   cor_mat %>%  top_n(threshold,corr) %>% rownames()
      }
  return(top_genes)
}
```

## Data

```{r}
acc1_cancer_cells = readRDS("./Data/" %>% paste0(data_to_read))

luminal_pathways = c("CHARAFE_BREAST_CANCER_LUMINAL_VS_BASAL_DN","CHARAFE_BREAST_CANCER_LUMINAL_VS_BASAL_UP","CHARAFE_BREAST_CANCER_LUMINAL_VS_MESENCHYMAL_DN","CHARAFE_BREAST_CANCER_LUMINAL_VS_MESENCHYMAL_UP","HUPER_BREAST_BASAL_VS_LUMINAL_DN","LIM_MAMMARY_LUMINAL_PROGENITOR_UP","SMID_BREAST_CANCER_LUMINAL_B_UP" )

# add luminal pathways
msigdb_gene_set = msigdbr(species = "Homo sapiens") 
msigdb_gene_set = msigdb_gene_set %>%as.data.frame() 
luminal_gs = msigdb_gene_set %>%  dplyr::filter(gs_name %in% luminal_pathways)
luminal_gs = luminal_gs %>% dplyr::distinct(gs_name, gene_symbol) %>% as.data.frame()
```

##  top 25 anti cor to top 25 myo score
```{r}
top_genes =  scan("./Data/top_25_pearson_myo_genes.txt", character(), quiet =  T)
```

```{r}
threshold = 25
anti_cor  = top_correlated(genes = top_genes,threshold = threshold,anti_cor = T)
```

```{r}
anti_cor
```

```{r results='hide'}
enrich_res = genes_vec_enrichment(genes = anti_cor,background = rownames(acc1_cancer_cells),homer = T,title = "lum top enrichment",custom_pathways = luminal_gs)
enrich_res
```
## Top 50
```{r}
threshold = 50
anti_cor  = top_correlated(genes = top_genes,threshold = threshold,anti_cor = T)
```

```{r}
anti_cor
```

```{r results='hide'}
enrich_res = genes_vec_enrichment(genes = anti_cor,background = rownames(acc1_cancer_cells),homer = T,title = "myo top enrichment",custom_pathways = luminal_gs)
enrich_res
```
## Less than 0.2 pearson
```{r}
threshold = -0.2
anti_cor  = top_correlated(genes = top_genes,threshold = threshold,anti_cor = T)
```

```{r}
anti_cor
```

```{r results='hide'}
enrich_res = genes_vec_enrichment(genes = anti_cor,background = rownames(acc1_cancer_cells),homer = T,title = "myo top enrichment",custom_pathways = luminal_gs)
enrich_res
```