---
title: '`r rstudioapi::getSourceEditorContext()$path %>% basename() %>% gsub(pattern = "\\.Rmd",replacement = "")`' 
author: "Avishai Wizel"
date: '`r Sys.time()`'
output:
  # html_notebook:
  #   code_folding: hide
  #   toc: true
  #   toc_collapse: true
  #   toc_float:
  #     collapsed: false
  #   number_sections: true
  #   toc_depth: 1
  html_document:
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float:
      collapsed: TRUE
    number_sections: true
    toc_depth: 2
    df_print: paged

params:
  data_out_dir: "./temp_data/" 

---



# Functions

```{r}
if (interactive()) {
  source("./pipe.R")
  input = get_input(get_current_path())
  output = get_output(get_current_path())
}
```

```{r warning=FALSE}
suppressMessages(library(GSEABase))
source_from_github(repositoy = "DEG_functions",version = "0.2.54")
genesets_h  = geneIds(getGmt(input$genesets_h))
source(input$fc_params)

```

# signature
```{r}

opscc_deg = read.table(file =  input$opscc_deg,row.names = 1,sep = ",",header = T)
hmsc_deg = read.table(file =  input$hmsc_deg,row.names = 1,sep = ",",header = T)

hmsc_top = hmsc_deg %>% filter(avg_log2FC > log2(signature_fc) &
                                 fdr < signature_fdr) %>% rownames()
opscc_top = opscc_deg %>% filter(avg_log2FC > log2(signature_fc) &
                                   fdr < signature_fdr) %>% rownames()

print ("intersect genes:")
intersected_genes = intersect(hmsc_top,opscc_top)
intersected_genes


```
# Venn



## OPSCC and HMSC
```{r}
library(ggvenn)
p = ggvenn::ggvenn(list(hmsc_top = hmsc_top, opscc_top = opscc_top),auto_scale = T)

```

```{r}
pdf(paste0(params$data_out_dir,"venn_HMSC_OPSCC_DEG.pdf"))
p
dev.off()
```

# HMSC GSEA

```{r}
set.seed(NULL)
# create 6 breaks between plot limits in log scale and then exponent, otherwise breaks not good
breaks_fun = function(limits){ 
  print(limits)
  breaks = exp(-seq(-log(limits[1]), -log(limits[2]), length.out = 6))
  breaks[1] = breaks[1] * 0.95 #adjust extreme ticks to prevent truncation
  breaks[6] = breaks[6] * 1.05
  return(signif(breaks, digits = 2))
}

ranked_vec = hmsc_deg[,"avg_log2FC"]%>% setNames(rownames(hmsc_deg)) %>% na.omit() # make named vector
hyp_obj <-hypeR_fgsea(signature = ranked_vec,genesets = genesets_h,up_only = F)

plt = hyp_dots(hyp_obj,merge = F,fdr = 0.2,val = "fdr")
p = plt[[1]] + aes(size=nes)+ 
  guides(size = guide_legend(title="NES",reverse=T))+
  scale_y_continuous(trans = hypeR:::.reverselog_trans(10), 
        breaks =breaks_fun)

p
```
```{r}
pdf(paste0(params$data_out_dir,"HMSC_HPV_signature_GSEA.pdf"))
p
dev.off()
```



# OPSCC GSEA

```{r fig.width=8}
ranked_vec = opscc_deg[,"avg_log2FC"]%>% setNames(rownames(opscc_deg)) %>% na.omit() # make named vector
hyp_obj <-hypeR_fgsea(signature = ranked_vec,genesets = genesets_h,up_only = F)

plt = hyp_dots(hyp_obj,merge = F,fdr = 0.2)
p1 = plt[[1]] + aes(size=nes)+ 
  guides(
    size = guide_legend(title="NES",reverse=T))+
  scale_y_continuous(trans = hypeR:::.reverselog_trans(10), 
        breaks =breaks_fun)

p2 = plt[[2]] + aes(size=nes) +scale_size(trans = 'reverse')+
  guides(
    size = guide_legend(title="NES",reverse=F))+
  scale_y_continuous(trans = hypeR:::.reverselog_trans(10), 
        breaks =breaks_fun)

p1
p2
```
```{r}
pdf(paste0(params$data_out_dir,"OPSCC_HPV_signature_GSEA_up.pdf"),width = 8,height = 5)
p1
dev.off()

pdf(paste0(params$data_out_dir,"OPSCC_HPV_signature_GSEA_down.pdf"),width = 8,height = 5)
p2
dev.off()

```


# SCC GSEA
```{r}
# ranked_vec = scc_deg[,"avg_diff"]%>% setNames(rownames(scc_deg)) %>% na.omit() # make named vector
# hyp_obj <-hypeR_fgsea(signature = ranked_vec,genesets = geneIds(genesets_h),up_only = F)
# 
# plt = hyp_dots(hyp_obj,merge = F,fdr = 0.2)
# plt[[1]] + aes(size=nes)+ 
#   guides(
#     size = guide_legend(title="NES",reverse=T))
# 
# plt[[2]] + aes(size=nes) +scale_size(trans = 'reverse')+
#   guides(
#     size = guide_legend(title="NES",reverse=F))

```
```{r}
# save
# write.xlsx(hyp_obj$data$up$data,paste0(params$data_out_dir,"SCC_GSEA.xlsx"))
```
