---
title: '03_Lum-Myo_HMSC' 
author: "Avishai Wizel"
date: '`r Sys.time()`'
output:
  # html_notebook: 
  #   code_folding: hide
  #   toc: true
  #   toc_collapse: true
  #   toc_float:
  #     collapsed: false
  #   number_sections: true
  #   toc_depth: 1
  html_document: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: TRUE
    number_sections: true
    toc_depth: 2
    df_print: paged
params: 
  data_out_dir: "./temp_data/" 
---


```{r}
if (interactive()) {
  source("./pipe.R")
  input = get_input(get_current_path())
  output = get_output(get_current_path())
}
```

# Functions

```{r warning=FALSE}
source_from_github(repositoy = "DEG_functions",version = "0.2.54")
source_from_github(repositoy = "HMSC_functions",version = "0.1.14",script_name = "functions.R")
source_from_github(repositoy = "cNMF_functions",version = "0.4.04",script_name = "cnmf_functions_V3.R")
source_from_github(repositoy = "sc_general_functions",version = "0.1.34",script_name = "functions.R")
library(hypeR)
library(GSEABase)
library(grid)
library(ComplexHeatmap)
library(ggpubr)
```

# Data

```{r}


hmsc_cancer_cells = readRDS(input$hmsc_cancer_cells)
hmsc_acc_pri_cancer = readRDS(input$hmsc_acc_pri_cancer)
acc_pri = subset(hmsc_acc_pri_cancer,subset = patient.ident != "HMSC")
DefaultAssay(acc_pri) = "RNA"

genesets_h  = getGmt(input$genesets_h)

# luminal_pathways = c("CHARAFE_BREAST_CANCER_LUMINAL_VS_BASAL_DN","CHARAFE_BREAST_CANCER_LUMINAL_VS_BASAL_UP","CHARAFE_BREAST_CANCER_LUMINAL_VS_MESENCHYMAL_DN","CHARAFE_BREAST_CANCER_LUMINAL_VS_MESENCHYMAL_UP","HUPER_BREAST_BASAL_VS_LUMINAL_DN","LIM_MAMMARY_LUMINAL_PROGENITOR_UP","SMID_BREAST_CANCER_LUMINAL_B_UP" )
# 
# # add luminal pathways
# luminal_gs = msigdbr(species = "Homo sapiens") %>% as.data.frame() %>% dplyr::filter(gs_name %in% luminal_pathways)%>% dplyr::distinct(gs_name, gene_symbol) %>% as.data.frame()
```




# HMSC analysis 
```{r}
DefaultAssay(hmsc_cancer_cells) = "integrated"
```

## UMAP 

```{r}
hmsc_cancer_cells = FindClusters(object = hmsc_cancer_cells,verbose = F,resolution = 0.5)
DimPlot(object = hmsc_cancer_cells,pt.size = 2)
```


## Lum Myo score

```{r}
original_myo_genes = c( "TP63", "TP73", "CAV1", "CDH3", "KRT5", "KRT14", "ACTA2", "TAGLN", "MYLK", "DKK3")
original_lum_genes = c("KIT", "EHF", "ELF5", "KRT7", "CLDN3", "CLDN4", "CD24", "LGALS3", "LCN2", "SLPI" )
```



```{r fig.height=8, fig.width=12}
FeaturePlot(hmsc_cancer_cells,features = original_myo_genes)
FeaturePlot(hmsc_cancer_cells,features = original_lum_genes)

```

```{r}
calculate_score.2 <- function(dataset,myo_genes,lum_genes,lum_threshold =1 , myo_threshold = -1) {
  myoscore=FetchData(object =dataset,vars =  myo_genes,slot = "data") %>% rowMeans()
  lescore=FetchData(object =dataset,vars =  lum_genes,slot = "data") %>% rowMeans()
  correlation = cor(lescore,myoscore) %>% round(digits = 2)
  message("correlation of lum score and myo score:" %>% paste(correlation))
  
  
  original_myo_genes = c("TP63", "TP73", "CAV1", "CDH3", "KRT5", "KRT14", "ACTA2", "TAGLN", "MYLK", "DKK3")
  original_lum_genes = c("KIT", "EHF", "ELF5", "KRT7", "CLDN3", "CLDN4", "CD24", "LGALS3", "LCN2", "SLPI")
  orig_myoscore=FetchData(object =dataset,vars =  original_myo_genes,slot = "data") %>% rowMeans()
  orig_lescore=FetchData(object =dataset,vars =  original_lum_genes,slot = "data") %>% rowMeans()
  correlation_to_original_lum = cor(orig_lescore,lescore) %>% round(digits = 2)
  correlation_to_original_myo = cor(orig_myoscore,myoscore) %>% round(digits = 2)

  message("correlation of lum score and original lum score:" %>% paste(correlation_to_original_lum))
  message("correlation of myo score and original myo score:" %>% paste(correlation_to_original_myo))

  dataset=AddMetaData(dataset,lescore-myoscore,"luminal_over_myo")
  print(
    FeaturePlot(object = dataset,features = "luminal_over_myo")
  )
  data = FetchData(object = dataset,vars = "luminal_over_myo")

  
    p = data %>% 
    ggplot(aes( x=luminal_over_myo)) + 
    geom_density() +ylab("Density")+theme(  axis.title=element_text(size=12,face="bold"))+ xlab("Luminal-Myoepithelial spectrum")+ggtitle(paste0("r =",correlation))
    print(p)
  
  lum_cells_num = subset(x = dataset,luminal_over_myo >(lum_threshold)) %>% ncol() /ncol(dataset)
  myo_cells_num = subset(x = dataset,luminal_over_myo <(myo_threshold)) %>% ncol()/ncol(dataset)
  df = data.frame(cell_type = c("myo_cells","lum_cells"),percentage = c(myo_cells_num,lum_cells_num))
  ggplot(data=df, aes(x=cell_type, y=percentage)) +
    geom_bar(stat="identity") + ggtitle("ACC cell types")
  
  return(p)

}


```


```{r}
acc_pri = SetIdent(acc_pri,value = "patient.ident")
p = calculate_score.2(dataset = acc_pri,myo_genes = original_myo_genes,lum_genes = original_lum_genes)
```


```{r}
pdf(paste0(params$data_out_dir,"ACC_lum_myo_spectrum_density.pdf"))
p
dev.off()
```

## Original score of ACC1



```{r}
DefaultAssay(hmsc_cancer_cells) = "integrated"
```

```{r}
p = calculate_score.2(dataset = hmsc_cancer_cells,myo_genes = original_myo_genes,lum_genes = original_lum_genes)
```
```{r}
pdf(paste0(params$data_out_dir,"HMSC_lum_myo_spectrum_density.pdf"))
p
dev.off()
```



```{r}
DefaultAssay(object = hmsc_cancer_cells) = "integrated"
```

```{r fig.height=5, fig.width=10}
library(circlize)

acc_data = FetchData(object = acc_pri,vars = c(original_lum_genes)) %>% cor()
acc_plt = ComplexHeatmap::Heatmap(matrix = acc_data ,name = "pearson", col = colorRamp2(seq(-1, 1, length = 3), c("blue", "#EEEEEE", "red")), heatmap_legend_param = list(at = c(-1, 0, 1)),
    cell_fun = function(j, i, x, y, width, height, fill) {
        grid.text(sprintf("%.2f", acc_data[i, j]), x, y, gp = gpar(fontsize = 7))
}, column_title = "ACC luminal genes")


hmsc_data = FetchData(object = hmsc_cancer_cells,vars = c(original_lum_genes)) %>% cor()
hmsc_plt = ComplexHeatmap::Heatmap(matrix = hmsc_data ,name = "pearson", col = colorRamp2(seq(-1, 1, length = 3), c("blue", "#EEEEEE", "red")), heatmap_legend_param = list(at = c(-1, 0, 1)),
    cell_fun = function(j, i, x, y, width, height, fill) {
        grid.text(sprintf("%.2f", hmsc_data[i, j]), x, y, gp = gpar(fontsize = 7))
}, column_title = "HMSC luminal genes")




p1 = grid.grabExpr(draw(hmsc_plt))
p2 = grid.grabExpr(draw(acc_plt))
p = ggarrange(p1,p2)
p



```


```{r}
pdf(paste0(params$data_out_dir,"Luminal_genes_correlation.pdf"),height = 5,width = 10)
p
dev.off()

```

```{r fig.height=5, fig.width=10}
library(circlize)

acc_data = FetchData(object = acc_pri,vars = c(original_myo_genes)) %>% cor()
acc_plt = ComplexHeatmap::Heatmap(matrix = acc_data,name = "pearson", col = colorRamp2(seq(-1, 1, length = 3), c("blue", "#EEEEEE", "red")), heatmap_legend_param = list(at = c(-1, 0, 1)),
    cell_fun = function(j, i, x, y, width, height, fill) {
        grid.text(sprintf("%.2f", acc_data[i, j]), x, y, gp = gpar(fontsize = 7))
}, column_title = "ACC Myoepithelial  genes")

hmsc_data = FetchData(object = hmsc_cancer_cells,vars = c(original_myo_genes)) %>% cor()
hmsc_plt = ComplexHeatmap::Heatmap(matrix = hmsc_data,name = "pearson", col = colorRamp2(seq(-1, 1, length = 3), c("blue", "#EEEEEE", "red")), heatmap_legend_param = list(at = c(-1, 0, 1)),
    cell_fun = function(j, i, x, y, width, height, fill) {
        grid.text(sprintf("%.2f", hmsc_data[i, j]), x, y, gp = gpar(fontsize = 7))
}, column_title = "HMSC Myoepithelial  genes")

p1 = grid.grabExpr(draw(hmsc_plt))
p2 = grid.grabExpr(draw(acc_plt))
p = ggarrange(p1,p2)
p
```
```{r}
pdf(paste0(params$data_out_dir,"Myo_genes_correlation.pdf"),height = 5,width = 10)
p
dev.off()

```

Barplot

```{r}
hmsc_data = FetchData(object = hmsc_cancer_cells,vars = c(original_lum_genes)) %>% cor()
acc_data = FetchData(object = acc_pri,vars = c(original_lum_genes)) %>% cor()
acc_data_vector = acc_data[upper.tri(acc_data,diag=F)] %>% as_vector()
hmsc_data_vector = hmsc_data[upper.tri(hmsc_data,diag=F)] %>% as_vector()

all_correlation = data.frame(pearson = c(acc_data_vector,hmsc_data_vector),
                             data = c(rep("acc", length(acc_data_vector)), rep("hmsc", length(hmsc_data_vector))))

p = ggplot(all_correlation, aes(x=pearson, color=data,fill=data)) +
  geom_histogram( position="identity",alpha=0.5)+ggtitle("Luminal genes correlations")
p
```

```{r}
pdf(paste0(params$data_out_dir,"Luminal_genes_correlation_barplot.pdf"),height = 5,width = 10)
p
dev.off()

```


```{r}
hmsc_data = FetchData(object = hmsc_cancer_cells,vars = c(original_myo_genes)) %>% cor()
acc_data = FetchData(object = acc_pri,vars = c(original_myo_genes)) %>% cor()
acc_data_vector = acc_data[upper.tri(acc_data,diag=F)] %>% as_vector()
hmsc_data_vector = hmsc_data[upper.tri(hmsc_data,diag=F)] %>% as_vector()

all_correlation = data.frame(pearson = c(acc_data_vector,hmsc_data_vector),
                             data = c(rep("acc", length(acc_data_vector)), rep("hmsc", length(hmsc_data_vector))))

p = ggplot(all_correlation, aes(x=pearson, color=data,fill=data)) +
  geom_histogram( position="identity",alpha=0.5)+ggtitle("Myo genes correlations")
p
```



```{r}
pdf(paste0(params$data_out_dir,"Myo_genes_correlation_barplot.pdf"),height = 5,width = 10)
p
dev.off()

```

# NOTCH ligands correlation

```{r}
DefaultAssay(hmsc_cancer_cells) = "integrated"
```

```{r}

myo_genes =  c("COL16A1" ,"RP1-39G22.4","CD200",   "MYLK","TP63","KCNMB1",  "ADAMTS2", "CLIC3",   "SNCG","ACTA2",   "TAGLN","CNN1" ,"MIR7974",  
 "MYL9","POM121L9P" )


myoscore=FetchData(object =hmsc_cancer_cells,vars =  myo_genes) %>% rowMeans()
  
notch_ligands = c("JAG1","JAG2","DLL1")

notch_ligands_score = hmsc_cancer_cells %>% FetchData(vars = notch_ligands) %>% rowMeans()

data = data.frame(notch_score = notch_ligands_score,myo_score = myoscore)
```

```{r}
sp <- ggscatter(data, x = "notch_score", y = "myo_score",
   add = "reg.line",  # Add regressin line
   add.params = list(color = "blue", fill = "lightgray"), # Customize reg. line
   conf.int = TRUE # Add confidence interval
   )
# Add correlation coefficient
sp + stat_cor(method = "pearson", label.x = 3, label.y = 5)+xlab("Notch Ligands Expression")+ylab("Myoepithelial Score")

```


## remove outlier
```{r}
notch_scores_filtered = notch_ligands_score[notch_ligands_score < 6]
myoscore = myoscore[names(myoscore) %in% names(notch_scores_filtered)]

data = data.frame(notch_score = notch_scores_filtered,myo_score = myoscore)
sp <- ggscatter(data, x = "notch_score", y = "myo_score",
   add = "reg.line",  # Add regressin line
   add.params = list(color = "blue", fill = "lightgray"), # Customize reg. line
   conf.int = TRUE)+ # Add confidence interval
   stat_cor(method = "pearson", label.x = 3, label.y = 5) + # Add correlation coefficient
   xlab("Notch Ligands Expression")+ylab("Myoepithelial Score")
sp 

```


```{r}
pdf(paste0(params$data_out_dir,"myo_notch_ligands_correlation_no_ourlier.pdf"))
sp
dev.off()
```

```{r}

myo_genes =  c("COL16A1" ,"RP1-39G22.4","CD200",   "MYLK","TP63","KCNMB1",  "ADAMTS2", "CLIC3",   "SNCG","ACTA2",   "TAGLN","CNN1" ,"MIR7974",  
 "MYL9","POM121L9P" )


myoscore=FetchData(object =hmsc_cancer_cells,vars =  myo_genes) %>% rowMeans()
  
notch_targets = c("NRARP", "NOTCH3", "HES4", "HEY1",  "HEY2" )

notch_targets_score = hmsc_cancer_cells %>% FetchData(vars = notch_targets) %>% rowMeans()

data = data.frame(notch_score = notch_targets_score,myo_score = myoscore)
```

```{r}
sp <- ggscatter(data, x = "notch_score", y = "myo_score",
   add = "reg.line",  # Add regressin line
   add.params = list(color = "blue", fill = "lightgray"), # Customize reg. line
   conf.int = TRUE)+ # Add confidence interval
   stat_cor(method = "pearson", label.x = 3, label.y = 5) + # Add correlation coefficient
   xlab("Notch Targets Expression")+ylab("Myoepithelial Score")
sp 
```

```{r}
pdf(paste0(params$data_out_dir,"myo_notch_targets_correlation_no_ourlier.pdf"))
sp
dev.off()
```