---
title: '04_HMSC_vs_ACC' 
author: "Avishai Wizel"
date: '`r Sys.time()`'
output:
  # html_notebook: 
  #   code_folding: hide
  #   toc: true
  #   toc_collapse: true
  #   toc_float:
  #     collapsed: false
  #   number_sections: true
  #   toc_depth: 1
  html_document: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: TRUE
    number_sections: true
    toc_depth: 2
    df_print: paged
params: 
  data_out_dir: "./temp_data/" 
   
---

```{r}
if (interactive()) {
  source("./pipe.R")
  input = get_input(get_current_path())
  output = get_output(get_current_path())
}
```

# Functions



```{r warning=FALSE}
source_from_github(repositoy = "DEG_functions",version = "0.2.56")
source_from_github(repositoy = "HMSC_functions",version = "0.1.14",script_name = "functions.R")
source_from_github(repositoy = "cNMF_functions",version = "0.4.04",script_name = "cnmf_functions_V3.R")
source_from_github(repositoy = "sc_general_functions",version = "0.1.34",script_name = "functions.R")
library(hypeR)
source(input$fc_params)
library(hypeR)
suppressPackageStartupMessages(library(GSEABase))
library(grid)
library(ComplexHeatmap)
library(ggpubr)
library(stringr)
library(data.table)
library(rstatix)
library(ggstatsplot)
```

# Data

```{r}
hmsc_cancer_cells = readRDS(input$hmsc_cancer_cells)
hmsc_acc_pri_cancer = readRDS(input$hmsc_acc_pri_cancer)
acc_pri = subset(hmsc_acc_pri_cancer,subset = patient.ident != "HMSC")
DefaultAssay(acc_pri) = "RNA"

genesets_h  = getGmt(input$genesets_h)
ensembl = readRDS(input$ensembl)

# luminal_pathways = c("CHARAFE_BREAST_CANCER_LUMINAL_VS_BASAL_DN","CHARAFE_BREAST_CANCER_LUMINAL_VS_BASAL_UP","CHARAFE_BREAST_CANCER_LUMINAL_VS_MESENCHYMAL_DN","CHARAFE_BREAST_CANCER_LUMINAL_VS_MESENCHYMAL_UP","HUPER_BREAST_BASAL_VS_LUMINAL_DN","LIM_MAMMARY_LUMINAL_PROGENITOR_UP","SMID_BREAST_CANCER_LUMINAL_B_UP" )
# 
# # add luminal pathways
# luminal_gs = msigdbr(species = "Homo sapiens") %>% as.data.frame() %>% dplyr::filter(gs_name %in% luminal_pathways)%>% dplyr::distinct(gs_name, gene_symbol) %>% as.data.frame()
```




# HMSC vs ACC

## UMAP

```{r}
DimPlot(hmsc_acc_pri_cancer,group.by = "patient.ident",label = T)
```


```{r}
# calculate lum/myo spectrum

myo_genes = c("TP63", "TP73", "CAV1", "CDH3", "KRT5", "KRT14", "ACTA2", "TAGLN", "MYLK", "DKK3")
lum_genes = c("KIT", "EHF", "ELF5", "KRT7", "CLDN3", "CLDN4", "CD24", "LGALS3", "LCN2", "SLPI")

myoscore=FetchData(object =hmsc_acc_pri_cancer,vars =  myo_genes,slot = "data") %>% rowMeans()
lescore=FetchData(object =hmsc_acc_pri_cancer,vars =  lum_genes,slot = "data") %>% rowMeans()
hmsc_acc_pri_cancer=AddMetaData(hmsc_acc_pri_cancer,lescore-myoscore,"luminal_over_myo")
```


```{r}
# plot
FeaturePlot(object = hmsc_acc_pri_cancer,features = "luminal_over_myo") & scale_color_gradientn(colours = c("blue"," grey","red"))
```

```{r}
FeaturePlot(object = hmsc_acc_pri_cancer,features = c("MYB"),pt.size = 1)
p = FeaturePlot(object = hmsc_acc_pri_cancer,features = c("kaye_acc_score"),pt.size = 1,combine = T)
p

```



```{r}
pdf(paste0(params$data_out_dir,"/kaye_acc_score_AllCancerCells.pdf"))
p
dev.off()
```

```{r}
notch_targets = c("NRARP", "NOTCH3", "HES4", "HEY1",  "HEY2" )
notch_targets_score = hmsc_acc_pri_cancer %>% FetchData(vars = notch_targets) %>% rowMeans()
hmsc_acc_pri_cancer=AddMetaData(hmsc_acc_pri_cancer,notch_targets_score, "notch_targets_score")
FeaturePlot(object = hmsc_acc_pri_cancer,features = c("notch_targets_score"),pt.size = 1)

```



## enrichment analysis 

```{r fig.width=8, echo=TRUE,results='hide',fig.keep='all'}
hmsc_acc_pri_cancer = SetIdent(hmsc_acc_pri_cancer, value ="patient.ident")
deg <-
  FindMarkers(
    hmsc_acc_pri_cancer,
    ident.1 = "HMSC",
    features = VariableFeatures(hmsc_acc_pri_cancer),
    densify = T,
    assay = "RNA",
    mean.fxn = function(x) {
      return(log(rowMeans(x) + 1, base = 2)) # change fun to calculate logFC in log space data (default to exponent data)
    }
  )

```

```{r}
library(biomaRt)
IDs <- rownames(deg)
genedesc <- getBM(attributes=c('external_gene_name','description'), filters = 'external_gene_name', values = IDs, mart =ensembl)
acc_deg_desc = left_join(x = rownames_to_column(deg),y = genedesc,by = c("rowname"= "external_gene_name"))
names(acc_deg_desc)[1] = "gene"
hmsc_up_genes = acc_deg_desc [acc_deg_desc$avg_log2FC>0,]
acc_up_genes = acc_deg_desc [acc_deg_desc$avg_log2FC<0,]
fwrite(hmsc_up_genes,file = params$data_out_dir %s+% "hmsc_up_genes.csv",row.names = F)
fwrite(acc_up_genes,file = params$data_out_dir %s+% "cc_up_genes.csv",row.names = F)

```

```{r fig.height=6, fig.width=6, results='asis'}
ranked_vec = deg[,"avg_log2FC"]%>% setNames(rownames(deg)) %>% na.omit() # make named vector
hyp_obj <-hypeR_fgsea(signature = ranked_vec,genesets = geneIds(genesets_h),up_only = F)

plt = hyp_dots(hyp_obj,merge = T,fdr = 0.2)
plt+ scale_y_discrete(limits = plyr::arrange(plt$data,signature,significance)[,"label"])+ 
  scale_colour_gradient2(low = "red",mid = "black",high = "black",midpoint = 0.1)



```

```{r fig.height=4, fig.width=12, results='asis'}
plt = hyp_dots(hyp_obj,merge = F,fdr = 0.2)

plt1 = plt$up+ aes(color=nes)+ggtitle("Up in HMSC")+ scale_colour_gradient2(low = "#E53935",mid = "white",high = "#E53935",midpoint = 0,limits = c(-3,3))

plt2 = plt$dn+ aes(color=nes)+ggtitle("Down in HMSC")+  scale_colour_gradient2(low = "#E53935",mid = "white",high = "#E53935",midpoint = 0,limits = c(-3,3))



p = ggarrange(plt1,plt2,common.legend = T,nrow = 1,legend = "right")
p 
```


```{r fig.width=10}
# plot GSEA
args = list(
  name = c("up","dn"),
  color = c("dodgerblue","indianred2"),
  title  = c("Up in HMSC","Up in ACC")
)
p_list = list()

for (i in 1:2) {
  name = args$name[i]
  color = args$color[i]
  title = args$title[i]
  
  final_result = hyp_obj$data[[name]]$data
  final_result = final_result %>% filter(fdr<0.2) 
  final_result$fdr = -log10(final_result$fdr)
  p <- ggplot(data = final_result, aes(x = reorder(label,fdr),y = fdr)) +
    geom_bar(stat = "identity", fill = color)  +
    coord_flip() + 
    geom_hline(yintercept = -log10(0.05), colour = "black", linetype = "longdash", size = 0.8,alpha = 0.5)+
    xlab("Pathway") + 
      scale_fill_manual(drop = FALSE) + ylab("FDR") + 
      geom_text(aes_string(label = "label", y = 0), 
                size = 4, color = "black", position = position_dodge(1), 
                hjust = 0) +
    scale_y_continuous(labels = function(x) {parse(text = paste0("10^-",x))}, # set fdr format 10^-X
                       expand = expansion(mult = c(0, 0.1)))+ #expand to avoid cut off
    theme(axis.text.y = element_blank(), axis.ticks.y = element_blank(),axis.text.x = element_text(size = 10)) +  
    ggtitle(title)
  p_list[[name]] = p
  
}
p = p_list[[1]]+p_list[[2]]
p
```
```{r}
pdf(paste0(params$data_out_dir,"ACC_vs_HMSC_GSEA_no_filtering_barplot.pdf"),width = 10)
p
dev.off()
```

## Cell cycle score  {.tabset}



```{r results='hide'}
hallmark_name = "GO_MITOTIC_CELL_CYCLE"
acc_pri = FindVariableFeatures(object = acc_pri,nfeatures = 15000)
acc_pri = ScaleData(object = acc_pri,features = VariableFeatures(acc_pri))
geneIds= genesets_h[[hallmark_name]]@geneIds %>% intersect(VariableFeatures(acc_pri)) 
score <- apply(acc_pri@assays$RNA@scale.data[geneIds,],2,mean)
acc_pri=AddMetaData(acc_pri,score,hallmark_name)

hmsc_cancer_cells = FindVariableFeatures(object = hmsc_cancer_cells,nfeatures = 15000)
hmsc_cancer_cells = ScaleData(object = hmsc_cancer_cells,features = VariableFeatures(hmsc_cancer_cells))
geneIds= genesets_h[[hallmark_name]]@geneIds %>% intersect(VariableFeatures(hmsc_cancer_cells)) 
score <- apply(hmsc_cancer_cells@assays$integrated@scale.data[geneIds,],2,mean)
hmsc_cancer_cells=AddMetaData(hmsc_cancer_cells,score,hallmark_name)

```

```{r echo=TRUE, results='asis'}
acc_cc_scores = FetchData(object = acc_pri,vars = "GO_MITOTIC_CELL_CYCLE")
hmsc_cc_scores = FetchData(object = hmsc_cancer_cells,vars = "GO_MITOTIC_CELL_CYCLE")

distributions_plt = ggplot() +
  geom_density(aes(GO_MITOTIC_CELL_CYCLE, fill = "ACC"), alpha = .2, data = acc_cc_scores) +
  geom_density(aes(GO_MITOTIC_CELL_CYCLE, fill = "HMSC"), alpha = .2, data = hmsc_cc_scores) +
  scale_fill_manual(name = "Dataset", values = c(ACC = "red", HMSC = "green"))+ geom_vline(aes(xintercept=0.3),
            color="blue", linetype="dashed", size=1) +ggtitle("'GO_MITOTIC_CELL_CYCLE'  score distribution")

print_tab(plt = distributions_plt,title = "score distribution",subtitle_num = 3)

```


```{r echo=TRUE, results='asis'}
hmsc_cc_cells = (sum(hmsc_cancer_cells@meta.data[[hallmark_name]]> 0.3) /ncol(hmsc_cancer_cells)) %>% round(digits = 3)*100
acc_cc_cells = (sum(acc_pri@meta.data[[hallmark_name]]> 0.3)/ncol(acc_pri)) %>% round(digits = 3)*100
df = data.frame(Dataset = c("HMSC","ACC"), cycling_cells_percentage = c(hmsc_cc_cells,acc_cc_cells))
cycling_cells_plt = ggplot(data=df, aes(x=Dataset, y=cycling_cells_percentage)) +
  geom_text(aes(label=cycling_cells_percentage), vjust=0, color="black", size=3.5)+
  geom_bar(stat="identity")+ylab(" % cycling cells")+
  geom_bar(stat="identity", fill="steelblue")+
  theme_minimal() + ggtitle("Cycling cells count")

print_tab(plt = cycling_cells_plt,title = "# cycling cells",subtitle_num = 3)
```


```{r}
pdf(paste0(params$data_out_dir,"/CC_distributions.pdf"))
distributions_plt
dev.off()

pdf(paste0(params$data_out_dir,"/cycling_cells.pdf"))
cycling_cells_plt
dev.off()
```


```{r fig.height=8, fig.width=10, results='asis'}
print_tab(plt = 
            FeaturePlot(hmsc_acc_pri_cancer,features = c("MKI67","CDK1","MCM2","CDC20"))
          ,title = "CC genes",subtitle_num = 3)
```

## Cycling cells filtering {.tabset}
```{r warning=FALSE}
#add score to all acc cancer cells
# geneIds= genesets[[hallmark_name]]@geneIds %>% intersect(VariableFeatures(all_acc_cancer_cells,assay = "integrated")) 
# score <- apply(all_acc_cancer_cells@assays$integrated@scale.data[geneIds,],2,mean)

#add score to all acc cancer cells
cc_all = c(acc_pri$GO_MITOTIC_CELL_CYCLE, hmsc_cancer_cells$GO_MITOTIC_CELL_CYCLE) %>% as.data.frame()
hmsc_acc_pri_cancer=AddMetaData(hmsc_acc_pri_cancer,cc_all,hallmark_name)

#filter:
all_acc_cancer_cells_ccFiltered=hmsc_acc_pri_cancer[,hmsc_acc_pri_cancer@meta.data[[hallmark_name]]< 0.3]


min_threshold = min(hmsc_acc_pri_cancer$GO_MITOTIC_CELL_CYCLE)
max_threshold = max(hmsc_acc_pri_cancer$GO_MITOTIC_CELL_CYCLE)
```

```{r, results='asis'}
library(viridis)
p_before = FeaturePlot(object = hmsc_acc_pri_cancer,features = hallmark_name) +
  ggtitle("Before cc filtering") &
            scale_color_gradientn(colours = plasma(n = 10, direction = -1),
                                  limits = c(min_threshold, max_threshold))

print_tab(plt = p_before ,title = "Before CC filtering",subtitle_num = 3)

p_after =  FeaturePlot(object = all_acc_cancer_cells_ccFiltered,features = hallmark_name) + 
            ggtitle("After cc filtering") &
            scale_color_gradientn(colours = plasma(n = 10, direction = -1), limits = c(min_threshold, max_threshold))
print_tab(plt = p_after, title = "After CC filtering" ,subtitle_num = 3)

```

```{r}
pdf(paste0(params$data_out_dir,"/ACC_vs_HMSC_cc_score_before.pdf"),width = 8,height = 5)
p_before
dev.off()

pdf(paste0(params$data_out_dir,"/ACC_vs_HMSC_cc_score_after.pdf"),width = 8,height = 5)
p_after
dev.off()

```


## DEG

```{r fig.width=8, echo=TRUE, results='asis',fig.keep='all'}
all_acc_cancer_cells_ccFiltered = SetIdent(all_acc_cancer_cells_ccFiltered, value ="patient.ident")
all_acc_cancer_cells_ccFiltered = FindVariableFeatures(all_acc_cancer_cells_ccFiltered,nfeatures = 15000,assay = "integrated")
deg <-
  FindMarkers(
    all_acc_cancer_cells_ccFiltered,
    ident.1 = "HMSC",
    features = VariableFeatures(all_acc_cancer_cells_ccFiltered,assay = "integrated"),
    densify = T,
    verbose = T,
    slot = "data",
     logfc.threshold = 0,
    mean.fxn = function(x) {
      return(log(rowMeans(x) + 1,base = 2)) # change func to calculate logFC in log space data (default to exponent data)
    },
    assay = "RNA"
  )
```



```{r fig.height=4, fig.width=12, results='asis'}
ranked_vec = deg[,"avg_log2FC" ]%>% setNames(rownames(deg)) %>% na.omit() # make named vector
hyp_obj <-hypeR_fgsea(signature = ranked_vec,genesets = geneIds(genesets_h),up_only = F)
plt = hyp_dots(hyp_obj,merge = F,fdr = 0.2)

plt1 = plt$up+ aes(size=nes)+ggtitle("Up in HMSC")+ 
  guides(
    size = guide_legend(title="|NES|",reverse=T))

plt2 = plt$dn+ aes(size=nes)+ggtitle("Down in HMSC")+scale_size(trans = 'reverse')+
    guides(
    size = guide_legend(title="|NES|",reverse=F)) 

p = ggarrange(plt1,plt2,common.legend = T,nrow = 1,legend = "right")
p

```

```{r}
pdf(paste0(params$data_out_dir,"/ACC_vs_HMSC_GSEA.pdf"),width = 12,height = 4)
p
dev.off()
```

```{r fig.width=10}
# plot GSEA
args = list(
  name = c("up","dn"),
  color = c("dodgerblue","indianred2"),
  title  = c("Up in HMSC","Up in ACC")
)
p_list = list()

for (i in 1:2) {
  name = args$name[i]
  color = args$color[i]
  title = args$title[i]
  
  final_result = hyp_obj$data[[name]]$data
  final_result = final_result %>% filter(fdr<0.2) 
  final_result$fdr = -log10(final_result$fdr)
  p <- ggplot(data = final_result, aes(x = reorder(label,fdr),y = fdr)) +
    geom_bar(stat = "identity", fill = color)  +
    coord_flip() + 
    geom_hline(yintercept = -log10(0.05), colour = "black", linetype = "longdash", size = 0.8,alpha = 0.5)+
    xlab("Pathway") + 
      scale_fill_manual(drop = FALSE) + ylab("FDR") + 
      geom_text(aes_string(label = "label", y = 0), 
                size = 4, color = "black", position = position_dodge(1), 
                hjust = 0) +
    scale_y_continuous(labels = function(x) {parse(text = paste0("10^-",x))}, # set fdr format 10^-X
                       expand = expansion(mult = c(0, 0.1)))+ #expand to avoid cut off
    theme(axis.text.y = element_blank(), axis.ticks.y = element_blank(),axis.text.x = element_text(size = 10)) +  
    ggtitle(title)
  p_list[[name]] = p
  
}
p = p_list[[1]]+p_list[[2]]
p
```


```{r}
pdf(paste0(params$data_out_dir,"ACC_vs_HMSC_GSEA_cc_filtered_barplot.pdf"),width = 10)
p
dev.off()
```



```{r}

volcano_plt = volcano_plot(de_genes = deg,fdr_cutoff = volcano_fdr,fc_cutoff = volcano_fc, ident1 = "HMSC",ident2 = "ACC",top_genes_text = 0)
volcano_plt
```






```{r}
pdf(paste0(params$data_out_dir,"/volcano_plot_ACC_VS_HMSC.pdf"))
volcano_plt
dev.off()

```

```{r}
write.csv2(x = deg,file = paste0(params$data_out_dir,"HMSC_ACC_DEG.csv"))
```

```{r}
deg$fdr = p.adjust(p = deg$p_val ,method = "fdr")

print("up in ACC:")
deg %>% filter(avg_log2FC< (-volcano_fc) & fdr < volcano_fdr) %>% nrow()

print("up in HMSC:")
deg %>% filter(avg_log2FC > (volcano_fc) & fdr < volcano_fdr) %>% nrow()

```


# correlation


<!-- ```{r} -->
<!-- hmsc_acc_pri_cancer = FindVariableFeatures(hmsc_acc_pri_cancer,nfeatures = 15000) -->
<!-- cancer_data = FetchData(hmsc_acc_pri_cancer,vars = "orig.ident") %>% mutate(cancer = if_else( -->
<!--   condition = orig.ident %in% c("ACC.plate2" ,"ACC1.P3"), -->
<!--   true = "HMSC", -->
<!--   false = "ACC"  )) %>% select(-orig.ident) -->
<!-- data = as.data.frame(hmsc_acc_pri_cancer@assays$integrated@data[VariableFeatures(hmsc_acc_pri_cancer),]) -->
<!-- all_cells_pearson = cor(data,method = "spearman") -->
<!-- row_ha = rowAnnotation(df = cancer_data, col = list(cancer  = c(HMSC = "red",ACC = "green"))) -->


<!-- ComplexHeatmap::Heatmap(matrix = all_cells_pearson ,name = "pearson", col = circlize::colorRamp2(seq(0, 1, length = 3), c("blue", "#EEEEEE", "red")),show_column_names = F,show_row_names = F,right_annotation = row_ha,clustering_distance_columns = "euclidean",clustering_distance_rows = "euclidean",clustering_method_columns = "average",clustering_method_rows = "average") -->

<!-- ``` -->

<!-- ```{r} -->
<!-- ComplexHeatmap::Heatmap(matrix = all_cells_pearson ,name = "pearson", col = circlize::colorRamp2(seq(0, 1, length = 3), c("blue", "#EEEEEE", "red")),show_column_names = F,show_row_names = F,right_annotation = row_ha,clustering_distance_columns = "euclidean",clustering_distance_rows = "euclidean",clustering_method_columns = "ward.D2",clustering_method_rows = "ward.D2") -->
<!-- ``` -->

<!-- ```{r} -->
<!-- # ACC cells: -->
<!-- acc_cells_comparisons  <- expand.grid( -->
<!--   cell_1 =  rownames(cancer_data[cancer_data$cancer == "ACC",,drop=F]), cell_2 =  rownames(cancer_data[cancer_data$cancer == "ACC",,drop=F]))%>% -->
<!--   filter(cell_1 != cell_2) #remove self comparisons  -->

<!-- acc_cells_correlation = c() -->
<!-- acc_cells_correlation = apply(acc_cells_comparisons, MARGIN = 1, FUN = function(x,matrix){ -->
<!--   cor_value = matrix[x[1],x[2]] -->
<!--   acc_cells_correlation = c(acc_cells_correlation,cor_value) -->
<!-- }, -->
<!-- all_cells_pearson) -->

<!-- # HMSC-ACC cells  -->
<!-- acc_hmsc_cells_comparisons  <- expand.grid( -->
<!--   cell_1 =  rownames(cancer_data[cancer_data$cancer == "ACC",,drop=F]), cell_2 =  rownames(cancer_data[cancer_data$cancer == "HMSC",,drop=F])) -->

<!-- acc_hmsc_cells_correlation = c() -->
<!-- acc_hmsc_cells_correlation = apply(acc_hmsc_cells_comparisons, MARGIN = 1, FUN = function(x,matrix){ -->
<!--   cor_value = matrix[x[1],x[2]] -->
<!--   acc_hmsc_cells_correlation = c(acc_hmsc_cells_correlation,cor_value) -->
<!-- }, -->
<!-- all_cells_pearson) -->

<!-- # HMSC cells  -->
<!-- hmsc_cells_comparisons  <- expand.grid( -->
<!--   cell_1 =  rownames(cancer_data[cancer_data$cancer == "HMSC",,drop=F]), cell_2 =  rownames(cancer_data[cancer_data$cancer == "HMSC",,drop=F]))%>% -->
<!--   filter(cell_1 != cell_2) #remove self comparisons  -->

<!-- hmsc_cells_correlation = c() -->
<!-- hmsc_cells_correlation = apply(hmsc_cells_comparisons, MARGIN = 1, FUN = function(x,matrix){ -->
<!--   cor_value = matrix[x[1],x[2]] -->
<!--   hmsc_cells_correlation = c(hmsc_cells_correlation,cor_value) -->
<!-- }, -->
<!-- all_cells_pearson) -->


<!-- all_correlation  = data.frame(pearson = c(acc_cells_correlation,acc_hmsc_cells_correlation,hmsc_cells_correlation), -->
<!--                               dataset = c(rep("ACC-ACC", length(acc_cells_correlation)),rep("ACC-HMSC", length(acc_hmsc_cells_correlation)), -->
<!--                                           rep("HMSC-HMSC", length(hmsc_cells_correlation)))) -->
<!-- p = ggplot(all_correlation, aes(x=pearson, color=dataset,fill=dataset)) + -->
<!--   geom_histogram( position="identity",alpha=0.5)+ -->
<!--   scale_y_log10() -->
<!-- p -->
<!-- ``` -->

# clustering 
```{r}
hmsc_acc_pri_cancer <- FindClusters(hmsc_acc_pri_cancer, resolution = 0.01)
hmsc_acc_pri_cancer$seurat_clusters %>% table()
data = FetchData(hmsc_acc_pri_cancer,vars = c("orig.ident","seurat_clusters")) %>% mutate(cancer = if_else(
  condition = orig.ident %in% c("ACC.plate2" ,"ACC1.P3"),
  true = "HMSC",
  false = "ACC"  )) %>% select(-orig.ident)

test = fisher_test(table(data))
p = ggbarstats(
  data,
  cancer,
  seurat_clusters,
  results.subtitle = FALSE,
  subtitle = paste0( "p-value = ",test$p),
  digits.perc = 2)
p


```

```{r}
pdf(paste0(params$data_out_dir,"HMSC_ACC_clusters.pdf"),height = 7,width = 8)
p
dev.off()

```
