---
title: '05_HPV_analysis' 
author: "Avishai Wizel"
date: '`r Sys.time()`'
output:
  # html_notebook: 
  #   code_folding: hide
  #   toc: true
  #   toc_collapse: true
  #   toc_float:
  #     collapsed: false
  #   number_sections: true
  #   toc_depth: 1
  html_document: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: TRUE
    number_sections: true
    toc_depth: 2
    df_print: paged
params: 
  data_out_dir: "./temp_data/" 
---


```{r}
if (interactive()) {
  source("./pipe.R")
  input = get_input(get_current_path())
  output = get_output(get_current_path())
}
```

# Functions

```{r warning=FALSE}
source_from_github(repositoy = "DEG_functions",version = "0.2.54")
source_from_github(repositoy = "HMSC_functions",version = "0.1.14",script_name = "functions.R")
source_from_github(repositoy = "sc_general_functions",version = "0.1.34",script_name = "functions.R")
source(input$fc_params)
library(hypeR)
library(GSEABase)
library(grid)
library(ComplexHeatmap)
library(ggpubr)
library(stringr)
library(data.table)
library(ggstatsplot)
```

# Data

```{r}
hmsc_cancer_cells = readRDS(input$hmsc_cancer_cells)
genesets_h  = getGmt(input$genesets_h)
pid_genesets = getGmt(input$genesets_cp_pid)
```

# HPV UMAP

```{r}
HPV33_P3 = fread(input$hpv_conuts_data_p3,col.names = c("plate","reads")) %>% as.data.frame()
HPV33_P3.df = HPV33_P3 %>% mutate(
  plate = gsub(x =HPV33_P3$plate, replacement = "",pattern = "_.*$") 
  %>% gsub(pattern = "-P",replacement = ".P") 
  %>% gsub(pattern = "-",replacement = "_",)
  )
HPV33_P3.df = HPV33_P3.df %>% dplyr::filter(HPV33_P3.df$plate %in% colnames(hmsc_cancer_cells))
rownames(HPV33_P3.df)  <- HPV33_P3.df$plate
HPV33_P3.df$plate = NULL


HPV33_P2 = fread(input$hpv_conuts_data_p2,col.names = c("plate","reads")) %>% as.data.frame()
HPV33_P2.df = HPV33_P2 %>% mutate(
  plate = gsub(x =HPV33_P2$plate, replacement = "",pattern = "_.*$") 
  %>% gsub(pattern = "plate2-",replacement = "plate2_",)
  %>% gsub(pattern = "-",replacement = "\\.",)
  )
HPV33_P2.df = HPV33_P2.df %>% dplyr::filter(HPV33_P2.df$plate %in% colnames(hmsc_cancer_cells))
rownames(HPV33_P2.df)  <- HPV33_P2.df$plate
HPV33_P2.df$plate = NULL

HPV33 = rbind(HPV33_P3.df,HPV33_P2.df)
hmsc_cancer_cells = AddMetaData(object = hmsc_cancer_cells,metadata = HPV33,col.name = "HPV33.reads")
FeaturePlot(hmsc_cancer_cells,features = "HPV33.reads",max.cutoff = 10)
```

# HPV reads count
```{r}

data = FetchData(object = hmsc_cancer_cells,vars = "HPV33.reads")

data = data %>% mutate("0 reads" = if_else(condition = HPV33.reads == 0,true = 1,false = 0))
data = data %>% mutate("1 reads" = if_else(condition = HPV33.reads == 1,true = 1,false = 0))
data = data %>% mutate("2 reads" = if_else(condition = HPV33.reads == 2,true = 1,false = 0))
data = data %>% mutate("3-23 reads" = if_else(condition = HPV33.reads >=3 &HPV33.reads  <24,true = 1,false = 0))
data = data %>% mutate("24+ reads" = if_else(condition = HPV33.reads >=24,true = 1,false = 0))
data = colSums(data[,2:ncol(data)]) %>% as.data.frame()
names(data)[1] = "count"
data = rownames_to_column(data,var = "bin")
data
ggplot(data=data, aes(x=factor(bin,levels = c("0 reads","1 reads","2 reads","3-23 reads","24+ reads")), y=count)) +
  geom_bar(stat="identity", fill="steelblue") + xlab("HPV Reads")+ theme_minimal()+
  geom_text(aes(label=count), vjust=-0.5, color="black", size=3.5)
```

# MYB comparision
```{r}
hpv33_positive = HPV33 %>% dplyr::mutate(hpv33_positive = case_when(reads >= 10 ~ "positive",
                                                                    reads < 10 ~ "negative")
)



hpv33_positive$reads = NULL
hmsc_cancer_cells = AddMetaData(object = hmsc_cancer_cells,metadata = hpv33_positive)
```

```{r fig.height=6, fig.width=12}
DimPlot(object = hmsc_cancer_cells,group.by  = c("hpv33_positive"),pt.size = 2)+
FeaturePlot(object = hmsc_cancer_cells,features = "MYB",pt.size = 2)

```

```{r}
FeaturePlot(object = hmsc_cancer_cells,features = "JAG1",pt.size = 2)

```


# Fisher test
```{r}
DefaultAssay(hmsc_cancer_cells) = "RNA" # calculate MYB positive/negtive from original data
# set MYB pos/neg
hmsc_cancer_cells$MYB_status = FetchData(object = hmsc_cancer_cells,vars = "MYB") %>%
  mutate(MYB_status = if_else(
    condition = MYB > 0,
    true = "MYB_positive",
    false = "MYB_negative"
  )) %>% 
  pull(MYB_status)

DefaultAssay(hmsc_cancer_cells) = "integrated"

```

```{r }
# plot
library(rstatix)

df  = FetchData(object = hmsc_cancer_cells,
                vars = c("MYB_status", "hpv33_positive"))  %>%
  droplevels()
test = fisher_test(table(df))
p = ggbarstats(
  df,
  MYB_status,
  hpv33_positive,
  results.subtitle = FALSE,
  subtitle = paste0("Fisher's exact test", ", p-value = ",
                    test$p)
)

p
```
# MYB targets

```{r}
# load MYB targets
library("readxl")
myb_tergets <- read_excel(input$myb_targets,col_names = T) %>% 
  pull(Gene)
```

```{r}

# add score
myb_tergets_score = FetchData(object = hmsc_cancer_cells,vars = myb_tergets,slot = "data") %>% rowMeans()
myb_tergets_df = data.frame(myb_tergets_score,row.names = names(myb_tergets_score))
hmsc_cancer_cells = AddMetaData(object = hmsc_cancer_cells,metadata = myb_tergets_df)

```


```{r}

genes_by_tp = FetchData(object = hmsc_cancer_cells,vars = c("hpv33_positive", "myb_tergets_score"),slot = "data") 

# all cells by patient boxplot
formula <- as.formula("myb_tergets_score ~ hpv33_positive")

#plot and split by patient:
stat.test <- genes_by_tp %>%
  t_test(formula) %>%
  adjust_pvalue(method = "fdr") %>%
  add_significance() %>%
  add_xy_position(x = "hpv33_positive") %>%
  mutate(p.adj = signif(p.adj, digits = 2))
stat.test


plt = ggplot(genes_by_tp, aes(x = hpv33_positive, y = myb_tergets_score)) +
  geom_violin(scale = "width",aes(fill = hpv33_positive)) +
  geom_boxplot(width = 0.2, outlier.shape = NA) +
  stat_pvalue_manual(stat.test, label = "{p.adj}")  + #add p value
  scale_y_continuous(expand = expansion(mult = c(0.05, 0.2))) + # Add 10% spaces between the p-value labels and the plot border
  geom_jitter()+
  labs(title = "Downstream MYB targets within HMSC", y = "MYB target score", fill = "HPV Status")+
  theme(plot.title = element_text(hjust = 0.5),axis.title.x = element_blank())
plt
```

```{r}
pdf(paste0(params$data_out_dir,"HMSC_HPVon_HPVoff_myb_targets.pdf"))
plt
dev.off()
```

# DEG LR latent vars plate


```{r}
DefaultAssay(hmsc_cancer_cells) = "integrated"
hmsc_cancer_cells = SetIdent(hmsc_cancer_cells,value = "hpv33_positive")
```



```{r echo = T, results = 'hide'}

hmsc_cancer_cells = FindVariableFeatures(hmsc_cancer_cells,nfeatures = 15000)
var_features = VariableFeatures(hmsc_cancer_cells)
top_expressed_features = hmsc_cancer_cells@assays$RNA@data %>% rowMeans() %>% sort(decreasing = T) %>% head(3000) %>% names()
features = intersect(var_features, top_expressed_features)


hmsc_deg <-
  FindMarkers(
    hmsc_cancer_cells,
    ident.1 = "positive",
    ident.2 = "negative",
    features = features,
    densify = T,
    assay = "RNA",
    test.use = "LR",
    latent.vars = "plate",
    logfc.threshold = 0.1,
    min.pct = 0,
    mean.fxn = function(x) {
      return(log2(rowMeans(x)+1)) # change func to calculate logFC in log space data (default to exponent data)
    }
  )
hmsc_deg$fdr<-p.adjust(p = as.vector(hmsc_deg$p_val) ,method = "fdr")
paged_table(hmsc_deg[c("MYB","JAG1","MYC"),])



```


```{r}
write.csv(x  = hmsc_deg,file = paste0(params$data_out_dir,basename(output$hmsc_deg)),row.names = T)
```


```{r}
# create 6 breaks between plot limits in log scale and then exponent, otherwise breaks not good
breaks_fun = function(limits){ 
  breaks = exp(-seq(-log(limits[1]), -log(limits[2]), length.out = 6))
  breaks[1] = breaks[1] * 0.95 #adjust extreme ticks to prevent truncation
  breaks[7] = breaks[7] * 1.05
  return(signif(breaks, digits = 2))
}

hmsc_deg$score = hmsc_deg$avg_log2FC*-log10(hmsc_deg$fdr)
ranked_vec = hmsc_deg[,"avg_log2FC"]%>% setNames(rownames(hmsc_deg)) %>% na.omit() # make named vector

genesets =geneIds(genesets_h)
hyp_obj <-hypeR_fgsea(signature = ranked_vec,genesets = genesets,up_only = F)
p = hyp_dots(hyp_obj,merge = F) 


p1 = p[[1]]+
  scale_y_continuous(trans = hypeR:::.reverselog_trans(10), 
        breaks =breaks_fun)

p2 = p[[2]]+
  scale_y_continuous(trans = hypeR:::.reverselog_trans(10), 
        breaks =breaks_fun)
p1
p2
```


```{r}
pdf(paste0(params$data_out_dir,"HMSC_HPVon_HPVoff_GSEA.pdf"))
p1
dev.off()
```








volcano plot log2(mean logTPM HPV+/mean logTPM HPV-)
```{r}
plt = volcano_plot(
  de_genes = hmsc_deg,
  fc_cutoff = volcano_fc,
  fdr_cutoff =volcano_fdr,
  ident1 = "HPV33 positive",
  ident2 = "HPV33 negative",
  top_genes_text = 10,show_gene_names = c("MYB","JAG1","MYC")
) + ggtitle("Differential Gene Expression by HPV Status
")
plt
```




```{r}
pdf(paste0(params$data_out_dir,"HMSC_HPVon_HPVoff_volcano.pdf"))
plt
dev.off()


```





## Cycling cells filtering {.tabset}

```{r}
hallmark_name = "GO_MITOTIC_CELL_CYCLE"
hmsc_cancer_cells = FindVariableFeatures(object = hmsc_cancer_cells,nfeatures = 15000,assay = "RNA")
hmsc_cancer_cells = ScaleData(object = hmsc_cancer_cells,features = VariableFeatures(hmsc_cancer_cells,assay = "RNA"))
geneIds= genesets_h[[hallmark_name]]@geneIds %>% intersect(VariableFeatures(hmsc_cancer_cells,assay = "RNA")) 
score <- apply(hmsc_cancer_cells@assays$integrated@scale.data[geneIds,],2,mean)
hmsc_cancer_cells=AddMetaData(hmsc_cancer_cells,score,hallmark_name)
```

```{r echo=TRUE, results='asis'}
hmsc_cc_scores = FetchData(object = hmsc_cancer_cells,vars = "GO_MITOTIC_CELL_CYCLE")

distributions_plt = ggplot() +
  geom_density(aes(GO_MITOTIC_CELL_CYCLE, fill = "HMSC"), alpha = .2, data = hmsc_cc_scores) +
  scale_fill_manual(name = "Dataset", values = c(ACC = "red", HMSC = "green"))+ geom_vline(aes(xintercept=0.3),
            color="blue", linetype="dashed", size=1) +ggtitle("'GO_MITOTIC_CELL_CYCLE'  score distribution")

print_tab(plt = distributions_plt,title = "score distribution",subtitle_num = 3)

```

```{r warning=FALSE}


#filter:
hmsc_cancer_cells_ccFiltered=hmsc_cancer_cells[,hmsc_cancer_cells@meta.data[[hallmark_name]]< 0.3]


```


```{r}
DefaultAssay(hmsc_cancer_cells_ccFiltered) = "integrated"
hmsc_cancer_cells_ccFiltered = SetIdent(hmsc_cancer_cells_ccFiltered,value = "hpv33_positive")
```



```{r echo = T, results = 'hide'}
hmsc_cancer_cells_ccFiltered = FindVariableFeatures(hmsc_cancer_cells_ccFiltered,nfeatures = 15000)
var_features = VariableFeatures(hmsc_cancer_cells_ccFiltered)
top_expressed_features = hmsc_cancer_cells_ccFiltered@assays$RNA@data %>% rowMeans() %>% sort(decreasing = T) %>% head(3000) %>% names()
features = intersect(var_features, top_expressed_features)

#3K genes

# top_expressed_features = hmsc_cancer_cells_ccFiltered@assays$RNA@data %>% rowMeans() %>% sort(decreasing = T) %>% head(3000) %>% names()
# features = top_expressed_features

hmsc_deg <-
  FindMarkers(
    hmsc_cancer_cells_ccFiltered,
    ident.1 = "positive",
    ident.2 = "negative",
    features = features,
    densify = T,
    assay = "RNA",
    test.use = "LR",
    latent.vars = "plate",
    logfc.threshold = 0.1,
    min.pct = 0.1,
    mean.fxn = function(x) {
      return(log2(rowMeans(x)+1)) # change func to calculate logFC in log space data (default to exponent data)
    }
  )
hmsc_deg$fdr<-p.adjust(p = as.vector(hmsc_deg$p_val) ,method = "fdr")



```



```{r}
hmsc_deg$score = hmsc_deg$avg_log2FC*-log10(hmsc_deg$fdr)
ranked_vec = hmsc_deg[,"avg_log2FC"]%>% setNames(rownames(hmsc_deg)) %>% na.omit() # make named vector

genesets =geneIds(genesets_h)
hyp_obj <-hypeR_fgsea(signature = ranked_vec,genesets = genesets,up_only = F)
p = hyp_dots(hyp_obj,merge = F)
p1 = p[[1]]+
  scale_y_continuous(trans = hypeR:::.reverselog_trans(10), 
        breaks =breaks_fun)
p2 = p[[2]]+
  scale_y_continuous(trans = hypeR:::.reverselog_trans(10), 
        breaks =breaks_fun)
p1
p2
```

```{r}
pdf(paste0(params$data_out_dir,"HMSC_HPVon_HPVoff_GSEA_noG2M_cells.pdf"))
p1
dev.off()


```

# HPV vs genes
```{r fig.width=8}
top_genes = hmsc_deg %>% filter(.$avg_log2FC>0) %>% arrange(.$fdr) %>% head(5) %>% rownames()
top_genes = c(top_genes,c("MYB","JAG1"))

myb_vs_hpv = FetchData(object = hmsc_cancer_cells,vars = c("hpv33_positive",top_genes))
df = reshape2::melt(myb_vs_hpv,value.name = "Expression") %>% dplyr::rename(gene = variable)

library(rstatix)
stat.test <- df %>%
    group_by(gene) %>%
  wilcox_test(Expression ~ hpv33_positive) %>%
  mutate(y.position = 5)

stat.test

stat.test <- stat.test %>% 
  add_xy_position(x = "gene", dodge = 0.8)

ggboxplot(
  df,
  x = "gene",
  y = "Expression",
  color = "hpv33_positive",
  palette = "jco",
  add = "jitter"
)+ stat_pvalue_manual(stat.test,y.position = 13, label = "p = {p}",remove.bracket = T)
```
# OPSCC signature

```{r}
avg_log2FC_cutoff = log2(signature_fc)
fdr_cutoff = signature_fdr


opscc_deg = read.table(file =  input$opscc_deg,row.names = 1,sep = ",",header = T)

opscc_signature = opscc_deg %>% filter(avg_log2FC > avg_log2FC_cutoff &
                                  fdr < fdr_cutoff) %>% rownames()
opscc_signature
```

```{r}

# add score
opscc_hpv_score = FetchData(object = hmsc_cancer_cells,vars = opscc_signature,slot = "data") %>% rowMeans()
hpv_signature = data.frame(opscc_hpv_score,row.names = names(opscc_hpv_score))
hmsc_cancer_cells = AddMetaData(object = hmsc_cancer_cells,metadata = hpv_signature)

```




```{r}

genes_by_tp = FetchData(object = hmsc_cancer_cells,vars = c("hpv33_positive", "opscc_hpv_score"),slot = "data") 

# all cells by patient boxplot
formula <- as.formula("opscc_hpv_score  ~ hpv33_positive")

#plot and split by patient:
stat.test <- genes_by_tp %>%
  t_test(formula) %>%
  adjust_pvalue(method = "fdr") %>%
  add_significance() %>%
  add_xy_position(x = "hpv33_positive") %>%
  mutate(p.adj = signif(p.adj, digits = 2))
stat.test


plt = ggplot(genes_by_tp, aes(x = hpv33_positive, y = opscc_hpv_score )) +
  geom_violin(scale = "width",aes(fill = hpv33_positive)) +
  geom_boxplot(width = 0.2, outlier.shape = NA) +
  stat_pvalue_manual(stat.test, label = "{p.adj}")  + #add p value
  scale_y_continuous(expand = expansion(mult = c(0.05, 0.2))) + # Add 10% spaces between the p-value labels and the plot border
  geom_jitter()+
  ggtitle("opscc_hpv_score ")+
  scale_fill_manual(values = c("positive" = "#1B9E77FF", "negative" = "#D95F02FF"),
                    labels = c("positive" = "HPV+","negative" ="HPV-"))
plt
```


# NOTCH genes
##JAG1
```{r}
data=FetchData(object =hmsc_cancer_cells,vars =  c("JAG1","hpv33_positive")) 
ggboxplot(data, x = "hpv33_positive", y = "JAG1",add = "jitter",fill = "hpv33_positive") + 
  stat_compare_means(method = "wilcox.test",comparisons =  list( c("negative", "positive")))    +
  stat_summary(fun.data = function(x) data.frame(y=10, label = paste("Mean=",round(mean(x),digits = 2))), geom="text") +
  scale_x_discrete(limits = c("negative","positive"))

```
## notch_targets
```{r}
notch_targets = c("NRARP", "NOTCH3", "HES4", "HEY1",  "HEY2" )
notch_targets_score = hmsc_cancer_cells %>% FetchData(vars = notch_targets) %>% rowMeans()

data = data.frame(notch_targets = notch_targets_score,hpv33_positive = hmsc_cancer_cells$hpv33_positive)

ggboxplot(data, x = "hpv33_positive", y = "notch_targets",add = "jitter",fill = "hpv33_positive") + 
  stat_compare_means(method = "wilcox.test",comparisons =  list( c("negative", "positive")))    +
  stat_summary(fun.data = function(x) data.frame(y=5, label = paste("Mean=",round(mean(x),digits = 2))), geom="text")  +
  scale_x_discrete(limits = c("negative","positive"))

```
# notch ligands
```{r}
notch_ligands = c("JAG1","JAG2","DLL1")
notch_ligands_score = hmsc_cancer_cells %>% FetchData(vars = notch_ligands) %>% rowMeans()

data = data.frame(notch_ligands = notch_ligands_score,hpv33_positive = hmsc_cancer_cells$hpv33_positive)

ggboxplot(data, x = "hpv33_positive", y = "notch_ligands",add = "jitter",fill = "hpv33_positive") + 
  stat_compare_means(method = "wilcox.test",comparisons =  list( c("negative", "positive")))    +
  stat_summary(fun.data = function(x) data.frame(y=5, label = paste("Mean=",round(mean(x),digits = 2))), geom="text")  +
  scale_x_discrete(limits = c("negative","positive"))

```
