---
title: "R Notebook"
output: 
  html_notebook: 
    code_folding: hide
---

# All cancer cells UMAP

```{r echo=TRUE, fig.height=8, fig.width=10, warning=FALSE}
library(Seurat)
library(dplyr)
acc_all_cells = readRDS("../Data/acc_tpm_nCount_mito_no146_15k_alldata_with_ACC1.rds")
DimPlot(acc_all_cells, reduction = "umap", label = TRUE, pt.size = 1,group.by = "patient.ident") 

```


```{r}
acchigh=read.delim("../data/oncotarget-05-12528-s001_acchigh.txt",skip=0,header=F,sep="\t",stringsAsFactors=F)
acchigh_s=apply(acc_all_cells@assays$RNA@scale.data[intersect(acchigh$V1,acc_all_cells@assays$RNA@var.features),],2,mean)
acchigh_s[acchigh_s < -0.5] = -0.5
acchigh_s[acchigh_s > 0.5] = 0.5
acc_all_cells=AddMetaData(acc_all_cells,acchigh_s,"kaye_acc_score")
```

# CAF markers

```{r fig.width=15}
FeaturePlot(acc_all_cells, c("COL3A1","COL1A2") ,cols = c("blue","yellow"))
```

# Endothelian markers

```{r fig.width=15}
FeaturePlot(acc_all_cells, c("VWF","PECAM1") ,cols = c("blue","yellow"))

```

# WBC markers

```{r fig.width=15}
FeaturePlot(acc_all_cells, c("CD79A","PTPRC") ,cols = c("blue","yellow"))

```

# ACC markers

```{r fig.width=15}
FeaturePlot(acc_all_cells, c("kaye_acc_score","MYB") ,cols = c("blue","yellow"))

```

# 3.Cell types in ACC1

```{r warning=FALSE}
new.cluster.ids <- c("CAF",
                     "ACC",
                     "ACC",
                     "ACC",
                     "ACC",
                     "ACC",
                     "ENDOTHELIAN",
                     "CAF",
                     "CAF",
                     "CAF",
                     "ACC",
                     "ACC",
                     "ACC")
names(new.cluster.ids) <- levels(acc_all_cells)
acc_all_cells = SetIdent(object = acc_all_cells,value = "seurat_clusters")
acc_all_cells <- RenameIdents(acc_all_cells, new.cluster.ids)
plot1 = DimPlot(acc_all_cells, reduction = "umap", label = TRUE, pt.size = 0.5) 
HoverLocator(plot = plot1, information = FetchData(acc_all_cells, vars = c("patient.ident")))

```



```{r}
library(ggplot2)
cell.type <- acc_all_cells@meta.data$seurat_clusters
levels(cell.type) <- new.cluster.ids
acc_all_cells <- AddMetaData(object = acc_all_cells, metadata = as.factor(cell.type), col.name = "cell.type")

acc1_all_cells = subset(x = acc_all_cells,subset = patient.ident == "ACC1")
acc1_types = acc1_all_cells@meta.data[["cell.type"]] %>% table() %>% as.data.frame()
names(acc1_types)[1] = "type"
ggplot(data=acc1_types, aes(x=type, y=Freq)) +
  geom_bar(stat="identity", fill="steelblue")+
  geom_text(aes(label=Freq), vjust=-0.5, color="black", size=3.5)
```

# 3. UMAP of luminal_over_myo

only cancer cells:

```{r}
# acc_cancer_cells = subset(x = acc_all_cells,subset = cell.type == "ACC")
# acc_cancer_cells <- FindVariableFeatures(acc_cancer_cells, selection.method = "vst", nfeatures = 15000)
# acc_cancer_cells <- ScaleData(acc_cancer_cells, vars.to.regress = c("percent.mt","nCount_RNA"))
# acc_cancer_cells <- RunPCA(acc_cancer_cells, features = VariableFeatures(object = acc_cancer_cells))
# acc_cancer_cells <- FindNeighbors(acc_cancer_cells, dims = 1:10)
# acc_cancer_cells <- FindClusters(acc_cancer_cells, resolution = 1)
# acc_cancer_cells <- RunUMAP(acc_cancer_cells, dims = 1:10)
# saveRDS(object = acc_cancer_cells,file = "../Data/acc_cancer_cells.RDS")

acc_cancer_cells = readRDS("../Data/acc_cancer_cells.RDS")

DimPlot(object = acc_cancer_cells, reduction = "umap", pt.size = 1, label = F,group.by = "patient.ident")

myoscore=apply(acc_cancer_cells@assays[["RNA"]][c("TP63","TP73","CDH3","KRT14","KRT5","ACTA2","CDH11","TAGLN","MYLK","DKK3","SPARC","TRIM29"),],2,mean)
lescore=apply(acc_cancer_cells@assays[["RNA"]][c("KIT","CLDN3","ANXA8","EHF","ELF5","KRT7","CLDN4","LCN2","LGALS3","WFDC2","ATP1B1","CD24"),],2,mean)
acc_cancer_cells=AddMetaData(acc_cancer_cells,lescore-myoscore,"luminal_over_myo")
FeaturePlot(object = acc_cancer_cells,features = "luminal_over_myo")
```

You may also use this plot:

```{r}
lum_or_myo = FetchData(object = acc_cancer_cells,vars = "luminal_over_myo")
lum_or_myo$luminal_over_myo[lum_or_myo$luminal_over_myo>=1] = "Lum"
lum_or_myo$luminal_over_myo[lum_or_myo$luminal_over_myo<= (-1)] = "Myo"
lum_or_myo$luminal_over_myo[lum_or_myo$luminal_over_myo> (-1) & lum_or_myo$luminal_over_myo<1] = "unassigned"
acc_cancer_cells <- AddMetaData(object = acc_cancer_cells, metadata = lum_or_myo, col.name = "lum_or_myo")

lum_or_myo_by_patient = FetchData(object = acc_cancer_cells,vars = c("lum_or_myo","patient.ident"))


lum_or_myo_by_patient %>% 
  dplyr::count(patient.ident, lum_or_myo) %>% 
  dplyr::add_count(patient.ident, wt = n, name = "overall") %>% 
  mutate(proportion = n / overall) 

```

```{r}
lum_or_myo_by_patient = lum_or_myo_by_patient %>% 
  dplyr::count(patient.ident, lum_or_myo) %>% 
  dplyr::add_count(patient.ident, wt = n, name = "overall") %>% 
  mutate(proportion = n / overall) %>% filter(lum_or_myo == "Myo")

ggplot(data=lum_or_myo_by_patient, aes(x=patient.ident, y=proportion)) +
  geom_bar(stat="identity", fill="steelblue")+
  theme_minimal() +ylab("Myo cells %")

```

# 4. UMAPS

```{r fig.height=15, fig.width=10}
myoscore=apply(acc_cancer_cells@assays[["RNA"]][c("TP63","TP73","CDH3","KRT14","KRT5","ACTA2","CDH11","TAGLN","MYLK","DKK3","SPARC","TRIM29"),],2,mean)
lescore=apply(acc_cancer_cells@assays[["RNA"]][c("KIT","CLDN3","ANXA8","EHF","ELF5","KRT7","CLDN4","LCN2","LGALS3","WFDC2","ATP1B1","CD24"),],2,mean)
acc_cancer_cells=AddMetaData(acc_cancer_cells,myoscore,"myo_score")
acc_cancer_cells=AddMetaData(acc_cancer_cells,lescore,"lum_core")
FeaturePlot(object = acc_cancer_cells,features = c("IL12B","TP63", "CNN1", "ACTA2","myo_score","lum_core"  ))
```

```{r}
# acc1_cancer_cells = subset(x = acc_cancer_cells,subset = patient.ident == "ACC1")
# acc1_cancer_cells <- FindVariableFeatures(acc1_cancer_cells, selection.method = "vst", nfeatures = 15000)
# acc1_cancer_cells <- ScaleData(acc1_cancer_cells, vars.to.regress = c("percent.mt","nCount_RNA"))
# acc1_cancer_cells <- RunPCA(acc1_cancer_cells, features = VariableFeatures(object = acc_cancer_cells))
# acc1_cancer_cells <- FindNeighbors(acc1_cancer_cells, dims = 1:10)
# acc1_cancer_cells <- FindClusters(acc1_cancer_cells, resolution = 1)
# acc1_cancer_cells <- RunUMAP(acc1_cancer_cells, dims = 1:10)
# saveRDS(object = acc1_cancer_cells,file = "../Data/acc1_cancer_cells.RDS")
acc1_cancer_cells = readRDS(file = "../Data/acc1_cancer_cells.RDS")
DimPlot(object = acc1_cancer_cells,reduction = "umap")

```

# 6. HPV+ cells UMAP

Only HMSC cancer cells:

```{r}
library(data.table)
HPV33_P3 = fread("../Data/HPV33_P3.txt",col.names = c("plate","reads")) %>% as.data.frame()
HPV33_P3.df = HPV33_P3 %>% mutate(
  plate = gsub(x =HPV33_P3$plate, replacement = "",pattern = "_.*$") 
  %>% gsub(pattern = "-P",replacement = ".P") 
  %>% gsub(pattern = "-",replacement = "_",)
  )



HPV33_P3.df = HPV33_P3.df %>% filter(HPV33_P3.df$plate %in% colnames(acc1_cancer_cells))
rownames(HPV33_P3.df)  <- HPV33_P3.df$plate
 HPV33_P3.df$plate = NULL
acc1_cancer_cells = AddMetaData(object = acc1_cancer_cells,metadata = HPV33_P3.df,col.name = "HPV33.reads")
FeaturePlot(acc1_cancer_cells,features = "HPV33.reads",max.cutoff = 40)
```

# CNV

```{r fig.width=10}
library(infercnv)
library(tidyverse)
acc_annotation  = as.data.frame(acc_all_cells@meta.data[,"seurat_clusters",drop = F])
acc_annotation = acc_annotation %>% rownames_to_column("orig.ident") 
acc_annotation = acc_annotation %>% mutate(orig.ident = gsub(x = acc_annotation$orig.ident,pattern = "\\.", replacement = "-") %>% 
  gsub(pattern = "_", replacement = "-"))
  


write.table(acc_annotation, "../Data/CNV/acc_annotation.txt", append = FALSE, 
            sep = "\t", dec = ".",row.names = FALSE, col.names = F)

infercnv_obj = CreateInfercnvObject(raw_counts_matrix="../Data/CNV/all.4icnv.txt", 
                                    annotations_file="../Data/CNV/acc_annotation.txt",
                                    delim="\t",gene_order_file="../Data/CNV/gencode_v19_gene_pos.txt"
                                    ,ref_group_names=c("0", "6", "7", "8", "9")) #groups of normal cells

infercnv_obj_default = infercnv::run(infercnv_obj, cutoff=1, out_dir='../Data/CNV/infercnv_output',
                                     cluster_by_groups=TRUE, plot_steps=FALSE,
                                     denoise=TRUE, HMM=FALSE, no_prelim_plot=TRUE,
                                     png_res=300,)
plot_cnv(infercnv_obj_default, output_format = "png",  write_expr_matrix = FALSE,out_dir = "../Data/CNV/",png_res	=800)

# saveRDS(object = infercnv_obj, file = "../Data/CNV/infercnv_obj.rds")
# saveRDS(object = infercnv_obj_default, file = "../Data/CNV/infercnv_obj_default.rds")

cluster.info=FetchData(acc_all_cells,c("ident","orig.ident","UMAP_1","UMAP_2","nCount_RNA","nFeature_RNA","percent.mt","patient.ident","seurat_clusters"))
cluster.info$cell=rownames(cluster.info)
write.table(cluster.info,"../Data/CNV/acc_UMAP_clusters2.txt",sep="\t",row.names=FALSE)

library(limma)
smoothed=apply(infercnv_obj_default@expr.data,2,tricubeMovingAverage, span=0.01)
cnsig=sqrt(apply((smoothed-1)^2,2,mean))
umap=read.table("../Data/CNV/acc_UMAP_clusters2.txt",header = TRUE)
names(cnsig)=umap$cell

# cnsig[cnsig>0.08]=0.08
acc_all_cells <- AddMetaData(object = acc_all_cells, metadata = cnsig, col.name = "copynumber")
cnv_plot <-FeaturePlot(acc_all_cells, "copynumber",pt.size = 1, cols = c("blue","yellow"))
cnv_plot
```

```{r warning=FALSE}
HoverLocator(plot = cnv_plot, information = FetchData(acc_all_cells, vars = c("orig.ident", "copynumber")))

```
CNV for ACC1:
```{r}
acc1_annotation  = as.data.frame(acc1_all_cells@meta.data[,"seurat_clusters",drop = F])
acc1_annotation = acc1_annotation %>% rownames_to_column("orig.ident") 
acc1_annotation = acc1_annotation %>% mutate(orig.ident = gsub(x = acc1_annotation$orig.ident,pattern = "\\.", replacement = "-") %>% 
  gsub(pattern = "_", replacement = "-"))
  


write.table(acc1_annotation, "../Data/CNV/acc1_annotation.txt", append = FALSE, 
            sep = "\t", dec = ".",row.names = FALSE, col.names = F)

infercnv_obj = CreateInfercnvObject(raw_counts_matrix="../Data/CNV/all.4icnv.txt", 
                                    annotations_file="../Data/CNV/acc1_annotation.txt",
                                    delim="\t",gene_order_file="../Data/CNV/gencode_v19_gene_pos.txt"
                                    ,ref_group_names=c("0", "6", "7", "8", "9")) #groups of normal cells
```

```{r}
DimPlot(object = acc1_all_cells,reduction = "umap",label = T)
```
```{r}
plot = FeaturePlot(acc1_all_cells, c("VWF") ,cols = c("blue","yellow"))
HoverLocator(plot = plot, information = FetchData(acc_all_cells, vars = c("VWF", "PECAM1","cell.type")))

plot = FeaturePlot(acc1_all_cells, c("PECAM1") ,cols = c("blue","yellow"))
HoverLocator(plot = plot, information = FetchData(acc_all_cells, vars = c("VWF", "PECAM1","cell.type")))
```

```{r}
plot = FeaturePlot(acc1_all_cells, c("COL3A1") ,cols = c("blue","yellow"))
HoverLocator(plot = plot, information = FetchData(acc1_all_cells, vars = c("COL3A1", "COL1A2","cell.type")))

plot = FeaturePlot(acc1_all_cells, c("COL1A2") ,cols = c("blue","yellow"))
HoverLocator(plot = plot, information = FetchData(acc1_all_cells, vars = c("COL3A1", "COL1A2","cell.type")))
```

```{r}
acc_all_cells = SetIdent(object = acc_all_cells,value = "patient.ident")
selected_group <- WhichCells(acc_all_cells, idents = "ACC1")

DimPlot(object = acc_all_cells, reduction = "umap", pt.size = 1,cells.highlight= selected_group,
        group.by = "patient.ident", label = TRUE) +
  scale_color_manual(labels = c("unselected", "ACC1"), values = c("grey", "red"))



```

```{r}
acc_all_cells = SetIdent(object = acc_all_cells,value = "patient.ident")
selected_group <- WhichCells(acc_all_cells, idents = "ACC1")

acc1_plot = DimPlot(object = acc_all_cells, reduction = "umap", pt.size = 1,cells.highlight= selected_group,
        group.by = "patient.ident", label = TRUE) +
  scale_color_manual(labels = c("unselected", "ACC1"), values = c("grey", "red"))

HoverLocator(plot = acc1_plot, information = FetchData(acc1_all_cells, vars = c("cell.type")))

```
```{r fig.height=8, fig.width=10}
library(pheatmap)
acc1_all_cells.df = acc1_all_cells@assays[["RNA"]]@data %>% as.data.frame()
acc1_cor = cor(acc1_all_cells.df)
annotation = FetchData(object = acc1_all_cells,vars = c("cell.type"))
pheatmap(acc1_cor,annotation_row = annotation,fontsize = 6)
```

```{r fig.height=12, fig.width=12}
FeaturePlot(object = acc1_cancer_cells,features = c("KIT","CLDN3","ANXA8","EHF","ELF5","KRT7","CLDN4","LCN2","LGALS3","WFDC2","ATP1B1","CD24"))
```
```{r fig.height=12, fig.width=12}
FeaturePlot(object = acc1_cancer_cells,features = c("KIT","CLDN3","ANXA8","EHF","ELF5","KRT7","CLDN4","LCN2","LGALS3","WFDC2","ATP1B1","CD24")
            ,slot = "scale.data")
```

```{r fig.height=12, fig.width=12}
FeaturePlot(object = acc1_cancer_cells,features = c("TP63","TP73","CDH3","KRT14","KRT5","ACTA2","CDH11","TAGLN","MYLK","DKK3","SPARC","TRIM29"))
```
```{r fig.height=12, fig.width=12}
FeaturePlot(object = acc1_cancer_cells,features = c("TP63","TP73","CDH3","KRT14","KRT5","ACTA2","CDH11","TAGLN","MYLK","DKK3","SPARC","TRIM29")
            ,slot = "scale.data")
```

correlation of lum/myp markers
```{r}
lum_markers  = FetchData(object = acc1_cancer_cells, vars = 
                 c("KIT","CLDN3","ANXA8","EHF","ELF5","KRT7","CLDN4","LCN2","LGALS3","WFDC2","ATP1B1","CD24"))
lum_cor = cor(lum_markers)
pheatmap(lum_cor)

```

```{r}
myo_markers  = FetchData(object = acc1_cancer_cells, vars = 
                 c("TP63","TP73","CDH3","KRT14","KRT5","ACTA2","CDH11","TAGLN","MYLK","DKK3","SPARC","TRIM29"))
myo_cor = cor(myo_markers)
pheatmap(myo_cor)

```

```{r}
myo_proteins = FetchData(object = acc1_cancer_cells,vars = c("CNN1"))
myo_proteins_cor = cor(myo_markers,myo_proteins)
pheatmap(myo_proteins_cor,cluster_cols = F, cluster_rows = F,display_numbers = T)
```
```{r}
a = colnames(acc_all_cells) %>% as.data.frame()
```

