---
title: "Create_data_V1"
date: 5.12.22
output: 
  html_notebook: 
    code_folding: hide
---
libraries
```{r}
library("ggplot2")
library("plyr")
library("Seurat")
library("SingleCellSignalR")
```

## Parameters:

```{r}
suffix = ""
tpm_as_counts = F #default: F
```

* suffix = `r suffix`
* tpm_as_counts = `r tpm_as_counts`

read data
```{r}
acc.data <- read.delim("/sci/labs/yotamd/lab_share/ACC/ACC_sc/fc/all.txt",skip=0,header=T, 
                       sep="\t",stringsAsFactors=F,row.names=1)
""
```

pre process
```{r}
tpm <- function(counts, lengths) {
  rpk <- counts / lengths
  coef <- sum(rpk) / 1e6
  rpk/coef
}

rownames(acc.data)=make.unique(acc.data$gene_name)
lengths = acc.data[,5]
omitgenes= startsWith(rownames(acc.data),"ERCC-")
acc.data=acc.data[!omitgenes,]
acc.data=acc.data[,7:ncol(acc.data)]


cell.labels <- gsub(".gene_counts.tsv","",colnames(acc.data))
cell.labels <- gsub(".sort.bam","",cell.labels)
cell.labels <- gsub("_",".",cell.labels)
cell.labels <- gsub(".S[0-9]*","",cell.labels)
well=regmatches(cell.labels, regexpr("[A-H][0-9]*$", cell.labels))
plate=substr(cell.labels,1,nchar(cell.labels)-nchar(well)-1)

colnames(acc.data)=paste(plate,well,sep="_")

clus_res=1
subgroup=!(startsWith(colnames(acc.data),"ACC4.")|startsWith(colnames(acc.data),"ACC6."))
acc.data = acc.data[,subgroup]

acc.tpm=apply(acc.data, 2, function(x) tpm(x, lengths[!omitgenes]))

```

Create Seurat
```{r}
acc.count_seurat <- CreateSeuratObject(counts = acc.data, project = "acc", min.cells = 3, min.features = 2000)
acc.tpm_seurat <- CreateSeuratObject(counts = log2(acc.tpm+1), project = "acc", min.cells = 3, min.features = 2000)
if (tpm_as_counts == T){
  acc.tpm_seurat_not_log <- CreateSeuratObject(counts = acc.tpm, project = "acc", min.cells = 3, min.features = 2000)
}
```

## MT precent
```{r fig.height=8}
percent.mt <- PercentageFeatureSet(acc.count_seurat, pattern = "^MT-")
acc.tpm_seurat[["percent.mt"]] <- percent.mt

mt_genes=(startsWith(rownames(acc.tpm_seurat),"MT-"))
acc.tpm_seurat = acc.tpm_seurat[!mt_genes,]

data = as.data.frame(acc.tpm_seurat@meta.data[["nCount_RNA"]])
data$MT = acc.tpm_seurat@meta.data[["percent.mt"]]
names(data)[1] <- "total nCount_RNA"
names(data)[2] <- "MT%"


plot(data,pch=19,main = "acc.tpm")
```

```{r}
if (tpm_as_counts == T){
  acc.tpm_seurat@assays$RNA@counts = GetAssayData(object = acc.tpm_seurat_not_log,slot = "counts") #keep acc tpm under "counts" slot
}
```

## Dim reduction
```{r results='hide'}
acc <- subset(acc.tpm_seurat, subset = nFeature_RNA > 2000 & percent.mt < 40)
# Identification of highly variable features
acc <- FindVariableFeatures(acc, selection.method = "vst", nfeatures = 15000) 

# Scaling the data
acc <- ScaleData(acc, vars.to.regress = c("percent.mt","nCount_RNA"))

# Perform linear dimensional reduction (PCA)
acc <- RunPCA(acc, features = VariableFeatures(object = acc))

ElbowPlot(acc, ndims = 50) # checking the dimensionality 

```
## UMAP
```{r}
pc2use=1:30;
```

chosen PC = `r max(pc2use)`

```{r fig.width=8, results='hide',class.source = "fold-show"}
# cluster the cells
acc <- FindNeighbors(acc, dims = pc2use)
acc <- FindClusters(acc, resolution = clus_res)

# Run non-linear dimensional reduction (UMAP)
acc <- RunUMAP(acc, dims = pc2use)
DimPlot(object = acc, reduction = "umap", pt.size = 1, label = F)

patient.ident <- gsub(replacement =  "ACC1",pattern ="ACC.plate2", acc@meta.data$orig.ident)
patient.ident <- gsub("[[:punct:]]\\w*$","", patient.ident)
patient.ident <- gsub("[[:punct:]]\\w*$","", patient.ident)

levels(as.factor(patient.ident))
acc <- AddMetaData(object = acc, metadata = as.factor(patient.ident), col.name = "patient.ident")

DimPlot(acc, reduction = "umap", label = TRUE, pt.size = 1,group.by = "patient.ident") 
```

```{r}
saveRDS(object = acc,file = paste("./Data/acc_tpm_nCount_mito_no146_15k_with_ACC1",suffix, sep = "_") %>% 
          paste0(".RDS"))
```

```{r eval=FALSE, include=FALSE}
#save notebook:
rstudioapi::documentSave() #save doc
this_notebooke_path = rstudioapi::getSourceEditorContext()$path
previewed_notebook = gsub(pattern = ".Rmd",replacement = ".nb.html",x = this_notebooke_path)
final_notebook  = basename(this_notebooke_path) %>% gsub(pattern = ".Rmd",replacement = "")
file.copy(from = previewed_notebook, to = dirname(this_notebooke_path) %>% paste(final_notebook,sep = "/") %>% paste(suffix,sep = "_") %>% paste0(".html"))
```