---
title: '`r rstudioapi::getSourceEditorContext()$path %>% basename() %>% gsub(pattern = "\\.Rmd",replacement = "")`' 
author: "Avishai Wizel"
date: '`r Sys.time()`'
output: 
  html_notebook: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: FALSE
    number_sections: true
    toc_depth: 1
---



# Functions

```{r warning=FALSE}
source_from_github(repositoy = "DEG_functions",version = "0.2.54")
genesets_h  = getGmt("./Input_data/h.all.v7.0.symbols.pluscc.gmt")
```

# signature
```{r}
# find hpv signature genes
hmsc_deg = read.table(file = "./Rendered_notebooks/HPV_analysis/HPV_analysis_2024_11_13/hpv_deg_df.csv",row.names = 1)
opscc_deg = readRDS(file = "./Rendered_notebooks/HPV_OPSCC_Analysis_PMC10191634/02_findDEG/02_findDEG_logFC_2024_11_13/opscc_deg_5Kvargenes.rds")
scc_deg = readRDS(file = "./Data_out/scc_deg_5Kvargenes.rds")


DT::datatable(hmsc_deg, caption = "hmsc_deg")
DT::datatable(opscc_deg, caption = "opscc_deg")
DT::datatable(scc_deg, caption = "scc_deg")

log2FC_cutoff = log2(1.3)
fdr_cutoff = 0.1

hmsc_top = hmsc_deg %>% filter(avg_log2FC > log2FC_cutoff &
                                 fdr < fdr_cutoff) %>% rownames()
opscc_top = opscc_deg %>% filter(avg_log2FC > log2FC_cutoff &
                                   fdr < fdr_cutoff) %>% rownames()
scc_top = scc_deg %>% filter(avg_log2FC > log2FC_cutoff &
                               fdr < fdr_cutoff) %>% rownames()

print ("intersect genes:")
intersect(intersect(hmsc_top,opscc_top),scc_top)
all_deg = list(hmsc_top = hmsc_top, opscc_top = opscc_top, scc_top = scc_top)

```
# Venn
```{r}
library(ggVennDiagram)
ggVennDiagram(all_deg)
```
# Save data
```{r}
# create data
deg_up_list = list(hmsc_up_deg = hmsc_top,
          opscc_up_deg = opscc_top,
          scc_up_deg = scc_top,
          hmsc_opscc = intersect(hmsc_top,opscc_top), 
          hmsc_scc = intersect(hmsc_top,scc_top),
          opscc_scc = intersect(opscc_top,scc_top), 
          shared = intersect(intersect(hmsc_top,opscc_top),scc_top)
          )
# save
library(openxlsx)
wb <- createWorkbook()
addWorksheet(wb, sheetName = "Sheet1")

for (i in 1:length(deg_up_list)) {
    writeData(wb, "Sheet1", names(deg_up_list)[i], startCol = i, startRow = 1,  
          rowNames = FALSE) #write name
  
  writeData(wb, "Sheet1", deg_up_list[[i]], startCol = i, startRow = 2,  
          rowNames = FALSE)
}

saveWorkbook(wb, "./Data_out/signature_compare/all_datasets_up_deg.xlsx", overwrite = TRUE)
```

# HMSC GSEA

```{r}
ranked_vec = hmsc_deg[,"avg_diff"]%>% setNames(rownames(hmsc_deg)) %>% na.omit() # make named vector
hyp_obj <-hypeR_fgsea(signature = ranked_vec,genesets = geneIds(genesets_h),up_only = F)

plt = hyp_dots(hyp_obj,merge = F,fdr = 0.2)
plt[[1]] + aes(size=nes)+ 
  guides(
    size = guide_legend(title="NES",reverse=T))


```
```{r}
# save
write.xlsx(hyp_obj$data$up$data,"./Data_out/signature_compare/HMSC_GSEA.xlsx")
```

# OPSCC GSEA

```{r}
ranked_vec = opscc_deg[,"avg_diff"]%>% setNames(rownames(opscc_deg)) %>% na.omit() # make named vector
hyp_obj <-hypeR_fgsea(signature = ranked_vec,genesets = geneIds(genesets_h),up_only = F)

plt = hyp_dots(hyp_obj,merge = F,fdr = 0.2)
plt[[1]] + aes(size=nes)+ 
  guides(
    size = guide_legend(title="NES",reverse=T))

plt[[2]] + aes(size=nes) +scale_size(trans = 'reverse')+
  guides(
    size = guide_legend(title="NES",reverse=F))


```
```{r}
# save
write.xlsx(hyp_obj$data$up$data,"./Data_out/signature_compare/OPSCC_GSEA.xlsx")
```
# SCC GSEA
```{r}
ranked_vec = scc_deg[,"avg_diff"]%>% setNames(rownames(scc_deg)) %>% na.omit() # make named vector
hyp_obj <-hypeR_fgsea(signature = ranked_vec,genesets = geneIds(genesets_h),up_only = F)

plt = hyp_dots(hyp_obj,merge = F,fdr = 0.2)
plt[[1]] + aes(size=nes)+ 
  guides(
    size = guide_legend(title="NES",reverse=T))

plt[[2]] + aes(size=nes) +scale_size(trans = 'reverse')+
  guides(
    size = guide_legend(title="NES",reverse=F))

```
```{r}
# save
write.xlsx(hyp_obj$data$up$data,"./Data_out/signature_compare/SCC_GSEA.xlsx")
```

# OPSCC boxplot
```{r}

top_genes = hmsc_deg %>% arrange(desc(.$avg_diff)) %>% head(5) %>% rownames()

top_genes_expr = FetchData(object = opscc,vars = c("hpv",top_genes))
df = reshape2::melt(top_genes_expr,value.name = "Expression") %>% dplyr::rename(gene = variable)

library(rstatix)
stat.test <- df %>%
    group_by(gene) %>%
  wilcox_test(Expression ~ hpv) %>%
  mutate(y.position = 5)

stat.test

stat.test <- stat.test %>% 
  add_xy_position(x = "gene", dodge = 0.8)

ggboxplot(
  df,
  x = "gene",
  y = "Expression",
  color = "hpv",
  palette = "jco",
  add = c("mean","boxplot"),trim = T
)+ stat_pvalue_manual(stat.test, label = "p = {p}",remove.bracket = T)
```
# SCC boxplot
```{r}

top_genes = hmsc_deg %>% arrange(desc(.$avg_diff)) %>% head(5) %>% rownames()

top_genes_expr = FetchData(object = scc_myb_patients,vars = c("hpv_positive",top_genes))
df = reshape2::melt(top_genes_expr,value.name = "Expression") %>% dplyr::rename(gene = variable)

library(rstatix)
stat.test <- df %>%
    group_by(gene) %>%
  wilcox_test(Expression ~ hpv_positive) %>%
  mutate(y.position = 5)

stat.test

stat.test <- stat.test %>% 
  add_xy_position(x = "gene", dodge = 0.8)

ggboxplot(
  df,
  x = "gene",
  y = "Expression",
  color = "hpv_positive",
  palette = "jco",
  add = c("mean","boxplot"),trim = T
)+ stat_pvalue_manual(stat.test, label = "p = {p}",remove.bracket = T)
```

