---
title: '`r rstudioapi::getSourceEditorContext()$path %>% basename() %>% gsub(pattern = "\\.Rmd",replacement = "")`' 
author: "Avishai Wizel"
date: '`r Sys.time()`'
output: 
  html_notebook: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: FALSE
    number_sections: true
    toc_depth: 1
    
  html_document: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: TRUE
    number_sections: true
    toc_depth: 2
params:
  signature: "HMSC"
---



# Functions

```{r warning=FALSE}
```

# Data

```{r}
opscc = readRDS("./Rendered_notebooks/HPV_OPSCC_Analysis_PMC10191634/01_preprocess/opscc_suerat.RDS")
library(readxl)
metadata = read_excel(path = "./Input_data/HPV_OPSCC_Analysis_PMC10191634/NIHMS1892753-supplement-Supp_Tables.xlsx",
          sheet = "S4 - Cell Table",progress = T,skip = 1,col_names = T)

# remove HPV- patients
hpv_neg<-c("OP10","OP12","OP16","OP19","OP8")
hpv_pos = unique(metadata$Patient)[! unique(metadata$Patient) %in% hpv_neg]
opscc_hpvPos = subset(opscc,subset = patient %in% hpv_pos)
```

# Cervical
```{r}
# read processed data:
SCC1_cancer  = readRDS(file = "./Data/cervical_cancer_data/Qiu et al/SCC1/SCC1_cancer.RDS")
SCC2_cancer  = readRDS(file = "./Data/cervical_cancer_data/Qiu et al/SCC2/SCC2_cancer_processed.RDS")
SCC3_cancer = readRDS(file = "./Data/cervical_cancer_data/Qiu et al/SCC3/SCC3_cancer_processed.RDS")
SCC4_cancer = readRDS(file = "./Data/cervical_cancer_data/Qiu et al/SCC4/SCC4_cancer_processed.RDS")
SCC5_cancer  = readRDS(file = "./Data/cervical_cancer_data/Qiu et al/SCC5/SCC5_cancer_processed.RDS")

scc.big <- merge(SCC1_cancer, y = c(SCC2_cancer,SCC3_cancer, SCC4_cancer,SCC5_cancer), add.cell.ids = c("SCC1","SCC2", "SCC3", "SCC4","SCC5"), project = "SCC")
scc.big$orig.ident =  sapply(X = strsplit(colnames(scc.big), split = "_"), FUN = "[", 1)


VlnPlot(object = scc.big,features = "MYB",group.by = "orig.ident",slot = "data", assay = "RNA")


```


```{r}
myb_data = FetchData(object = scc.big,vars = c("MYB","orig.ident"),slot = "data", assay = "RNA")
myb_data %>%   group_by(orig.ident) %>% 
  summarise(counts = sum(MYB > 0, na.rm = TRUE))
```


# Patients filter
```{r fig.height=6, fig.width=12}
scc_myb_patients<- subset(scc.big, subset = orig.ident %in% c("SCC3","SCC4","SCC5"))
```


# HMSC 

```{r}
hmsc_cancer_cells = readRDS("./Data_out/03_HMSC_cells_preprocess_2024-05-12/acc1_cancer_cells_2500features_integrated_V5.RDS")
genesets  = getGmt("./Input_data/h.all.v7.0.symbols.pluscc.gmt")

```

# HPV UMAP

```{r}
HPV33_P3 = fread("./Data/HPV33_P3.txt",col.names = c("plate","reads")) %>% as.data.frame()
HPV33_P3.df = HPV33_P3 %>% mutate(
  plate = gsub(x =HPV33_P3$plate, replacement = "",pattern = "_.*$") 
  %>% gsub(pattern = "-P",replacement = ".P") 
  %>% gsub(pattern = "-",replacement = "_",)
  )
HPV33_P3.df = HPV33_P3.df %>% dplyr::filter(HPV33_P3.df$plate %in% colnames(hmsc_cancer_cells))
rownames(HPV33_P3.df)  <- HPV33_P3.df$plate
HPV33_P3.df$plate = NULL


HPV33_P2 = fread("./Data/HPV33_P2.txt",col.names = c("plate","reads")) %>% as.data.frame()
HPV33_P2.df = HPV33_P2 %>% mutate(
  plate = gsub(x =HPV33_P2$plate, replacement = "",pattern = "_.*$") 
  %>% gsub(pattern = "plate2-",replacement = "plate2_",)
  %>% gsub(pattern = "-",replacement = "\\.",)
  )
HPV33_P2.df = HPV33_P2.df %>% dplyr::filter(HPV33_P2.df$plate %in% colnames(hmsc_cancer_cells))
rownames(HPV33_P2.df)  <- HPV33_P2.df$plate
HPV33_P2.df$plate = NULL

HPV33 = rbind(HPV33_P3.df,HPV33_P2.df)
hmsc_cancer_cells = AddMetaData(object = hmsc_cancer_cells,metadata = HPV33,col.name = "HPV33.reads")
FeaturePlot(hmsc_cancer_cells,features = "HPV33.reads",max.cutoff = 10)
```




```{r}
hpv33_positive = HPV33 %>% dplyr::mutate(hpv33_positive = case_when(reads >= 10 ~ "positive",
                                                                    reads < 10 ~ "negative")
)



hpv33_positive$reads = NULL
hmsc_cancer_cells = AddMetaData(object = hmsc_cancer_cells,metadata = hpv33_positive)
```


# signature
```{r}
# find hpv signature genes
hmsc_deg = read.table(file = "./Data_out/HPV_analysis/hpv_deg_df.csv",row.names = 1)
opscc_deg = readRDS(file = "./Data_out/opscc_deg.rds")
scc_deg = readRDS(file = "./Data_out/scc_deg.rds")

if(params$signature == "HMSC"){
  avg_diff_cutoff = 1
  fdr_cutoff = 0.1
  signature = hmsc_deg %>% filter(avg_diff>avg_diff_cutoff & fdr<fdr_cutoff) %>% rownames()
  signature
  
}else{
  DT::datatable(hmsc_deg,caption = "hmsc_deg")
  DT::datatable(opscc_deg,caption = "opscc_deg")
  DT::datatable(scc_deg,caption = "scc_deg")
  
  avg_diff_cutoff = 0.1
  fdr_cutoff = 0.1
  
  hmsc_top = hmsc_deg %>% filter(avg_diff>avg_diff_cutoff & fdr<fdr_cutoff) %>% rownames()
  opscc_top = opscc_deg %>% filter(avg_diff>avg_diff_cutoff & fdr<fdr_cutoff) %>% rownames()
  scc_top = scc_deg %>% filter(avg_diff>avg_diff_cutoff & fdr<fdr_cutoff) %>% rownames()
  
  signature = intersect(intersect(hmsc_top,scc_top),opscc_top)
  print("shared DEG:")
  signature
  
}

```
```{r}
metagenes_violin_compare.2 = function(dataset,prefix = "",pre_on = c("OSI","NT"),axis.text.x = 11,test = "t.test", programs = c("Hypoxia","TNFa","Cell_cycle"),return_list = F,combine_patients = F){
  require(facefuns)
  plt.lst = list()
  if(combine_patients){
    genes_by_tp = FetchData(object = dataset,vars =  c("treatment",programs)) %>% filter(treatment %in% pre_on)  %>% as.data.frame() #mean expression
    formula <- as.formula(paste0(programs, "~ treatment ") )
    
    #plot and split by patient:   
    stat.test = compare_means(formula = formula ,data = genes_by_tp,method = test,p.adjust.method = "fdr")%>% # Add pairwise comparisons p-value
      dplyr::filter(group1 == pre_on[1] & group2 == pre_on[2])  #filter for pre vs on treatment only
    
    stat.test$p.format =stat.test$p.adj #modift 0 pvalue to be lowest possible float
    stat.test$p.format[!stat.test$p.1format == 0 ] <- paste("=",stat.test$p.format[!stat.test$p.format == 0 ])
    stat.test$p.format[stat.test$p.format == 0 ] <- paste("<",.Machine$double.xmin %>% signif(digits = 3))
    
    
    genes_by_tp = reshape2::melt(genes_by_tp, id.vars = c("treatment"),value.name = "score")
    plt = ggplot(genes_by_tp, aes(x = variable, y = score,fill = treatment)) + geom_split_violin(scale = 'width')+ 
      geom_boxplot(width = 0.25, notch = FALSE, notchwidth = .4, outlier.shape = NA, coef=0)+
      ylim(min(genes_by_tp$score),max(genes_by_tp$score)*1.25)
    plt = plt +stat_pvalue_manual(stat.test, label = "{p.signif}", label.size = 7,  #add p value
                                  y.position = max(genes_by_tp$score)*1.08,inherit.aes = F,size = 3.3,x = ".y.") # set position at the top value
    return(plt)
  }
  
  
  
  
  
  if (return_list) {
    return(plt.lst)
  }
}
```

```{r}
hpv_signature = FetchData(object = opscc_hpvPos,vars = signature) %>% rowMeans()
hpv_score_df = data.frame(hpv_signature,row.names = names(hpv_signature))
opscc_hpvPos = AddMetaData(object = opscc_hpvPos,metadata = hpv_score_df)

opscc_hpvPos = SetIdent(opscc_hpvPos,value = "hpv")
VlnPlot(object = opscc_hpvPos,features = "hpv_signature")

opscc_hpvPos@meta.data[["treatment"]] = factor(opscc_hpvPos$hpv, levels = c("HPV+", "HPV-"))

plt = metagenes_violin_compare.2(dataset = opscc_hpvPos, prefix = "patient",pre_on = c("HPV+","HPV-"),test = "wilcox.test",programs = "hpv_signature", return_list = F,combine_patients = T)+ labs(fill = "")+ylab("Expression")+xlab("Gene")+theme(axis.text=element_text(size=12),
        axis.title=element_text(size=14))+ labs(fill = "")+ylab("Expression")+xlab("Gene")+theme(axis.title=element_text(size=14))+ scale_fill_manual(values=c("#F8766D", "cyan3")) +ggtitle("OPSCC") #from bovona.rmd
plt

```



```{r}
hpv_signature = FetchData(object = scc_myb_patients,vars = signature) %>% rowMeans()
hpv_score_df = data.frame(hpv_signature,row.names = names(hpv_signature))
scc_myb_patients = AddMetaData(object = scc_myb_patients,metadata = hpv_score_df)

scc_myb_patients = SetIdent(scc_myb_patients,value = "hpv_positive")
VlnPlot(object = scc_myb_patients,features = "hpv_signature")

scc_myb_patients@meta.data[["treatment"]] = factor(scc_myb_patients$hpv_positive, levels = c("positive", "negative"))

plt = metagenes_violin_compare.2(dataset = scc_myb_patients, prefix = "patient",pre_on =  c("positive", "negative"),test = "wilcox.test",programs = "hpv_signature", return_list = F,combine_patients = T)+ labs(fill = "")+ylab("Expression")+xlab("Gene")+theme(axis.text=element_text(size=12),
        axis.title=element_text(size=14))+ labs(fill = "")+ylab("Expression")+xlab("Gene")+theme(axis.title=element_text(size=14))+ scale_fill_manual(values=c("#F8766D", "cyan3")) +ggtitle("SCC") #from bovona.rmd
plt

```
```{r}
hpv_signature = FetchData(object = hmsc_cancer_cells,vars = signature) %>% rowMeans()
hpv_score_df = data.frame(hpv_signature,row.names = names(hpv_signature))
hmsc_cancer_cells = AddMetaData(object = hmsc_cancer_cells,metadata = hpv_score_df)

hmsc_cancer_cells = SetIdent(hmsc_cancer_cells,value = "hpv33_positive")
VlnPlot(object = hmsc_cancer_cells,features = "hpv_signature")

hmsc_cancer_cells@meta.data[["treatment"]] = factor(hmsc_cancer_cells$hpv33_positive, levels = c("positive", "negative"))

plt = metagenes_violin_compare.2(dataset = hmsc_cancer_cells, prefix = "patient",pre_on =  c("positive", "negative"),test = "wilcox.test",programs = "hpv_signature", return_list = F,combine_patients = T)+ labs(fill = "")+ylab("Expression")+xlab("Gene")+theme(axis.text=element_text(size=12),
        axis.title=element_text(size=14))+ labs(fill = "")+ylab("Expression")+xlab("Gene")+theme(axis.title=element_text(size=14))+ scale_fill_manual(values=c("#F8766D", "cyan3")) +ggtitle("HMSC") #from bovona.rmd
plt

```
