---
title: '`r rstudioapi::getSourceEditorContext()$path %>% basename() %>% gsub(pattern = "\\.Rmd",replacement = "")`' 
author: "Avishai Wizel"
date: '`r Sys.time()`'
output: 
  html_notebook: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: FALSE
    number_sections: true
    toc_depth: 1
---



# Functions

```{r warning=FALSE}
source_from_github(repositoy = "DEG_functions",version = "0.2.54")
genesets_h  = getGmt("./Input_data/h.all.v7.0.symbols.pluscc.gmt")
```

# signature
```{r}
# find hpv signature genes
hmsc_deg = read.table(file = "./Data_out/HPV_analysis/hpv_deg_df.csv",row.names = 1)
opscc_deg = readRDS(file = "./Data_out/opscc_deg_5Kvargenes.rds")
scc_deg = readRDS(file = "./Data_out/scc_deg_5Kvargenes.rds")


DT::datatable(hmsc_deg, caption = "hmsc_deg")
DT::datatable(opscc_deg, caption = "opscc_deg")
DT::datatable(scc_deg, caption = "scc_deg")

avg_diff_cutoff = 0.1
fdr_cutoff = 0.1

hmsc_top = hmsc_deg %>% filter(avg_diff > avg_diff_cutoff &
                                 fdr < fdr_cutoff) %>% rownames()
opscc_top = opscc_deg %>% filter(avg_diff > avg_diff_cutoff &
                                   fdr < fdr_cutoff) %>% rownames()
scc_top = scc_deg %>% filter(avg_diff > avg_diff_cutoff &
                               fdr < fdr_cutoff) %>% rownames()

print ("intersect genes:")
intersect(intersect(hmsc_top,opscc_top),scc_top)
all_deg = list(hmsc_top = hmsc_top, opscc_top = opscc_top, scc_top = scc_top)

```
# Venn
```{r}
library(ggVennDiagram)
ggVennDiagram(all_deg)
```
# HMSC GSEA

```{r}
ranked_vec = hmsc_deg[,"avg_diff"]%>% setNames(rownames(hmsc_deg)) %>% na.omit() # make named vector
hyp_obj <-hypeR_fgsea(signature = ranked_vec,genesets = geneIds(genesets_h),up_only = F)

plt = hyp_dots(hyp_obj,merge = F,fdr = 0.2)
plt[[1]] + aes(size=nes)+ 
  guides(
    size = guide_legend(title="NES",reverse=T))


```

# OPSCC GSEA

```{r}
ranked_vec = opscc_deg[,"avg_diff"]%>% setNames(rownames(opscc_deg)) %>% na.omit() # make named vector
hyp_obj <-hypeR_fgsea(signature = ranked_vec,genesets = geneIds(genesets_h),up_only = F)

plt = hyp_dots(hyp_obj,merge = F,fdr = 0.2)
plt[[1]] + aes(size=nes)+ 
  guides(
    size = guide_legend(title="NES",reverse=T))

plt[[2]] + aes(size=nes) +scale_size(trans = 'reverse')+
  guides(
    size = guide_legend(title="NES",reverse=F))


```

# SCC GSEA
```{r}
ranked_vec = scc_deg[,"avg_diff"]%>% setNames(rownames(scc_deg)) %>% na.omit() # make named vector
hyp_obj <-hypeR_fgsea(signature = ranked_vec,genesets = geneIds(genesets_h),up_only = F)

plt = hyp_dots(hyp_obj,merge = F,fdr = 0.2)
plt[[1]] + aes(size=nes)+ 
  guides(
    size = guide_legend(title="NES",reverse=T))

plt[[2]] + aes(size=nes) +scale_size(trans = 'reverse')+
  guides(
    size = guide_legend(title="NES",reverse=F))

```
# OPSCC boxplot
```{r}

top_genes = hmsc_deg %>% arrange(desc(.$avg_diff)) %>% head(5) %>% rownames()

top_genes_expr = FetchData(object = opscc,vars = c("hpv",top_genes))
df = reshape2::melt(top_genes_expr,value.name = "Expression") %>% dplyr::rename(gene = variable)

library(rstatix)
stat.test <- df %>%
    group_by(gene) %>%
  wilcox_test(Expression ~ hpv) %>%
  mutate(y.position = 5)

stat.test

stat.test <- stat.test %>% 
  add_xy_position(x = "gene", dodge = 0.8)

ggboxplot(
  df,
  x = "gene",
  y = "Expression",
  color = "hpv",
  palette = "jco",
  add = c("mean","boxplot"),trim = T
)+ stat_pvalue_manual(stat.test, label = "p = {p}",remove.bracket = T)
```
# SCC boxplot
```{r}

top_genes = hmsc_deg %>% arrange(desc(.$avg_diff)) %>% head(5) %>% rownames()

top_genes_expr = FetchData(object = scc_myb_patients,vars = c("hpv_positive",top_genes))
df = reshape2::melt(top_genes_expr,value.name = "Expression") %>% dplyr::rename(gene = variable)

library(rstatix)
stat.test <- df %>%
    group_by(gene) %>%
  wilcox_test(Expression ~ hpv_positive) %>%
  mutate(y.position = 5)

stat.test

stat.test <- stat.test %>% 
  add_xy_position(x = "gene", dodge = 0.8)

ggboxplot(
  df,
  x = "gene",
  y = "Expression",
  color = "hpv_positive",
  palette = "jco",
  add = c("mean","boxplot"),trim = T
)+ stat_pvalue_manual(stat.test, label = "p = {p}",remove.bracket = T)
```

