---
title: '`r rstudioapi::getSourceEditorContext()$path %>% basename() %>% gsub(pattern = "\\.Rmd",replacement = "")`' 
author: "Avishai Wizel"
date: '`r Sys.Date()`'
output: 
  html_notebook: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: FALSE
---
## cnv

```{r}
ggbarstats(
  cnv_vs_plate, cnv.cluster, orig.ident,
  results.subtitle = FALSE,
  subtitle = paste0(
    "Fisher's exact test", ", p-value = ",
    ifelse(test$p.value < 0.001, "< 0.001", round(test$p.value, 3))
  )
)

```

```{r}

pheatmap(infercnv.observations2,cluster_cols = F,cluster_rows = F, show_rownames = F,show_colnames = F, breaks = breaks,color = colorRampPalette(rev(c("darkred", "white", "darkblue")))(15),annotation_row = cnv_subtypes,annotation_colors = annoCol)

```
## cNMF
```{r}
cnmf_vs_plate = FetchData(object = acc1_cancer_cells,vars = c("program.assignment","orig.ident"))
cnmf_vs_plate= cnmf_vs_plate %>% dplyr::filter(program.assignment == "1" | program.assignment == "2")
test <- fisher.test(table(cnmf_vs_plate))
ggbarstats(
  cnmf_vs_plate, program.assignment, orig.ident,
  results.subtitle = FALSE,
  subtitle = paste0(
    "Fisher's exact test", ", p-value = ",
    ifelse(test$p.value < 0.001, "< 0.001", round(test$p.value, 3))
  )
)

```

## cNMF {.tabset}


### exceptions

```{r}
DimPlot(object = acc1_cancer_cells, cells.highlight = cells, cols.highlight = c("green","red"), cols = "gray", order = TRUE,pt.size = 2,sizes.highlight = 2) + ggtitle("exceptions")

```
### program.assignment

```{r}
DimPlot(acc1_cancer_cells,group.by = "program.assignment",pt.size = 2,cols =colors)
```
### metagene.1

```{r}
FeaturePlot(object = acc1_cancer_cells,features = c("metagene.1"))

```
### metagene.2

```{r }

FeaturePlot(object = acc1_cancer_cells,features = c("metagene.2"))

```

