---
title: '`r rstudioapi::getSourceEditorContext()$path %>% basename() %>% gsub(pattern = "\\.Rmd",replacement = "")`' 
author: "Avishai Wizel"
date: '`r Sys.time()`'
output: 
  html_notebook: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: FALSE
    number_sections: true
    toc_depth: 1
---



# Functions

```{r warning=FALSE}
```



# Data

```{r}
acc1_cancer_cells = readRDS("./Data/acc1_cancer_cells_15KnCount_V3.RDS")
acc1_cancer_cells$plate = acc1_cancer_cells$orig.ident
```

```{r}
data("HumanDC")
exp <- HumanDC[["exp"]]
meta <- HumanDC[["metadata"]]
```

```{r}
exp = list()
meta = list()
acc1_cancer_cells.list <- SplitObject(acc1_cancer_cells, split.by = "plate")
exp[["ACC.plate2"]] = acc1_cancer_cells.list$ACC.plate2@assays$RNA@data %>% as.array()
exp[["ACC1.P3"]] = acc1_cancer_cells.list$ACC1.P3@assays$RNA@data %>% as.array()


meta[["ACC.plate2"]] = data.frame(cell_id = rownames(acc1_cancer_cells.list$ACC.plate2@meta.data), cell_type = "cancer", dataset = acc1_cancer_cells.list$ACC.plate2$plate %>% as.character())

meta[["ACC1.P3"]] = data.frame(cell_id = rownames(acc1_cancer_cells.list$ACC1.P3@meta.data), cell_type = "cancer", dataset = acc1_cancer_cells.list$ACC1.P3$plate %>% as.character())

```

```{r}
library(SCIBER)
omega <- c()
omega[[1]] <- 0.8

ref_index <- 2
n_core <- 1

res <- SCIBER(input_batches = exp, ref_index = ref_index,
              batches_meta_data = meta, omega = omega, n_core = n_core)
```

```{r}
norm_exp_1 = res[[1]] %>% as.data.frame()
norm_exp_2 = res[[2]] %>% as.data.frame()

norm_exp = cbind(res[[1]] %>% as.data.frame(),res[[2]]%>% as.data.frame())
acc1_cancer_cells[["sciber"]]  = CreateAssayObject(counts = norm_exp)
DefaultAssay(acc1_cancer_cells) <- "sciber"
```

```{r}
acc1_cancer_cells = FindVariableFeatures(object = acc1_cancer_cells,nfeatures = 15000)
acc1_cancer_cells <- ScaleData(acc1_cancer_cells, verbose = FALSE)
acc1_cancer_cells <- RunPCA(acc1_cancer_cells, npcs = 30, verbose = FALSE)
ElbowPlot(acc1_cancer_cells)

```
```{r message=FALSE, warning=FALSE}
acc1_cancer_cells <- RunUMAP(acc1_cancer_cells, reduction = "pca", dims = 1:10)
acc1_cancer_cells <- FindNeighbors(acc1_cancer_cells, reduction = "pca", dims = 1:10)
acc1_cancer_cells <- FindClusters(acc1_cancer_cells, resolution = 0.5)
```

## UMAPS
```{r}
DimPlot(acc1_cancer_cells, reduction = "umap", group.by = "plate")
DimPlot(acc1_cancer_cells, reduction = "umap")
```




```{r}
acc_deg <- FindMarkers(acc1_cancer_cells, ident.1 = "0",features = VariableFeatures(acc1_cancer_cells),densify = T)
enrichment_analysis(acc_deg,background = VariableFeatures(acc1_cancer_cells),fdr_Cutoff = 0.01,ident.1 = "0",ident.2 = "1",show_by = 1)

acc_deg <- FindMarkers(acc1_cancer_cells, ident.1 = "1",features = VariableFeatures(acc1_cancer_cells),densify = T)
enrichment_analysis(acc_deg,background = VariableFeatures(acc1_cancer_cells),fdr_Cutoff = 0.01,ident.1 = "1",ident.2 = "1",show_by = 1)

acc_deg <- FindMarkers(acc1_cancer_cells, ident.1 = "2",features = VariableFeatures(acc1_cancer_cells),densify = T)
enrichment_analysis(acc_deg,background = VariableFeatures(acc1_cancer_cells),fdr_Cutoff = 0.01,ident.1 = "2",ident.2 = "1",show_by = 1)
```

```{r}
acc_deg <- FindMarkers(acc1_cancer_cells, ident.1 = "2",ident.2 = "0", features = VariableFeatures(acc1_cancer_cells),densify = T)
enrichment_analysis(acc_deg,background = VariableFeatures(acc1_cancer_cells),fdr_Cutoff = 0.01,ident.1 = "2",ident.2 = "0",show_by = 1)

acc_deg <- FindMarkers(acc1_cancer_cells, ident.1 = "2",ident.2 = "1", features = VariableFeatures(acc1_cancer_cells),densify = T)
enrichment_analysis(acc_deg,background = VariableFeatures(acc1_cancer_cells),fdr_Cutoff = 0.01,ident.1 = "2",ident.2 = "1",show_by = 1)

```
```{r}
acc_deg <- FindMarkers(acc1_cancer_cells, ident.1 = "0",ident.2 = "1", features = VariableFeatures(acc1_cancer_cells),densify = T)
enrichment_analysis(acc_deg,background = VariableFeatures(acc1_cancer_cells),fdr_Cutoff = 0.01,ident.1 = "0",ident.2 = "1",show_by = 1)

acc_deg <- FindMarkers(acc1_cancer_cells, ident.1 = "1",ident.2 = "0", features = VariableFeatures(acc1_cancer_cells),densify = T)
enrichment_analysis(acc_deg,background = VariableFeatures(acc1_cancer_cells),fdr_Cutoff = 0.01,ident.1 = "1",ident.2 = "0",show_by = 1)

```
```{r}
acc1_cancer_cells_filtered = subset(acc1_cancer_cells, subset = seurat_clusters !=2)
```

## HPV-MYB
```{r}
HPV33_P3 = fread("../Data/HPV33_P3.txt",col.names = c("plate","reads")) %>% as.data.frame()
HPV33_P3.df = HPV33_P3 %>% mutate(
  plate = gsub(x =HPV33_P3$plate, replacement = "",pattern = "_.*$") 
  %>% gsub(pattern = "-P",replacement = ".P") 
  %>% gsub(pattern = "-",replacement = "_",)
  )
HPV33_P3.df = HPV33_P3.df %>% dplyr::filter(HPV33_P3.df$plate %in% colnames(acc1_cancer_cells))
rownames(HPV33_P3.df)  <- HPV33_P3.df$plate
HPV33_P3.df$plate = NULL


HPV33_P2 = fread("../Data/HPV33_P2.txt",col.names = c("plate","reads")) %>% as.data.frame()
HPV33_P2.df = HPV33_P2 %>% mutate(
  plate = gsub(x =HPV33_P2$plate, replacement = "",pattern = "_.*$") 
  %>% gsub(pattern = "plate2-",replacement = "plate2_",)
  %>% gsub(pattern = "-",replacement = "\\.",)
  )
HPV33_P2.df = HPV33_P2.df %>% dplyr::filter(HPV33_P2.df$plate %in% colnames(acc1_cancer_cells))
rownames(HPV33_P2.df)  <- HPV33_P2.df$plate
HPV33_P2.df$plate = NULL

HPV33 = rbind(HPV33_P3.df,HPV33_P2.df)
acc1_cancer_cells = AddMetaData(object = acc1_cancer_cells,metadata = HPV33,col.name = "HPV33.reads")
```

```{r}
hpv33_positive = HPV33 %>% dplyr::mutate(hpv33_positive = case_when(reads >= 10 ~ "positive",
                                                                    reads < 10 ~ "negative")
)



hpv33_positive$reads = NULL
acc1_cancer_cells = AddMetaData(object = acc1_cancer_cells,metadata = hpv33_positive)
```


```{r}
myb_vs_hpv = FetchData(object = acc1_cancer_cells,vars = c("hpv33_positive","MYB"))
myb_vs_hpv $hpv33_positive = as.character(myb_vs_hpv $hpv33_positive )

ggboxplot(myb_vs_hpv, x = "hpv33_positive", y = "MYB",
          palette = "jco",
          add = "jitter")+ stat_compare_means(method = "t.test",comparisons = list(c("positive","negative")))+ stat_summary(fun.data = function(x) data.frame(y=15, label = paste("Mean=",round(mean(x),digits = 2))), geom="text") +ylab("log2(MYB)")

```
```{r}
plate_1 = subset(acc1_cancer_cells,subset = plate == "ACC.plate2")
myb_vs_hpv = FetchData(object = plate_1,vars = c("hpv33_positive","MYB"))
myb_vs_hpv $hpv33_positive = as.character(myb_vs_hpv $hpv33_positive )

p = ggboxplot(myb_vs_hpv, x = "hpv33_positive", y = "MYB",
          palette = "jco",
          add = "jitter")+ stat_compare_means(method = "wilcox.test",comparisons = list(c("positive","negative")))+ stat_summary(fun.data = function(x) data.frame(y=15, label = paste("Mean=",round(mean(x),digits = 2))), geom="text") +ylab("log2(MYB)")+ggtitle("ACC.plate2")

plate_2 = subset(acc1_cancer_cells,subset = plate == "ACC1.P3")
myb_vs_hpv = FetchData(object = plate_2,vars = c("hpv33_positive","MYB"))
myb_vs_hpv $hpv33_positive = as.character(myb_vs_hpv $hpv33_positive )

p+ggboxplot(myb_vs_hpv, x = "hpv33_positive", y = "MYB",
          palette = "jco",
          add = "jitter")+ stat_compare_means(method = "wilcox.test",comparisons = list(c("positive","negative")))+ stat_summary(fun.data = function(x) data.frame(y=15, label = paste("Mean=",round(mean(x),digits = 2))), geom="text") +ylab("log2(MYB)")+ggtitle("ACC1.P3")
```

```{r}
original_myo_genes = c( "TP63", "TP73", "CAV1", "CDH3", "KRT5", "KRT14", "ACTA2", "TAGLN", "MYLK", "DKK3")
original_lum_genes = c("KIT", "EHF", "ELF5", "KRT7", "CLDN3", "CLDN4", "CD24", "LGALS3", "LCN2", "SLPI" )
```



```{r}
calculate_score(dataset = acc1_cancer_cells,myo_genes = original_myo_genes,lum_genes = original_lum_genes)
```
<script src="https://hypothes.is/embed.js" async></script>

