---
title: "Cancer_filtering"
date: 6.12.22
output: 
  html_notebook: 
    code_folding: hide
---
## Parameters:

```{r}
suffix = ""
data_to_read = "acc_tpm_nCount_mito_no146_15k_with_ACC1_V2.RDS"
```



```{r}
source_from_github(repositoy = "DEG_functions",version = "0.2.1")
acc_all_cells = readRDS("./Data/" %>% paste0(data_to_read))
```

## UMAP
```{r fig.width=8}
DimPlot(acc_all_cells, reduction = "umap", label = TRUE, pt.size = 0.5,group.by = "patient.ident") 
```

## UMAP by cluster
```{r fig.width=8}
DimPlot(acc_all_cells, reduction = "umap", label = TRUE, pt.size = 0.5) 
```

add kaye_acc_score
```{r}
acchigh=read.delim("./Data/oncotarget-05-12528-s001_acchigh.txt",skip=0,header=F,sep="\t",stringsAsFactors=F)
acchigh_s=apply(acc_all_cells@assays$RNA@scale.data[intersect(acchigh$V1,acc_all_cells@assays$RNA@var.features),],2,mean)
acchigh_s[acchigh_s < -0.5] = -0.5
acchigh_s[acchigh_s > 0.5] = 0.5
acc_all_cells=AddMetaData(acc_all_cells,acchigh_s,"kaye_acc_score")
```

## Markers {.tabset}

### CAF markers


```{r fig.width=15}
FeaturePlot(acc_all_cells, c("COL3A1","COL1A2") ,cols = c("blue","yellow"))
```
###  Endothelial markers


```{r fig.width=15}
FeaturePlot(acc_all_cells, c("VWF","PECAM1") ,cols = c("blue","yellow"))
```


###  WBC markers

```{r fig.width=15}
FeaturePlot(acc_all_cells, c("CD79A","PTPRC") ,cols = c("blue","yellow"))

```

### ACC markers

```{r fig.width=15}
FeaturePlot(acc_all_cells, c("kaye_acc_score","MYB") ,cols = c("blue","yellow"))
```
## {-}


## 3.Cluster assignment
```{r}
new.cluster.ids <- c("0" = "ACC", #0
                     "1" =  "ACC", #1
                     "2" =  "CAF", #2
                     "3" =  "ACC", #3
                     "4" = "Endothelial", #4
                     "5" = "ACC", #5
                     "6" = "HMSC", #6
                     "7" = "CAF", #7
                     "8" = "CAF", #8
                     "9" = "CAF", #9
                     "10" = "ACC", #10
                     "11" = "CAF", #11
                     "12" = "ACC", #12
                     "13" = "ACC", #13
                     "14" = "ACC", #14
                     "15" = "ACC", #15
                     "16" = "ACC", #16
                     "17" = "WBC", #17
                     "18" = "CAF" #18
                     )
```


```{r}
names(new.cluster.ids) <- levels(acc_all_cells)
acc_all_cells = SetIdent(object = acc_all_cells,value = "seurat_clusters")
acc_all_cells <- RenameIdents(acc_all_cells, new.cluster.ids)
DimPlot(acc_all_cells, reduction = "umap", label = F, pt.size = 0.5) 
```

## Cell types in ACC1
```{r results='hide'}
cell.type <- acc_all_cells@meta.data$seurat_clusters
levels(cell.type) <- new.cluster.ids
acc_all_cells <- AddMetaData(object = acc_all_cells, metadata = as.factor(cell.type), col.name = "cell.type")

acc1_all_cells = subset(x = acc_all_cells,subset = patient.ident == "ACC1")
acc1_types = acc1_all_cells@meta.data[["cell.type"]] %>% table() %>% as.data.frame()
names(acc1_types)[1] = "type"
ggplot(data=acc1_types, aes(x=type, y=Freq)) +
  geom_bar(stat="identity", fill="steelblue")+
  geom_text(aes(label=Freq), vjust=-0.5, color="black", size=3.5)
```

## ACC cancer cells dim reduction
```{r}
acc_cancer_cells = subset(x = acc_all_cells,subset = cell.type == "ACC")
acc_cancer_cells <- FindVariableFeatures(acc_cancer_cells, selection.method = "vst", nfeatures = 15000)
acc_cancer_cells <- ScaleData(acc_cancer_cells, vars.to.regress = c("percent.mt","nCount_RNA"))
acc_cancer_cells <- RunPCA(acc_cancer_cells, features = VariableFeatures(object = acc_cancer_cells))
ElbowPlot(acc_cancer_cells, ndims = 50) # checking the dimensionality 
```

```{r}
pc2use = 1:25
```


```{r}
acc_cancer_cells <- FindNeighbors(acc_cancer_cells, dims = pc2use)
acc_cancer_cells <- FindClusters(acc_cancer_cells, resolution = 1)
acc_cancer_cells <- RunUMAP(acc_cancer_cells, dims = pc2use)
```

```{r}
DimPlot(acc_cancer_cells,pt.size = 0.5)
DimPlot(acc_cancer_cells,pt.size = 0.5,group.by = "patient.ident")
```


```{r}
file_name = paste("./Data/acc_cancer_cells_V3.RDS")

if (!file.exists(file_name)){
  saveRDS(object = acc_cancer_cells,file = file_name)
}else (stop("file exists"))
```

```{r}
acc_cancer_cells = read_rds("./Data/acc_cancer_cells_V3.RDS")
```



## ACC1 cancer cells dim reduction
```{r results='hide'}
acc1_cancer_cells = subset(x = acc_cancer_cells,subset = patient.ident == "ACC1")
acc1_cancer_cells <- FindVariableFeatures(acc1_cancer_cells, selection.method = "vst", nfeatures = 15000)
acc1_cancer_cells <- ScaleData(acc1_cancer_cells, vars.to.regress = c("nCount_RNA","percent.mt"))
acc1_cancer_cells <- RunPCA(acc1_cancer_cells, features = VariableFeatures(object = acc1_cancer_cells))
ElbowPlot(acc1_cancer_cells, ndims = 50) # checking the dimensionality 
```

```{r results='hide'}
acc1_cancer_cells = subset(x = acc_cancer_cells,subset = patient.ident == "ACC1")
acc1_cancer_cells <- FindVariableFeatures(acc1_cancer_cells, selection.method = "vst", nfeatures = 15000)
acc1_cancer_cells <- ScaleData(acc1_cancer_cells, vars.to.regress = c("nCount_RNA","percent.mt"))
acc1_cancer_cells <- RunPCA(acc1_cancer_cells, features = VariableFeatures(object = acc1_cancer_cells))
ElbowPlot(acc1_cancer_cells, ndims = 50) # checking the dimensionality 
```
```{r}
pc2use = 1:25
```


```{r echo=TRUE}
acc1_cancer_cells <- FindNeighbors(acc1_cancer_cells, dims = pc2use,k.param  = 5,annoy.metric = "cosine")
acc1_cancer_cells <- FindClusters(acc1_cancer_cells, resolution = 0.5)
acc1_cancer_cells <- RunUMAP(acc1_cancer_cells, dims = pc2use,n.neighbors = 5)
```

```{r}
DimPlot(acc1_cancer_cells,pt.size = 1)
```

```{r}
# saveRDS(object = acc1_cancer_cells,file = "./Data/acc1_cancer_cells_V3.RDS")
```

```{r}
acc1_cancer_cells = read_rds("./Data/acc1_cancer_cells_V3.RDS")
```

```{r}
acc1_cancer_cells.df = acc1_cancer_cells@assays[["RNA"]]@data %>% as.data.frame()
acc1_cor = cor(acc1_cancer_cells.df)
annotation = FetchData(object = acc1_cancer_cells,vars = c("cell.type"))
pht1 = pheatmap(acc1_cor,annotation_row = annotation,fontsize = 6,silent = T)
```



```{r}
acc1_cancer_cells.df = acc1_cancer_cells@assays[["RNA"]]@data %>% as.data.frame()
acc1_cor = cor(acc1_cancer_cells.df)
annotation = FetchData(object = acc1_cancer_cells,vars = c("cell.type"))
pheatmap(acc1_cor,annotation_row = annotation,fontsize = 6,silent = F)
```

```{r}
num_of_clusters = 3
clustering_distance = "euclidean"

  

annotation = FetchData(object = acc1_cancer_cells,vars = c("orig.ident"))


colors <- c(seq(-1,1,by=0.01))
my_palette <- c("blue",colorRampPalette(colors = c("blue", "white", "red"))
                                                 (n = length(colors)-3), "red")
plate = FetchData(object = acc1_cancer_cells,vars = "orig.ident" )
pheatmap(mat = acc1_cor,annotation_col =  annotation, clustering_distance_rows = clustering_distance,clustering_distance_cols = clustering_distance,color = my_palette,breaks = colors,show_rownames = F,show_colnames = F)
```

```{r}
num_of_clusters = 3
clustering_distance = "euclidean"
myannotation = as.data.frame(cutree(pht1[["tree_row"]], k = num_of_clusters))
 
names(myannotation)[1] = "cluster"
  myannotation$cluster = as.factor(myannotation$cluster)
  
  palette1 <- palette(brewer.pal(num_of_clusters, "Paired"))
  palette1 <- palette(brewer.pal(num_of_clusters, "Paired")) #need to do twice to work
  
  names(palette1) = unique(myannotation$cluster)
  ann_colors = list (cluster = palette1)
  annotation = list(ann_colors = ann_colors, myannotation = myannotation)
  
  colors <- c(seq(-1,1,by=0.01))
  my_palette <- c("blue",colorRampPalette(colors = c("blue", "white", "red"))
                                                   (n = length(colors)-3), "red")
  plate = FetchData(object = acc1_cancer_cells,vars = "orig.ident" )
  pheatmap(mat = acc1_cor,annotation_col =  annotation[["myannotation"]], annotation_colors = annotation[["ann_colors"]], clustering_distance_rows = clustering_distance,clustering_distance_cols = clustering_distance,color = my_palette,breaks = colors,show_rownames = F,show_colnames = F)
```


```{r}
acc1_cancer_cells = AddMetaData(object = acc1_cancer_cells,metadata = myannotation,col.name = "cor_cluster")
acc1_cancer_cells = AddMetaData(object = acc1_cancer_cells,metadata = acc.tpm_seurat$raw.counts,col.name = "raw.counts") #from create_data_V1

comparisons_1 <- list(c("1", "3"))
comparisons_2 <- list(c("2","3"))

VlnPlot(object = acc1_cancer_cells,group.by= "cor_cluster",features = "raw.counts")+ stat_compare_means(comparisons = comparisons_1, label = "p.signif",label.y = max(acc1_cancer_cells$raw.counts)*0.7)+ stat_compare_means(comparisons = comparisons_2, label = "p.signif",label.y = max(acc1_cancer_cells$raw.counts)*0.8)

VlnPlot(object = acc1_cancer_cells,group.by= "cor_cluster",features = "nFeature_RNA")+ stat_compare_means(comparisons = comparisons_1, label = "p.signif",label.y = max(acc1_cancer_cells$nFeature_RNA)*0.7)+ stat_compare_means(comparisons = comparisons_2, label = "p.signif",label.y = max(acc1_cancer_cells$nFeature_RNA)*0.8) + geom_hline(aes(yintercept = 2500, color = "2500 genes"))+scale_colour_manual(values = c("blue"))
```




```{r}
acc1_cancer_15KnCount = subset(x = acc1_cancer_cells,subset = nFeature_RNA > 2500)
acc1_cancer_15KnCount.df = acc1_cancer_15KnCount@assays[["RNA"]]@data %>% as.data.frame()
acc1_cor = cor(acc1_cancer_15KnCount.df)
annotation = FetchData(object = acc1_cancer_15KnCount,vars = c("cell.type"))

colors <- c(seq(-1,1,by=0.01))
  my_palette <- c("blue",colorRampPalette(colors = c("blue", "white", "red"))
                                                   (n = length(colors)-3), "red")
  
pht1 = pheatmap(acc1_cor,annotation_row = annotation,fontsize = 6,breaks = colors, color = my_palette,show_colnames = F,show_rownames = F)
```


```{r}
acc1_cancer_15KnCount <- FindVariableFeatures(acc1_cancer_15KnCount, selection.method = "vst", nfeatures = 15000)
acc1_cancer_15KnCount <- ScaleData(acc1_cancer_15KnCount, vars.to.regress = c("percent.mt","nCount_RNA"))
acc1_cancer_15KnCount <- RunPCA(acc1_cancer_15KnCount, features = VariableFeatures(object = acc1_cancer_15KnCount))
ElbowPlot(acc1_cancer_15KnCount, ndims = 50) # checking the dimensionality 
```

```{r}
pc2use = 1:20
```


```{r}
acc1_cancer_15KnCount <- FindNeighbors(acc1_cancer_15KnCount, dims = pc2use)
acc1_cancer_15KnCount <- FindClusters(acc1_cancer_15KnCount, resolution = 1)
acc1_cancer_15KnCount <- RunUMAP(acc1_cancer_15KnCount, dims = pc2use)
```

```{r}
DimPlot(acc1_cancer_15KnCount,pt.size = 1)
DimPlot(acc1_cancer_15KnCount,pt.size = 1,group.by = "orig.ident")
```


```{r}
acc1_cancer_15KnCount$plate = acc1_cancer_15KnCount$orig.ident
saveRDS(object = acc1_cancer_15KnCount,file = "./Data/acc1_cancer_cells_2500features_V3.RDS")
```

```{r}
acc1_cancer_cells = read_rds(file = "./Data/acc1_cancer_cells_2500features_V3.RDS")
```


remove acc1 cells that nCount_RNA<15K
```{r}
only_acc_cells_lst = colnames(acc_cancer_cells)[(!acc_cancer_cells$patient.ident == "ACC1")]
hmsc_filtered_cells_lst = colnames(acc1_cancer_15KnCount)

acc_cancer_cells = acc_cancer_cells [,c(only_acc_cells_lst,hmsc_filtered_cells_lst)]
```



# Plate bias
```{r fig.height=10, fig.width=8}

comparisons <- list(c("ACC.plate2", "ACC1.P3"))


plt1 = VlnPlot(object = acc1_cancer_cells,group.by= "orig.ident",features = "raw.counts")+ stat_compare_means(comparisons = comparisons, label = "p.signif",label.y = 4e06)
plt2 = VlnPlot(object = acc1_cancer_cells,group.by= "orig.ident",features = "nFeature_RNA")+ stat_compare_means(comparisons = comparisons, label = "p.signif",label.y = 10000)

plt1+plt2
```


```{r}
acc_cancer_cells <- FindVariableFeatures(acc_cancer_cells, selection.method = "vst", nfeatures = 15000)
acc_cancer_cells <- ScaleData(acc_cancer_cells, vars.to.regress = c("percent.mt","nCount_RNA"))
acc_cancer_cells <- RunPCA(acc_cancer_cells, features = VariableFeatures(object = acc_cancer_cells))
ElbowPlot(acc_cancer_cells, ndims = 50) # checking the dimensionality 
```

```{r}
pc2use = 1:20
```


```{r}
acc_cancer_cells <- FindNeighbors(acc_cancer_cells, dims = pc2use)
acc_cancer_cells <- FindClusters(acc_cancer_cells, resolution = 1)
acc_cancer_cells <- RunUMAP(acc_cancer_cells, dims = pc2use)
```

```{r}
DimPlot(acc_cancer_cells,pt.size = 0.5)
DimPlot(acc_cancer_cells,pt.size = 0.5,group.by = "patient.ident")
```


```{r}
ident = plyr::revalue(acc_cancer_cells@meta.data[["patient.ident"]], c("ACC1"="HMSC"))
acc_cancer_cells@meta.data[["patient.ident"]] <- ident
acc_cancer_cells = SetIdent(acc_cancer_cells, value = "patient.ident")

```

```{r}
DimPlot(acc_cancer_cells,pt.size = 0.5)
DimPlot(acc_cancer_cells,pt.size = 0.5,group.by = "patient.ident")+ggtitle("Patient identity")
```

## all_acc_cancercells_primaryOnly
```{r}
acc1_cancer_cells = readRDS("./Data/acc1_cancer_cells_2500features_integrated_V5.RDS")
all_acc_cancer_cells = readRDS("./Data/acc_cancer_cells_V5_integrated.RDS")
acc_cancerCells_noACC1 = readRDS("./Data/acc_cancer_no146_primaryonly15k_cancercells.rds")
```

```{r}
non_primary_list = c("ACC22.P12.LN","ACC22.LN.P11", "ACC5.P11","ACC7.P13")
primary_plates = all_acc_cancer_cells$orig.ident %>% unique() %>% as.vector() %>%  base::setdiff(non_primary_list)

all_acc_cancer_cells = SetIdent(object = all_acc_cancer_cells, value = "orig.ident")
all_acc_primary_cancer = subset(all_acc_cancer_cells, idents  = primary_plates)
```

```{r}
all_acc_primary_cancer <- FindVariableFeatures(all_acc_primary_cancer, selection.method = "vst", nfeatures = 15000)
all_acc_primary_cancer <- ScaleData(all_acc_primary_cancer, vars.to.regress = c("percent.mt","nCount_RNA"))
all_acc_primary_cancer <- RunPCA(all_acc_primary_cancer, features = VariableFeatures(object = all_acc_primary_cancer))
ElbowPlot(all_acc_primary_cancer, ndims = 50) # checking the dimensionality 
```

```{r}
pc2use = 1:20
```

```{r}
all_acc_primary_cancer <- FindNeighbors(all_acc_primary_cancer, dims = pc2use)
all_acc_primary_cancer <- FindClusters(all_acc_primary_cancer, resolution = 1)
all_acc_primary_cancer <- RunUMAP(all_acc_primary_cancer, dims = pc2use)
```

```{r}
DimPlot(all_acc_primary_cancer,pt.size = 1,group.by = "patient.ident")
DimPlot(all_acc_primary_cancer,pt.size = 1,group.by = "orig.ident")
FeaturePlot(object = all_acc_primary_cancer,features = "percent.mt")
```
```{r}
saveRDS(object = all_acc_primary_cancer,file = "./Data/acc_cancer_cells_V5_integrated_primary.RDS")
```
