---
title: '`r rstudioapi::getSourceEditorContext()$path %>% basename() %>% gsub(pattern = "\\.Rmd",replacement = "")`' 
author: "Avishai Wizel"
date: '`r Sys.time()`'
output:
  # html_notebook:
  #   code_folding: hide
  #   toc: true
  #   toc_collapse: true
  #   toc_float:
  #     collapsed: false
  #   number_sections: true
  #   toc_depth: 1
  html_document: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: TRUE
    number_sections: true
    toc_depth: 2
    df_print: paged
params: 
  data_out_dir: "./temp_data/" 
  input_data: !r c(
    matrix = "./Input_data/HPV_OPSCC_Analysis_PMC10191634/GSE182227_OPSCC.mtx.gz",
    b1 = "./Input_data/HPV_OPSCC_Analysis_PMC10191634/GSE182227_barcodes.txt.gz",
    g1 = "./Input_data/HPV_OPSCC_Analysis_PMC10191634/GSE182227_genes.txt.gz")
  output_data: !r c("opscc_suerat.RDS")
---


Read Data and create seurat object
Code and data from: https://github.com/micmin3/HPV_OPSCC_Analysis

# Functions

```{r warning=FALSE}
```

# Data

```{r}
#| Read data
matrix<-Matrix::readMM(params$input_data["matrix"])
b1<-read.table(params$input_data["b1"])
g1<-read.table(params$input_data["g1"])
```

```{r}
colnames(matrix)<-b1[,1]
rownames(matrix)<-g1[,1]
genespercell = colSums(matrix > 0) #Genes expressed per cell
cellthreshold<-genespercell>=1000 #|genespercell>=quantile(genespercell,0.4)#Local and global complexity threshold
merged<-matrix[,cellthreshold] #Filter cells by thresholds
```

```{r}
#| read metadata and keep cancer cells

library(readxl)
metadata = read_excel(path = "./Input_data/HPV_OPSCC_Analysis_PMC10191634/NIHMS1892753-supplement-Supp_Tables.xlsx",
          sheet = "S4 - Cell Table",progress = T,skip = 1,col_names = T)

cancer_cells = metadata %>% filter(Cancer_assignment == "Cancer") %>% pull(Cell_barcode)
merged_cancer = merged[,cancer_cells]
```


```{r}
#| create seurat object 
opscc = CreateSeuratObject(counts = merged_cancer, min.cells = 3, min.features = 200)
# QC and preprocess
opscc <- NormalizeData(opscc, normalization.method = "LogNormalize", scale.factor = 10000)
opscc <- FindVariableFeatures(opscc, selection.method = "vst", nfeatures = 5000)
seurat_metadata = data.frame(row.names = metadata$Cell_barcode,hpv = metadata$HPV, patient=metadata$Patient)
opscc = AddMetaData(object = opscc,metadata = seurat_metadata)
```



```{r}
#| save
file_name = paste0(params$data_out_dir,params$output_data)

saveRDS(object = opscc,file =file_name)
```