---
title: '`r rstudioapi::getSourceEditorContext()$path %>% basename() %>% gsub(pattern = "\\.Rmd",replacement = "")`' 
author: "Avishai Wizel"
date: '`r Sys.time()`'
output:
  # html_notebook: 
  #   code_folding: hide
  #   toc: true
  #   toc_collapse: true
  #   toc_float:
  #     collapsed: false
  #   number_sections: true
  #   toc_depth: 1
  html_document: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: TRUE
    number_sections: true
    toc_depth: 2
    df_print: paged
params: 
  data_out_dir: "./temp_data/" 
  input_data: !r c(opscc =  "./Reports/HPV_OPSCC_Analysis_PMC10191634/01_preprocess/opscc_suerat.RDS", metadata = "./Input_data/HPV_OPSCC_Analysis_PMC10191634/NIHMS1892753-supplement-Supp_Tables.xlsx",
   global_params  = "./Input_data/global_params.R")
  output_data: !r c(deg = "OPSCC_HPV_DEG.csv")
---


```{r}
source(params$input_data["global_params"])

```



```{r}
opscc = readRDS(params$input_data["opscc"])
library(readxl)
metadata = read_excel(path = params$input_data["metadata"],
          sheet = "S4 - Cell Table",progress = T,skip = 1,col_names = T)

# remove HPV- patients
hpv_neg<-c("OP10","OP12","OP16","OP19","OP8")
hpv_pos = unique(metadata$Patient)[! unique(metadata$Patient) %in% hpv_neg]
opscc_hpvPos = subset(opscc,subset = patient %in% hpv_pos)
```

```{r}
opscc_hpvPos = SetIdent(object = opscc_hpvPos,value = "hpv")
opscc_hpvPos = FindVariableFeatures(object = opscc_hpvPos,nfeatures = 15000)
var_features = VariableFeatures(object = opscc_hpvPos)

# top_expressed_features = opscc_hpvPos@assays$RNA@data %>% rowMeans() %>% sort(decreasing = T) %>% head(5000) %>% names()
# features = intersect(var_features, top_expressed_features)
features = var_features

```

```{r}
deg = FindConservedMarkers(object = opscc_hpvPos,ident.1 = "HPV+",ident.2 = "HPV-",
            features = features,grouping.var =  "patient",
            logfc.threshold = 0,min.pct = 0.1,densify = T,
            mean.fxn = function(x) {
            return(log(rowMeans(x) + 1, base = 2)) # change func to calculate logFC in log space data (default to exponent data)
            })

```

```{r}



opscc_deg = deg %>% rowwise() %>% mutate(second_min_avg_log2FC = sort(c_across(contains("avg_log2FC")))[4]) %>% ungroup() %>% as.data.frame()
rownames(opscc_deg) = rownames(deg)
hmsc_top = hmsc_deg %>% filter(avg_log2FC > log2(signature_fc) &
                                 fdr < signature_fdr) %>% rownames()
opscc_top = opscc_deg %>% filter(second_min_avg_log2FC > log2(signature_fc)) %>% rownames()

print ("intersect genes:")
intersected_genes = intersect(hmsc_top,opscc_top)
intersected_genes
```


```{r}

opscc_deg$fdr = max_pval
opscc_deg$avg_log2FC = max_avg_log2FC

plt = volcano_plot(
  de_genes = opscc_deg,
  fc_cutoff = volcano_fc,
  fdr_cutoff = volcano_fdr,
  ident1 = "HPV positive",
  ident2 = "HPV negative",
  top_genes_text = 0,
  show_gene_names = intersected_genes
  ) +
  ggtitle("Differential Gene Expression by HPV Status")  + 
  expand_limits(y = c(0, 4))+
  coord_cartesian(clip = "off")

plt
```

# DEG per patient

```{r}

all_deg = list()
for (patient in unique(opscc_hpvPos$patient)) {
  patient_obj =   opscc_hpvPos[,opscc_hpvPos$patient == patient]
  patient_obj = SetIdent(object = patient_obj, value = "hpv")
  patient_obj = FindVariableFeatures(object = patient_obj, nfeatures = 15000)
  var_features = VariableFeatures(object = patient_obj)
  
  top_expressed_features = patient_obj@assays$RNA@data %>% rowMeans() %>% sort(decreasing = T) %>% head(5000) %>% names()
  # features = intersect(var_features, top_expressed_features)
  features = var_features

  # find DEG
  deg = FindMarkers(
    object = patient_obj,
    ident.1 = "HPV+",
    ident.2 = "HPV-",
    features = features,
    logfc.threshold = 0,
    min.pct = 0.1,
    densify = T,
    mean.fxn = function(x) {
      return(log(rowMeans(x) + 1, base = 2)) # change func to calculate logFC in log space data (default to exponent data)
    }
  )
  deg$fdr <- p.adjust(p = as.vector(deg$p_val) , method = "fdr")
  all_deg[[patient]] = deg
}
```



```{r}
signature_fc = 1.3
all_sig_deg = list()
for (patient in unique(opscc_hpvPos$patient)) {
sig_deg =   all_deg[[patient]] %>% filter(avg_log2FC > log2(signature_fc) & fdr < signature_fdr) %>% rownames()
all_sig_deg[[patient]] = sig_deg
}

data <- data.frame(value = unlist(all_sig_deg), vector_id = rep(1:length(all_sig_deg), sapply(all_sig_deg, length)))

common_values <- data %>%
  group_by(value) %>%
  dplyr::summarize(count = n()) %>%
  filter(count >= 8 ) %>%
  pull(value)
print(common_values)
# lapply(all_sig_deg, function (x)  "CBR1" %in% x) #test
```

