---
title: '`r rstudioapi::getSourceEditorContext()$path %>% basename() %>% gsub(pattern = "\\.Rmd",replacement = "")`' 
author: "Avishai Wizel"
date: '`r Sys.time()`'
output: 
  html_notebook: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: FALSE
    number_sections: true
    toc_depth: 1
---



# Functions

```{r warning=FALSE}
```

# Data



```{r}
opscc = readRDS("./Rendered_notebooks/HPV_OPSCC_Analysis_PMC10191634/01_preprocess/opscc_suerat.RDS")
library(readxl)
metadata = read_excel(path = "./Input_data/HPV_OPSCC_Analysis_PMC10191634/NIHMS1892753-supplement-Supp_Tables.xlsx",
          sheet = "S4 - Cell Table",progress = T,skip = 1,col_names = T)

# remove HPV- patients
hpv_neg<-c("OP10","OP12","OP16","OP19","OP8")
hpv_pos = unique(metadata$Patient)[! unique(metadata$Patient) %in% hpv_neg]
opscc_hpvPos = subset(opscc,subset = patient %in% hpv_pos)
```


# MYB-HPV cor

```{r}
# get hpv genes and calc score
hpv_16_genes = rownames(opscc_hpvPos)[ startsWith(x =rownames(opscc_hpvPos),prefix =  "HPV16")]
hpv_score = FetchData(object = opscc_hpvPos,vars = hpv_16_genes,slot = "counts") %>% rowSums()
hpv_score_df = data.frame(hpv_score,row.names = names(hpv_score))
opscc_hpvPos = AddMetaData(object = opscc_hpvPos,metadata = hpv_score_df)
```


```{r fig.height=10, fig.width=10}
data = opscc_hpvPos 
myb_vs_hpv = FetchData(object = data, vars = c("hpv_score", "MYB","patient"),slot = "data")
sp <- ggscatter(myb_vs_hpv, x = "hpv_score", y = "MYB",
   add = "reg.line",  # Add regressin line
   add.params = list(color = "blue", fill = "lightgray"), # Customize reg. line
   conf.int = TRUE # Add confidence interval
   ) +  facet_wrap(~ patient, scales="free")
# Add correlation coefficient
sp + stat_cor(method = "pearson")

```

```{r}
VlnPlot(object = opscc_hpvPos,features = "MYB",group.by = "patient")
FetchData(object = opscc_hpvPos,vars = c("MYB","patient"))%>% 
  dplyr::group_by(patient) %>% 
  summarise(MYB = sum(MYB)) %>% 
  arrange(MYB)
```

```{r fig.height=6, fig.width=10}
genes_by_tp = FetchData(object = opscc_hpvPos,vars = c("hpv", "MYB","hpv_score","patient"),slot = "data")  %>% 
  mutate(hpv = if_else(condition = hpv_score>=3,true = "HPV+",false = "HPV-")) 


# all cells by patient boxplot
formula <- as.formula("MYB ~ hpv")

#plot and split by patient:
stat.test <- genes_by_tp %>%
  group_by(patient) %>%
  t_test(formula) %>%
  adjust_pvalue(method = "fdr") %>%
  add_significance() %>%
  add_xy_position(x = "hpv") %>%
  mutate(p.adj = signif(p.adj, digits = 2))
stat.test


plt = ggplot(genes_by_tp, aes(x = hpv, y = MYB)) +
  geom_violin(scale = "width") +
  geom_boxplot(width = 0.1, outlier.shape = NA) +
  facet_wrap( ~ patient, scales = "free") +
  stat_pvalue_manual(stat.test, label = "{p.adj}")  + #add p value
  scale_y_continuous(expand = expansion(mult = c(0.05, 0.2))) # Add 10% spaces between the p-value labels and the plot border
plt
```

# wilcox by patient

```{r}
# plot by patients
genes_by_tp = FetchData(object = opscc_hpvPos,vars = c("MYB","patient","hpv","hpv_score"),slot = "data") %>% 
  mutate(hpv = if_else(condition = hpv_score>=15,true = "HPV+",false = "HPV-")) %>% 
  filter(!patient %in% c("OP13","OP35","OP6")) %>% 
  mutate(patient_and_hpv = paste(patient,hpv,sep = "_")) %>% 
  dplyr::group_by(patient,patient_and_hpv,hpv) %>% 
  summarise(MYB = mean(MYB)) 

formula <- as.formula("MYB ~ hpv")

#plot and split by patient:
stat.test = compare_means(
  formula = formula ,
  data = genes_by_tp,
  method = "wilcox.test",
  p.adjust.method = "fdr",paired = F
) # Add pairwise comparisons p-value



plt = ggplot(genes_by_tp, aes(x = hpv, y = MYB)) +
  geom_boxplot(width = 0.1,outlier.shape = NA) + geom_jitter(shape=16, position=position_jitter(0.2))
plt = plt + stat_pvalue_manual(stat.test,
                               label = paste0(stat.test$method, ", p = {p.adj}"),
                               #add p value
                               y.position = 0.2)+ ggtitle("By sample") # set position at the top value
plt



```


# HMSC HPV signature DEG 

```{r fig.height=5, fig.width=12}
library(rstatix)

hmsc_deg = read.table(file = "./Data_out/HPV_analysis/hpv_deg_df.csv",row.names = 1)
top_genes = hmsc_deg %>% filter(.$fdr<0.05) %>% filter(.$avg_diff>log2(1.5)) %>%  arrange(dplyr::desc(.$avg_diff)) %>% head(5) %>% rownames()
top_genes = c(top_genes, "MYB", "JAG1")

myb_vs_hpv = FetchData(object = opscc_hpvPos,vars = c("hpv",top_genes))
df = reshape2::melt(myb_vs_hpv,value.name = "logTPM") %>% dplyr::rename(gene = variable)


stat.test <- df %>%
    group_by(gene) %>%
  wilcox_test(logTPM ~ hpv) %>%
  mutate(y.position = 5)

stat.test

stat.test <- stat.test %>% 
  add_xy_position(x = "gene", dodge = 0.8)

p = ggviolin(
  df,
  x = "gene",
  y = "logTPM",
  fill = "hpv",
  palette = "jco",scale = 'width',trim = T,
  add = "boxplot"
)+ stat_pvalue_manual(stat.test,y.position = 4, label = "p = {p}",remove.bracket = F)

p


 ggplot(df, aes(x = gene, y = logTPM, group = interaction(gene,hpv))) +
   geom_violin(scale = 'width',trim=T,position = position_dodge(0.8),aes(fill =hpv)) +
   geom_boxplot(position = position_dodge(0.8), outlier.shape = NA, coef=0,width = 0.15, fill="white")+ 
   stat_pvalue_manual(stat.test,y.position = 3.2, label = "p = {p}",remove.bracket = F)+
  stat_summary(aes(fill =hpv),inherit.aes = T,fun.data = function(x) data.frame(y=3.8, label = round(mean(x),digits = 2)), geom="text",position = position_dodge(0.8))
 
 
  ggplot(df, aes(x = gene, y = logTPM)) +
   geom_boxplot(position = position_dodge(0.8), coef=0,width = 0.75,aes(fill =hpv))+
  stat_summary(aes(fill =hpv),inherit.aes = T,fun.data = function(x) data.frame(y=3.8, label = round(mean(x),digits = 2)), geom="text",position = position_dodge(0.8)) + 
   stat_pvalue_manual(stat.test,y.position = 3.5, label = "p = {p}",remove.bracket = F)
 
  

```