---
title: '`r rstudioapi::getSourceEditorContext()$path %>% basename() %>% gsub(pattern = "\\.Rmd",replacement = "")`' 
author: "Avishai Wizel"
date: '`r Sys.time()`'
output: 
  html_notebook: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: FALSE
    number_sections: true
    toc_depth: 1
---



# Functions

```{r warning=FALSE}
```

# Data

```{r}
opscc = readRDS("./Rendered_notebooks/HPV_OPSCC_Analysis_PMC10191634/01_preprocess/opscc_suerat.RDS")
library(readxl)
metadata = read_excel(path = "./Input_data/HPV_OPSCC_Analysis_PMC10191634/NIHMS1892753-supplement-Supp_Tables.xlsx",
          sheet = "S4 - Cell Table",progress = T,skip = 1,col_names = T)

# remove HPV- patients
hpv_neg<-c("OP10","OP12","OP16","OP19","OP8")
hpv_pos = unique(metadata$Patient)[! unique(metadata$Patient) %in% hpv_neg]
opscc_hpvPos = subset(opscc,subset = patient %in% hpv_pos)
```


# test with original functions

```{r}
# from https://github.com/micmin3/HPV_OPSCC_Analysis/blob/main/functions.R
filter.umi<-function(matrix,
                     cells,
                     min_umi=5,
                     min_cells=20,
                     min_avlog=4,
                     centre="mean",
                     ref=NULL,
                     log=TRUE,
                     cut=NULL,
                     start="umi",
                     whitelist=NULL,
                     sparse=FALSE){
  m2<-matrix[,colnames(matrix) %in% cells]
  #Merge doublet genes
  m2<-Matrix.utils::aggregate.Matrix(m2,rownames(m2),fun="sum")

  #UMI to TPM
  if(start=="umi"){
  count_sum <- colSums(m2)  #apply(m2, 2, sum)
  tpmmat <- (t(t(m2)/count_sum))*1000000}
  if(start=="tpm"){tpmmat<-m2}
  #Average logtransformed tpm for filtering
  tpmav<- rowMeans(tpmmat) #apply(tpmmat,1,mean)
  logfilt<-log2((tpmav)+1)
  #UMI threshold for genes highly expressed in few cells
  if(isFALSE(sparse)){
  if(is.null(cut)){umi_threshold<-apply(m2,1,function(x)sum(x>=min_umi))}else{
    z1<-ntile(cells,cut)
    zn<-unique(z1)
    l1<-parallel::mclapply(zn,mc.cores=cut,function(x){
      apply(m2[,z1==x],1,function(y)sum(y>=min_umi))
    })
    d1<-do.call(cbind,l1)
    umi_threshold<-rowSums(d1)
      }
  #Filter genes with mean log expression > 4 OR passing UMI threshold
  genestokeep <- logfilt>=min_avlog|umi_threshold>=min_cells|names(logfilt) %in% whitelist}else{
  genestokeep <- logfilt>=min_avlog|names(logfilt) %in% whitelist
  }
  filtered.matrix <- tpmmat[genestokeep,]
  #Logtransform and centre
  if(isFALSE(log)){uncmat<-filtered.matrix}
  if(isTRUE(log)){
    if(isTRUE(sparse)){
    uncmat<-filtered.matrix
    uncmat[uncmat>0]<-log2( (uncmat[uncmat>0]/10) +1)
    }else{uncmat<-log2( (filtered.matrix/10) +1)}
  }
  if(centre=="mean"){avg <- rowMeans(uncmat)} #apply(uncmat, 1, mean)}
  if(centre=="median"){avg <- rowMedians(uncmat)}
  if(centre=="median" | centre=="mean"){centmat <- sweep(uncmat,1,avg)}
  if(centre=="ref"){centmat<-sweep(uncmat,1,ref[names(ref) %in% rownames(uncmat)])}
  if(centre!="none"){return(centmat)}
  if(centre=="none"){return(uncmat)}
}

TPMtoLog<-function(x,centre=FALSE){
  
  logged<-log2((x/10) +1)
  if(isTRUE(centre)){
    av<-rowMeans(logged)
    logged<-sweep(logged,1,av)
      }
  return(logged)
}
```


```{r}
hpv_16_genes = rownames(opscc_hpvPos)[ startsWith(x =rownames(opscc_hpvPos),prefix =  "HPV16")]
a = filter.umi(matrix = opscc_hpvPos@assays$RNA@counts,cells = colnames(opscc_hpvPos %>% subset(patient == "OP14")),whitelist = HPVgenes)
genes = hpv_16_genes[hpv_16_genes %in% rownames(a)]
score = a[genes,] %>% colMeans()

myb_vs_hpv = data.frame(hpv_score = score, MYB= a["MYB",],row.names = colnames(a))

sp <- ggscatter(myb_vs_hpv, x = "hpv_score", y = "MYB",
   add = "reg.line",  # Add regressin line
   add.params = list(color = "blue", fill = "lightgray"), # Customize reg. line
   conf.int = TRUE # Add confidence interval
   )
# Add correlation coefficient
sp + stat_cor(method = "pearson")
```

```{r}
library(rstatix)
merged = opscc@assays$RNA@counts
metadata = as.data.frame(metadata)
rownames(metadata) = metadata$Cell_barcode
bm<- metadata %>% filter(Cancer_assignment=="Cancer") %>% rownames() %>%
  filter.umi(matrix=merged) %>% as.data.frame()

myb_vs_hpv = bm[top_genes,] %>% t() %>% as.data.frame() %>% dplyr::select(-5) 
myb_vs_hpv$hpv = metadata[rownames(myb_vs_hpv),"HPV"]

df = reshape2::melt(myb_vs_hpv,value.name = "logTPM") %>% dplyr::rename(gene = variable)


stat.test <- df %>%
    group_by(gene) %>%
  wilcox_test(logTPM ~ hpv) %>%
  mutate(y.position = 5)

stat.test

stat.test <- stat.test %>% 
  add_xy_position(x = "gene", dodge = 0.8)

p = ggviolin(
  df,
  x = "gene",
  y = "logTPM",
  fill = "hpv",
  palette = "jco",scale = 'width',trim = T,
  add = "boxplot"
)+ stat_pvalue_manual(stat.test,y.position = 4, label = "p = {p}",remove.bracket = F)

p


 ggplot(df, aes(x = gene, y = logTPM, group = interaction(gene,hpv))) +
   geom_violin(scale = 'width',trim=T,position = position_dodge(0.8),aes(fill =hpv)) +
   geom_boxplot(position = position_dodge(0.8), outlier.shape = NA, coef=0,width = 0.15, fill="white")+ 
   stat_pvalue_manual(stat.test,y.position = 5.3, label = "p = {p}",remove.bracket = F)+
  stat_summary(aes(fill =hpv),inherit.aes = T,fun.data = function(x) data.frame(y=6.2, label = round(mean(x),digits = 2)), geom="text",position = position_dodge(0.8))
 
 
  ggplot(df, aes(x = gene, y = logTPM)) +
   geom_boxplot(position = position_dodge(0.8), coef=0,width = 0.75,aes(fill =hpv))+
  stat_summary(aes(fill =hpv),inherit.aes = T,fun.data = function(x) data.frame(y=3.8, label = round(mean(x),digits = 2)), geom="text",position = position_dodge(0.8)) + 
   stat_pvalue_manual(stat.test,y.position = 3.5, label = "p = {p}",remove.bracket = F)
 
  
```


```{r}
myb_vs_hpv = bm[top_genes,] %>% t() %>% as.data.frame() %>% dplyr::select(-5) 
myb_vs_hpv$hpv = metadata[rownames(myb_vs_hpv),"HPV"]
myb_vs_hpv$patient = metadata[rownames(myb_vs_hpv),"Patient"]
myb_vs_hpv = myb_vs_hpv %>% 
  filter(!patient %in% c(hpv_neg)) %>% 
  mutate(patient_and_hpv = paste(patient,hpv,sep = "_")) %>% 
  dplyr::group_by(patient_and_hpv,hpv,patient) %>% 
  summarise(MYB = mean(MYB)) 

formula <- as.formula("MYB ~ hpv")

#plot and split by patient:
stat.test = compare_means(
  formula = formula ,
  data = myb_vs_hpv,
  method = "wilcox.test",
  p.adjust.method = "fdr",paired = F
) # Add pairwise comparisons p-value


library(ggrepel)

pos <- position_quasirandom()
plt = ggplot(myb_vs_hpv, aes(x = hpv, y = MYB,label = patient)) +
  # geom_text_repel(min.segment.length = 0,position = pos,box.padding = 1,max.overlaps = 20, segment.color = "grey50",  segment.size  = 0.2)+
  geom_boxplot(width = 0.1,outlier.shape = NA) + geom_jitter(shape=16, position=pos) 

plt = plt + stat_pvalue_manual(stat.test,
                               label = paste0(stat.test$method, ", p = {p.adj}"),
                               #add p value
                               y.position = 1.5)+ ggtitle("By sample") # set position at the top value
plt


```
# from michael



```{r}
merged = opscc@assays$RNA@counts
metadata_cancer = metadata %>% filter(Cancer_assignment == "Cancer" )

hpv_16_genes = rownames(opscc)[ startsWith(x =rownames(opscc),prefix =  "HPV16")]
hpv_score = FetchData(object = opscc,vars = hpv_16_genes,slot = "counts") %>% rowSums() %>% as.data.frame() %>%
  setNames(c("hpv_score")) %>% rownames_to_column(var = "Cell_barcode")
metadata_cancer  = left_join(x = metadata_cancer,y = hpv_score,by =  c("Cell_barcode"= "Cell_barcode"))
metadata_cancer = metadata_cancer %>% as.data.frame()
rownames(metadata_cancer) = metadata_cancer$Cell_barcode


pl<-metadata_cancer %>% filter(HPV=="HPV+") %>% pull(Patient) %>% unique()

gl<-c("MYB","ANLN","AK4","PBRM1","IFT122","CAPG","JAG1")

library(parallel)
ff<-mclapply(pl,function(x){
  c1<-metadata_cancer %>% filter(Patient == x) %>%  rownames() #Select only cancer cells
  
  # m1<- #Raw UMI matrix for Sample x
  m1 <-  filter.umi(merged,cells=c1,whitelist = gl)
  
  m2<-m1[gl,] %>% t() %>% as.matrix() %>% as.data.frame()
  cbind.data.frame(metadata_cancer[c1,c("Patient","hpv_score","HPV")],m2)
  })
ff2<-do.call(rbind,ff)
ff2




```
```{r}
# per patient boxplot

ff2_by_patient = ff2 %>% 
  mutate(patient_and_hpv = paste(Patient,HPV,sep = "_")) %>% 
  dplyr::group_by(Patient,patient_and_hpv,HPV) %>% 
  summarise(MYB = mean(MYB)) 


formula <- as.formula("MYB ~ HPV")

#plot and split by patient:
stat.test = compare_means(
  formula = formula ,
  data = ff2_by_patient,
  method = "wilcox.test",
  p.adjust.method = "fdr",paired = F
) # Add pairwise comparisons p-value



plt = ggplot(ff2_by_patient, aes(x = HPV, y = MYB, label = Patient)) +
  geom_boxplot(width = 0.1,outlier.shape = NA) + geom_jitter(shape=16, position=position_jitter(0.2))
plt = plt + stat_pvalue_manual(stat.test,
                               label = paste0(stat.test$method, ", p = {p.adj}"),
                               #add p value
                               y.position = 0.2)+ ggtitle("By sample") # set position at the top value
plt

```
```{r}
library(ggpubr)
library(rstatix)

# all cells by patient boxplot
formula <- as.formula("MYB ~ HPV")

#plot and split by patient:
stat.test <- ff2 %>%
  group_by(Patient) %>%
  t_test(formula) %>%
  adjust_pvalue(method = "fdr") %>%
  add_significance()%>% 
  add_xy_position(x = "HPV") %>% 
  mutate(p.adj = signif(p.adj,digits = 2))
stat.test 



plt = ggplot(ff2, aes(x = HPV, y = MYB)) +
  geom_violin(scale = "width") + geom_boxplot(width = 0.1, outlier.shape = NA) +
  facet_wrap( ~ Patient, scales = "free")


plt = plt +stat_pvalue_manual(stat.test, label = "{p.adj}")  + #add p value
  scale_y_continuous(expand = expansion(mult = c(0.05, 0.2))) # Add 10% spaces between the p-value labels and the plot border

plt
```


```{r fig.height=10, fig.width=10}
# correlation

sp <- ggscatter(ff2, x = "hpv_score", y = "MYB",
   add = "reg.line",  # Add regressin line
   add.params = list(color = "blue", fill = "lightgray"), # Customize reg. line
   conf.int = TRUE # Add confidence interval
   ) +  facet_wrap(~ Patient, scales="free")
# Add correlation coefficient
sp + stat_cor(method = "pearson")
```

