---
title: "HMSC_HPV_signature"
author: "Avishai Wizel"
date: '`r Sys.time()`'
output:
  # html_notebook: 
  #   code_folding: hide
  #   toc: true
  #   toc_collapse: true
  #   toc_float:
  #     collapsed: false
  #   number_sections: true
  #   toc_depth: 1
  html_document: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: TRUE
    number_sections: true
    toc_depth: 2
    df_print: paged
params: 
  data_out_dir: "./temp_data/" 
  input_data: !r c(
    opscc =  "./Reports/HPV_OPSCC_Analysis_PMC10191634/01_preprocess/opscc_suerat.RDS",
    hmsc_deg = "./Reports/HMSC/05_HPV_analysis/HMSC_hpv_deg_df.csv",
        global_params  = "./Input_data/global_params.R")

---




```{r}
if (interactive()) {
  source("./pipe.R")
  input = get_input(get_current_path())
  output = get_output(get_current_path())
}
```


# Functions

```{r warning=FALSE}
library(rstatix)
source(input$fc_params)
library(ComplexHeatmap)
library(ggpubr)

```

# Data

```{r}
opscc = readRDS(input$opscc)
library(readxl)
avg_log2FC_cutoff = log2(signature_fc)
fdr_cutoff = signature_fdr

# remove HPV- patients
hpv_neg<-c("OP10","OP12","OP16","OP19","OP8")
hpv_pos = unique(opscc$patient )[! unique(opscc$patient) %in% hpv_neg]
opscc_hpvPos = subset(opscc,subset = patient %in% hpv_pos)
opscc_hpvPos$patient <- factor(opscc_hpvPos$patient, levels = c("OP4", "OP5", "OP6", "OP9", "OP13", "OP14", "OP17", "OP20",
"OP33", "OP34", "OP35"))# sort patients alphanumeric based on the numeric part


hmsc_deg = read.table(file = params$input_data["hmsc_deg"],row.names = 1,sep = ",",header = T)

hmsc_signatue = rownames(hmsc_deg[hmsc_deg$fdr<fdr_cutoff & hmsc_deg$avg_log2FC>avg_log2FC_cutoff,])

hmsc_signatue
```


```{r}
# get hpv genes and calc score
hpv_16_genes = rownames(opscc_hpvPos)[ startsWith(x =rownames(opscc_hpvPos),prefix =  "HPV16")]
hpv_score = FetchData(object = opscc_hpvPos,vars = hpv_16_genes,slot = "counts") %>% rowSums()
hpv_score_df = data.frame(hpv_score,row.names = names(hpv_score))
opscc_hpvPos = AddMetaData(object = opscc_hpvPos,metadata = hpv_score_df)
```

```{r}

#set HPV to consider + if hpv_score>3
opscc_hpvPos$hpv = FetchData(object = opscc_hpvPos,vars = "hpv") %>%
 mutate(hpv = if_else(condition = hpv_score>=3,true = "HPV+",false = "HPV-")) %>% 
  pull(hpv)

```



```{r}

# add score
hpv_signature_score = FetchData(object = opscc_hpvPos,vars = hmsc_signatue,slot = "data") %>% rowMeans()
hpv_signature = data.frame(hpv_signature_score,row.names = names(hpv_signature_score))
opscc_hpvPos = AddMetaData(object = opscc_hpvPos,metadata = hpv_signature)

```


```{r fig.height=4, fig.width=10}

genes_by_tp = FetchData(object = opscc_hpvPos,vars = c("hpv", "hpv_signature_score","patient"),slot = "data") %>%
    filter(patient != "OP13") 



#plot and split by patient:
stat.test <- genes_by_tp %>%
  group_by(patient) %>% 
  t_test(hpv_signature_score ~ hpv) %>%
  adjust_pvalue(method = "fdr") %>%
  add_significance() %>%
  add_xy_position(x = "hpv") %>%
  mutate(p = signif(p, digits = 2))
stat.test


plt = ggplot(genes_by_tp, aes(x = hpv, y = hpv_signature_score)) +
  geom_violin(scale = "width",aes(fill = hpv)) +
  geom_boxplot(width = 0.2, outlier.shape = NA) +
  stat_pvalue_manual(stat.test, label = "{p}")  + #add p value
  facet_wrap("patient",scales="fixed",ncol = 5)+
  scale_y_continuous(expand = expansion(mult = c(0.05, 0.2))) + # Add 10% spaces between the p-value labels and the plot border
  ggtitle("HMSC HPV signature")+
  theme_minimal()+
  ylab("Signature Score")
plt
```



```{r}
pdf(paste0(params$data_out_dir,"OPSCC_violin_plots_HMSC_HPV_signature.pdf"),height = 4,width = 10)
plt
dev.off()
```

```{r}
#just op13
genes_by_tp = FetchData(object = opscc_hpvPos,vars = c("hpv", "hpv_signature_score","patient"),slot = "data") %>% filter (patient == "OP13")



#plot and split by patient:
stat.test <- genes_by_tp %>%
  t_test(hpv_signature_score ~ hpv) %>%
  adjust_pvalue(method = "fdr") %>%
  add_significance() %>%
  add_xy_position(x = "hpv") %>%
  mutate(p.adj = signif(p.adj, digits = 2))
stat.test


plt = ggplot(genes_by_tp, aes(x = hpv, y = hpv_signature_score)) +
  geom_violin(scale = "width",aes(fill = hpv)) +
  geom_boxplot(width = 0.2, outlier.shape = NA) +
  stat_pvalue_manual(stat.test, label = "{p.adj}")  + #add p value
  scale_y_continuous(expand = expansion(mult = c(0.05, 0.2))) + # Add 10% spaces between the p-value labels and the plot border
  ggtitle("HMSC HPV signature")+
  theme_minimal()+
  ylab("Signature Score")
plt
```
```{r fig.height=6, fig.width=8}
pdf(paste0(params$data_out_dir,"OPSCC_violin_plots_HMSC_HPV_signature_OP13.pdf"))
plt
dev.off()
```


```{r}
#TODO add clinical to input paths
clinial = read.csv(file = "./Input_data/HPV_OPSCC_Analysis_PMC10191634/clinical.csv",row.names = 1)
clinial$patient = c("OP20", "OP4", "OP5", "OP14", 
"OP17", "OP34", "OP33", "OP35", 
"OP6", "OP9", "OP13")

data =  FetchData(object = opscc_hpvPos,vars = c("hpv_signature_score","patient"),slot = "data") %>% 
  filter (patient != "OP13") %>% 
  group_by(patient) %>% 
  dplyr::summarise(mean_hpv_score = mean(hpv_signature_score, na.rm = TRUE), .groups = "drop")

  
all_data = left_join(data,clinial,by = c('patient' = 'patient'))
all_data$Overall.stage = factor(as.character(all_data$Overall.stage),levels = c("1","2","3"))
all_data 
```

```{r}
ggplot(all_data) +
  aes(x = Overall.stage, y = mean_hpv_score, fill = Overall.stage) +
  geom_boxplot() +
  geom_jitter()+
  theme(legend.position = "none")
```
```{r fig.height=5, fig.width=7}

library(ggstatsplot)
jitter <- position_jitter(width = 0.1)

ggbetweenstats(
  data = all_data,
  x = Overall.stage,
  y = mean_hpv_score,
  type = "nonparametric", # ANOVA or Kruskal-Wallis
  plot.type = "box",
  pairwise.comparisons = TRUE,
  pairwise.display = "all",
  centrality.plotting = FALSE,
  bf.message = FALSE,
  p.adjust.method = "fdr",
  point.args = list(alpha = 1,position = jitter),
  violin.args = list(width = 0)
  
)
```

```{r}
all_data %>% filter(Overall.stage %in% c(1,2)) %>% 
  wilcox_test(mean_hpv_score ~ Overall.stage)
```

# session info
<button class="btn btn-primary" data-toggle="collapse" data-target="#BlockName"> Show/Hide </button>  
<div id="BlockName" class="collapse">  
```{r}
library(devtools)
session_info()
```

</div>