---
title: '`r rstudioapi::getSourceEditorContext()$path %>% basename() %>% gsub(pattern = "\\.Rmd",replacement = "")`' 
author: "Avishai Wizel"
date: '`r Sys.time()`'
output: 
  # html_notebook: 
  #   code_folding: hide
  #   toc: yes
  #   toc_collapse: yes
  #   toc_float: 
  #     collapsed: TRUE
  #   number_sections: true
  #   toc_depth: 2
  #   
  html_document: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: TRUE
    number_sections: true
    toc_depth: 2
params:
  log_tpm: FALSE
  data_out_dir: "./temp_data/" 
  input_data: "./Input_data/hsapiens_gene_ensembl_version_113"
  output_data: !r c("TCGA_HNSC_TPM.RDS","TCGA_CESC_TPM.RDS")
---


```{r package-options, include=FALSE}
knitr::opts_knit$set(progress = TRUE, verbose = TRUE)
```


```{r}
library(TCGAbiolinks)
library(biomaRt)
library(kableExtra)
library(rmarkdown)
ensembl = readRDS(params$input_data)
print(getGDCInfo()$data_release)
```

```{r}
build_datasets <- function(project_name, filter = list(sample_type = c("Primary Tumor"))) {
  library(data.table)
  data_dir = paste0(params$data_out_dir,"GDCdata")
  
  # from https://github.com/BioinformaticsFMRP/TCGAbiolinks/issues/493#issuecomment-1083311661
  # Defines the query to the GDC
  query <- GDCquery(project = project_name,
                    data.category = "Transcriptome Profiling",
                    data.type = "Gene Expression Quantification",
                    experimental.strategy = "RNA-Seq",
                    workflow.type = "STAR - Counts")
  
  # Get metadata matrix
  metadata <- query[[1]][[1]]
  
  # Download data using api
  GDCdownload(query, method = "api",directory = data_dir)
  
  # Get main directory where data is stored
  main_dir <- file.path(data_dir, project_name)
  # Get file list of downloaded files
  file_list <- file.path(data_dir, project_name,list.files(main_dir,recursive = TRUE)) 
  
  # Read first downloaded to get gene names
  test_tab <- read.table(file = file_list[1], sep = '\t', header = TRUE)
  # Delete header lines that don't contain usefull information
  test_tab <- test_tab[-c(1:4),]
  # STAR counts and tpm datasets
  tpm_data_frame <- data.frame(test_tab[,2])
  count_data_frame <- data.frame(test_tab[,2])
  
  # Append cycle to get the complete matrix
  for (i in c(1:length(file_list))) {
    # Read table
    test_tab <- fread(file = file_list[i],sep = "\t",header = T,data.table = F)
    # Delete not useful lines
    test_tab <- test_tab[-c(1:4),]
    # Column bind of tpm and counts data
    tpm_data_frame <- cbind(tpm_data_frame, test_tab[,9])
    sample_id = basename(dirname(file_list[i])) # get dir name
    sample_name = metadata[metadata$id == sample_id ,"cases.submitter_id"]
    colnames(tpm_data_frame)[i+1] = sample_name # col 1 is gene
    # count_data_frame <- cbind(count_data_frame, test_tab[,4])
    # Print progres from 0 to 1
    message(i/length(file_list)*100, " % completed \n")

  }
  # update col names
  colnames(tpm_data_frame)[1] = "Gene"
  genes = tpm_data_frame$Gene
  tpm_data_frame$Gene <- NULL
  
  
  
  # remove all 0 genes
  not_all_zero <-apply(tpm_data_frame, 1, function(row) any(row != 0))
  tpm_data_frame = tpm_data_frame[not_all_zero,]
  genes = genes[not_all_zero]
  
  
  # remove all rows that are not gene symbols
  results <- getBM(attributes=c("ensembl_gene_id","hgnc_symbol","transcript_biotype"), mart=ensembl)
  not_symbol = !genes %in% results$hgnc_symbol
  genes = genes[!not_symbol]
  tpm_data_frame = tpm_data_frame[!not_symbol,]
  rownames(tpm_data_frame) = make.unique(genes) 
  
  for (i in 1:length(filter)) {
    col = names(filter)[i]
    values = filter[[i]]
    primary_samples = metadata[metadata[[col]] %in% values,"cases.submitter_id"]
    tpm_data_frame = tpm_data_frame[,primary_samples]
  }
  return(tpm_data_frame)
}


```


# CECS
```{r}
project_name = "TCGA-CESC"
```

```{r}
cesc_tpm = build_datasets(project_name = "TCGA-CESC")
saveRDS(cesc_tpm,file = paste0(params$data_out_dir,"TCGA_CESC_TPM.RDS"))

```

# OPSCC

```{r}
project_name = "TCGA-HNSC"
```

```{r}
HNSC_tpm = build_datasets(project_name = project_name,filter = list(sample_type = c("Primary Tumor")))

saveRDS(HNSC_tpm,file = paste0(params$data_out_dir,"TCGA_HNSC_TPM.RDS"))

```


