---
title: '`r rstudioapi::getSourceEditorContext()$path %>% basename() %>% gsub(pattern = "\\.Rmd",replacement = "")`' 
author: "Avishai Wizel"
date: '`r Sys.time()`'
output: 
  html_notebook: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: FALSE
    number_sections: true
    toc_depth: 1
---



# Functions

```{r warning=FALSE}
```

# Data

```{r}

```

# Data

```{r}

mtx <- "./Data/cervical_cancer_data/Qiu et al/SCC1/GSM5917937_SCC_1_matrix.mtx.gz"
cells <- "./Data/cervical_cancer_data/Qiu et al/SCC1/GSM5917937_SCC_1_barcodes.tsv.gz"
features <-  "./Data/cervical_cancer_data/Qiu et al/SCC1/GSM5917937_SCC_1_features.tsv.gz"
SCC1.data <- ReadMtx(mtx = mtx, cells = cells, features = features)
SCC1 <- CreateSeuratObject(counts = SCC1.data, project = "scc", min.cells = 3, min.features = 200)
SCC1[["percent.mt"]] <- PercentageFeatureSet(SCC1, pattern = "^MT-")
SCC1 <- subset(SCC1, subset = percent.mt < 10)
SCC1 <- NormalizeData(SCC1)

```



```{r}
SCC1 <- FindVariableFeatures(SCC1,nfeatures = 2000)
SCC1 <- ScaleData(SCC1,features = VariableFeatures(SCC1),vars.to.regress = c("percent.mt","nCount_RNA"))
SCC1  %<>%  RunPCA( features = VariableFeatures(object = SCC1))
```

```{r}
ElbowPlot(SCC1,ndims = 50)
```

```{r}
SCC1  %<>%  FindNeighbors(dims = 1:20) %>%  FindClusters(resolution = 0.2) %>%  RunUMAP(dims = 1:20)
```

```{r}
DimPlot(SCC1,label = T)
```

```{r}
FeaturePlot(SCC1,features = "MYB")
```

```{r fig.height=7, fig.width=7,results='asis'}
library(patchwork)

p1 = FeaturePlot(object = SCC1,features = c("KRT18","EPCAM"),ncol = 1) + plot_annotation(
  title = 'epithelial markers')

p2 = FeaturePlot(object = SCC1,features = c("VWF", "PLVAP"),ncol = 1)+ plot_annotation(
  title = 'endothelial markers')

p3 = FeaturePlot(object = SCC1,features = c("COL1A1", "LUM"),ncol = 1)+ plot_annotation(
  title = 'fibroblasts  markers')

p4 = FeaturePlot(object = SCC1,features = c("ACTA2", "TAGLN"),ncol = 1)+ plot_annotation(
  title = 'smooth muscle markers')
p5 = FeaturePlot(object = SCC1,features = c("CSF3R"),ncol = 1)+ plot_annotation(
  title = 'neutrophils markers')
p6 = FeaturePlot(object = SCC1,features = c("CPA3"),ncol = 1)+ plot_annotation(
  title = 'mast markers')
p7 = FeaturePlot(object = SCC1,features = c("FCN1"),ncol = 1)+ plot_annotation(
  title = 'monocytes   markers')
p8 = FeaturePlot(object = SCC1,features = c("C1QB","LYZ"),ncol = 1)+ plot_annotation(
  title = 'macrophages    markers')
p9 = FeaturePlot(object = SCC1,features = c("IRF8"),ncol = 1)+ plot_annotation(
  title = 'dendritic markers')
p10 = FeaturePlot(object = SCC1,features = c("JCHAIN","MZB1"),ncol = 1)+ plot_annotation(
  title = 'B/plasma markers')
p11= FeaturePlot(object = SCC1,features = c("CD2","CD3D"),ncol = 1)+ plot_annotation(
  title = 'T markers')

for (p in list(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11)) {
  print_tab(plt = p,title = p$patches$annotation$title)

}
```
```{r}
SCC1_cancer <- subset(SCC1, subset = seurat_clusters %in% c(2))
```

```{r}
saveRDS(object = DietSeurat(SCC1_cancer),file = "./Data/cervical_cancer_data/Qiu et al/SCC1/SCC1_cancer.RDS")
```

<script src="https://hypothes.is/embed.js" async></script>

