---
title: '`r rstudioapi::getSourceEditorContext()$path %>% basename() %>% gsub(pattern = "\\.Rmd",replacement = "")`' 
author: "Avishai Wizel"
date: '`r Sys.time()`'
output: 
  html_notebook: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: FALSE
    number_sections: true
    toc_depth: 1
---




# Functions

```{r warning=FALSE}
```

```{r}
```

# Data

```{r}

mtx <- "./Data/cervical_cancer_data/Qiu et al/SCC3/GSM5917939_SCC_3_matrix.mtx.gz"
cells <- "./Data/cervical_cancer_data/Qiu et al/SCC3/GSM5917939_SCC_3_barcodes.tsv.gz"
features <-  "./Data/cervical_cancer_data/Qiu et al/SCC3/GSM5917939_SCC_3_features.tsv.gz"
SCC3.data <- ReadMtx(mtx = mtx, cells = cells, features = features)
SCC3 <- CreateSeuratObject(counts = SCC3.data, project = "scc", min.cells = 3, min.features = 200)
SCC3[["percent.mt"]] <- PercentageFeatureSet(SCC3, pattern = "^MT-")
SCC3 <- subset(SCC3, subset = percent.mt < 10)
SCC3 <- NormalizeData(SCC3)

```



```{r}
SCC3 <- FindVariableFeatures(SCC3,nfeatures = 2000)
SCC3 <- ScaleData(SCC3,features = VariableFeatures(SCC3),vars.to.regress = c("percent.mt","nCount_RNA"))
SCC3  %<>%  RunPCA( features = VariableFeatures(object = SCC3))
```

```{r}
ElbowPlot(SCC3,ndims = 50)

```
```{r}
SCC3  %<>%  FindNeighbors(dims = 1:20) %>%  FindClusters(resolution = 0.2) %>%  RunUMAP(dims = 1:20)
```

```{r}
DimPlot(SCC3,label = T)
```

```{r}
FeaturePlot(SCC3,features = "MYB")

```
```{r fig.height=7, fig.width=7,results='asis'}
library(patchwork)

p1 = FeaturePlot(object = SCC3,features = c("KRT18","EPCAM"),ncol = 1) + plot_annotation(
  title = 'epithelial markers')

p2 = FeaturePlot(object = SCC3,features = c("VWF", "PLVAP"),ncol = 1)+ plot_annotation(
  title = 'endothelial markers')

p3 = FeaturePlot(object = SCC3,features = c("COL1A1", "LUM"),ncol = 1)+ plot_annotation(
  title = 'fibroblasts  markers')

p4 = FeaturePlot(object = SCC3,features = c("ACTA2", "TAGLN"),ncol = 1)+ plot_annotation(
  title = 'smooth muscle markers')
p5 = FeaturePlot(object = SCC3,features = c("CSF3R"),ncol = 1)+ plot_annotation(
  title = 'neutrophils markers')
p6 = FeaturePlot(object = SCC3,features = c("CPA3"),ncol = 1)+ plot_annotation(
  title = 'mast markers')
p7 = FeaturePlot(object = SCC3,features = c("FCN1"),ncol = 1)+ plot_annotation(
  title = 'monocytes   markers')
p8 = FeaturePlot(object = SCC3,features = c("C1QB","LYZ"),ncol = 1)+ plot_annotation(
  title = 'macrophages    markers')
p9 = FeaturePlot(object = SCC3,features = c("IRF8"),ncol = 1)+ plot_annotation(
  title = 'dendritic markers')
p10 = FeaturePlot(object = SCC3,features = c("JCHAIN","MZB1"),ncol = 1)+ plot_annotation(
  title = 'B/plasma markers')
p11= FeaturePlot(object = SCC3,features = c("CD2","CD3D"),ncol = 1)+ plot_annotation(
  title = 'T markers')

for (p in list(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11)) {
  print_tab(plt = p,title = p$patches$annotation$title)

}
```

```{r}
SCC3_cancer <- subset(SCC3, subset = seurat_clusters %in% c(3,9,2))
```

```{r}
VlnPlot(object = SCC3_cancer,features = "MYB")
```

# HPV reads

```{r}
all_reads_per_cell = c()
runs = c("18158739","18158740","18158741","18158742")

for (run in runs) {
hpv_bam = read_tsv(file = "./Data/cervical_cancer_data/Qiu et al/SCC3/HPV/" %s+% run %s+% "_reads.tsv",col_select = 1,col_names = F)
reads_per_cell = str_extract(pattern = "CR:Z:.*$",string = hpv_bam$X1) %>% str_sub( start = 6)
all_reads_per_cell = c(reads_per_cell,all_reads_per_cell)


}

all_reads_per_cell = all_reads_per_cell%>% table() %>% as.data.frame() %>% column_to_rownames(".")
rownames(all_reads_per_cell) = paste0(rownames(all_reads_per_cell),"-1")
all_reads_per_cell
```

```{r}
zero_cells = colnames(SCC3_cancer)[!colnames(SCC3_cancer) %in% rownames(all_reads_per_cell)]
zero_cells_freq = data.frame(row.names = zero_cells,Freq = rep(0,length(zero_cells)))
reads_per_cell_all_cells = rbind(all_reads_per_cell,zero_cells_freq)
SCC3_cancer %<>% AddMetaData(metadata = reads_per_cell_all_cells,col.name = "HPV_reads")
hpv_reads = FetchData(object = SCC3_cancer,vars = "HPV_reads")
```

```{r}
data = hpv_reads %>% mutate("0 reads" = if_else(condition = HPV_reads == 0,true = 1,false = 0))
data = data %>% mutate("1 reads" = if_else(condition = HPV_reads == 1,true = 1,false = 0))
data = data %>% mutate("2 reads" = if_else(condition = HPV_reads == 2,true = 1,false = 0))
data = data %>% mutate("3-23 reads" = if_else(condition = HPV_reads >=3 &HPV_reads  <24,true = 1,false = 0))
data = data %>% mutate("24+ reads" = if_else(condition = HPV_reads >=24,true = 1,false = 0))
data = colSums(data[,2:ncol(data)]) %>% as.data.frame()
names(data)[1] = "count"
data = rownames_to_column(data,var = "bin")
ggplot(data=data, aes(x=factor(bin,levels = c("0 reads","1 reads","2 reads","3-23 reads","24+ reads")), y=count)) +
  geom_bar(stat="identity", fill="steelblue") + xlab("HPV Reads")+ theme_minimal()+
  geom_text(aes(label=count), vjust=-0.5, color="black", size=3.5)
```


```{r}

hpv_positive = hpv_reads %>% dplyr::mutate(hpv_positive = case_when(HPV_reads >= 2 ~ "positive",
                                                                    HPV_reads < 2 ~ "negative")
)


SCC3_cancer = AddMetaData(object = SCC3_cancer,metadata = hpv_positive)

myb_data = FetchData(object = SCC3_cancer,vars = ("MYB"))%>% dplyr::mutate(myb_positive = case_when(MYB > 0 ~ "positive",
                                                                    MYB == 0 ~ "negative")) %>% dplyr::select("myb_positive")
SCC3_cancer = AddMetaData(object = SCC3_cancer,metadata = myb_data,col.name = "MYB_positive")

```

```{r}
saveRDS(object = DietSeurat(SCC3_cancer),file = "./Data/cervical_cancer_data/Qiu et al/SCC3/SCC3_cancer_processed.RDS")
```

```{r}
DimPlot(object = SCC3_cancer,group.by  = c("hpv_positive"),pt.size = 0.5)
DimPlot(object = SCC3_cancer,group.by  = c("MYB_positive"),pt.size = 0.5)
FeaturePlot(object = SCC3_cancer,features = c("HPV_reads"),pt.size = 0.5)
FeaturePlot(object = SCC3_cancer,features = c("MYB"),pt.size = 0.5)

```


```{r}
library(ggrepel)
data = FetchData(object = SCC3_cancer,vars =  c("MYB","HPV_reads"))


ggplot(data,
           aes(x = MYB, y = HPV_reads)) +  geom_smooth(method = lm) +
  geom_point() + stat_cor(method = "pearson")
```

# Boxplot HPV_positive VS MYB

```{r}
myb_vs_hpv = FetchData(object = SCC3_cancer, vars = c("hpv_positive", "MYB"))
myb_vs_hpv$hpv_positive = paste("HPV", myb_vs_hpv$hpv_positive)
p1 = ggplot(myb_vs_hpv,aes( x = hpv_positive, y = MYB,, fill=hpv_positive))+ 
    geom_violin(trim=FALSE) + theme_minimal()+
  stat_compare_means(method = "wilcox.test",comparisons = list(c("HPV positive","HPV negative")))+
  stat_summary(fun.data = function(x) data.frame(y=max(x)*1.2, label = paste("Mean=",round(mean(x),digits = 2))), geom="text") +ylab("MYB")+ggtitle("SCC3") +
  geom_boxplot(width=.1, outlier.shape=NA) 


print_tab(p1,title = gene)

```

```{r}
myb_vs_hpv = FetchData(object = SCC3_cancer, vars = c("HPV_reads", "MYB_positive"))

p2 = ggplot(myb_vs_hpv,aes( x = MYB_positive, y =HPV_reads ,  fill=MYB_positive))+ 
    geom_violin(trim=FALSE) + theme_minimal()+
  stat_compare_means(method = "wilcox.test",comparisons = list(c("positive","negative")))+
  stat_summary(fun.data = function(x) data.frame(y=max(x)*1.2, label = paste("Mean=",round(mean(x),digits = 2))), geom="text")+
  geom_boxplot(width=.1, outlier.shape=NA) 


print_tab(p2,title = gene)

```

```{r}
library(ggstatsplot)
df  = FetchData(object = SCC3_cancer,vars = c("hpv_positive","MYB_positive")) %>% droplevels() 
test = fisher.test(table(df))
plt = ggbarstats(
  df,
  MYB_positive,
  hpv_positive,
  results.subtitle = FALSE,
  subtitle = paste0("Fisher's exact test", ", p-value = ",
                    round(test$p.value, 13))
)

print_tab(plt = plt,title = "fisher")
```


```{r fig.height=6, fig.width=12}
p1+p2 +plt
```






<script src="https://hypothes.is/embed.js" async></script>

