---
title: '`r rstudioapi::getSourceEditorContext()$path %>% basename() %>% gsub(pattern = "\\.Rmd",replacement = "")`' 
author: "Avishai Wizel"
date: '`r Sys.time()`'
output: 
  html_notebook: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: FALSE
    number_sections: true
    toc_depth: 1
    
  html_document: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: TRUE
    number_sections: true
    toc_depth: 2
params:
  data_out_dir: "./Data_out/" 

---

```{r}
paged_table(as.data.frame(unlist(params)))
```

# Functions

```{r warning=FALSE}
```

# Data

```{r}
acc_all_cells = readRDS("./Data_out/01_create_data_2024-05-09/acc_tpm_nCount_mito_no146_15k_with_ACC1.RDS")
```


## UMAP
```{r fig.height=6, fig.width=8}
ident = plyr::revalue(acc_all_cells@meta.data[["patient.ident"]], c("ACC1"="HMSC"))
acc_all_cells@meta.data[["patient.ident"]] <- ident

p = DimPlot(acc_all_cells, reduction = "umap", label = TRUE, pt.size = 0.5,group.by = "patient.ident",repel = F)  +
  ggtitle(element_blank())

p
```

```{r}
# save plot
pdf(file = paste0(params$data_out_dir,"all_cells_umap.pdf"),width = 8,height = 6)
p
dev.off()
```
